### ISSUE TITLE
Investigate why HHS Protect isn't seeing OTC results from Cue

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#10062]
## Problem statement

We received the following email on June 22, 2023: 

From: Weitz, Andrew (NIH/NIBIB) [E] <andrew.weitz@nih.gov>
Sent: Thursday, June 22, 2023 10:44 AM
To: Duranovic, Arnej (CDC/DDPHSS/OD) (CTR) <umn2@cdc.gov>
Cc: Kpamegan, Norris (CDC/DDID/NCEZID/OD) (CTR) <svi5@cdc.gov>
Subject: Issue with Cue results
 
Hi Arnej,

 

Within HHS Protect, we are not seeing any OTC results from Cue after May 25th.  Prior to that date, >1000 results were being sent per day.  Would ReportStream mind following up with Cue to see why?

 

Thanks,

Andrew
## What you need to know
- [ ] LaFreda responded to the email to let Arnej know that she would follow up on this request with the Customer Support Team.

## Acceptance criteria

- [ ] Provide explanation to Andrew on what's happening.

## To do

- [ ] Engineer to investigate the data we've received from Cue
- [ ] After engineer has investigated, Customer support to reach out to Cue for an explanation.

**Comment by GilmoreA6** [comment]
Sent email to CUE:

"Good Morning Becky,

I am reaching out to inquire about the status of Cue Health sending COVID-19 results to ReportStream. It looks like the last time we received any data from Cue was 05/25/23 and we wanted to reach out and see if you were having any issues with reporting to us or if Cue has decided to no longer utilize ReportStream for COVID-19 result reporting due to the end of the public health emergency. 

Please let me know if you are having any issues with ReportStream or if there is a more appropriate contact for this inquiry.

Thanks,

James"

**Comment by oslynn** [comment]
Never get any response from Cue Health.  Therefore, I am going to close this ticket for now.
