### ISSUE TITLE
Test CDC-ELIMS messages: Part 2

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#10204]
### User Story
As CDC ELIMS Rhapsody, I want to be able to send a message through ReportStream that is lossless so that a STLT can receive a CLIA compliant message.

### Description/Use Case
We want to run sample messages sent by the CDC ELIMS team through RS and validate that no data is lost once the message undergoes the translation to internal FHIR and back to HL7v2. If data is lost, we want to update the HL7->FHIR or FHIR->HL7 mappings to fix the issue.

### Risks/Impacts/Considerations
- Some differences between the input HL7v2 and output HL7v2 messages may be okay. We need to meet with the CDC ELIMS team to approve any discrepancies between the two messages. 

### Dev Notes
If fixes are needed, we will update the HL7->FHIR or FHIR->HL7 mappings to address the issues. We may also create a sender transform if needed.

For this story, the following messages will need to be tested and verified:

- [52_04204582_5128_Test.HL7](https://cdc.sharepoint.com/:u:/r/teams/ReportStream/Shared%20Documents/ELIMS-ELR/ELIMS%20artifacts/52_04204582_5128_Test.HL7?csf=1&web=1&e=19Ge9a)
- [52_24095_04204575_5120.HL7](https://cdc.sharepoint.com/:u:/r/teams/ReportStream/Shared%20Documents/ELIMS-ELR/ELIMS%20artifacts/52_24095_04204575_5120.HL7?csf=1&web=1&e=LfQ0ao)

Each HL7v2 message that is being tested should have its own notes document. See the following document for example on how it should be formatted and where it should live: 
- [40_Message_RS_processing_notes.xlsx](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/ELIMS-ELR/40_Message_RS_processing_notes.xlsx?d=w0e69763787ea46ffa7187cee9417b41d&csf=1&web=1&e=oPWYkc)

### Acceptance Criteria
- [ ] The aforementioned HL7v2 messages were run through the universal pipeline and CDC ELIMS team confirmed the output message is good

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10204?planning-poker) with Zenhub @arnejduranovic @jimmyfagan @thetaurean @luis-pabon-tf @JFU-NAVA-PBC @JessicaWNava

**Comment by mkalish** [comment]
@arnejduranovic 
Is this blocked on #10027?

cc/ @jimmyfagan

**Comment by jimmyfagan** [comment]
I wouldn't say blocked necessarily, but there's a lot of overlap. At a minimum I'd say any work here should start with [this branch](https://github.com/CDCgov/prime-reportstream/tree/jimmy/10027-sender-transforms-elims), which is currently under review [here](https://github.com/CDCgov/prime-reportstream/pull/10114#issuecomment-1633522052).

**Comment by jimmyfagan** [comment]
Jotting down some notes based on my attempts today:

When it is parsed with v2.5.1, a 5-character MSH-2 causes failure; there is a check in `PipeParser.java` that doesn't seem to be overridable unless the message version is greater than or equal to v2.7. When a v2 message is parsed with v2.7, it allows a 5-character MSH-2, but a lot of the rest of the conversion to FHIR fails, and the resulting Bundle is unusable. I'm a bit stumped at the moment, but one of the options that comes to mind is to contribute to that library to allow that error to be ignored or otherwise intercepted rather than throwing a breaking exception for that case. We have other hacks in the code to prevent the errors, so it seems that 2.5.1 senders including an extra character in MSH-2 is not uncommon.
