### ISSUE TITLE
DC - List of Labs with Total Test result counts

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#10739]
## **Problem Statement**
On the bi-weekly DC call - they stated that the lab data we previously sent them didn't include total counts.  They also didn't see the value added by receiving test results from small labs.

## **What you need to know**

[https://app.zenhub.com/files/304423150/5b733dfc-09bf-4b88-b439-588cd7b17158/download]

Please generate a new list for the State of DC that includes the lab name, total counts for the past year. Where the ordering provider is DC and resident is DC. 

## **Acceptance Criteria**
-List includes the lab name and city.
-Residents city and state
-Total test counts for the past two years

## **To Do**
A quick note to the assignee of the ticket.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by adegolier** [comment]
[query_result_2023-08-02T23_32_11.057001Z.csv](https://github.com/CDCgov/prime-reportstream/files/12245463/query_result_2023-08-02T23_32_11.057001Z.csv)


As requested, assuming where "resident" is stated, "patient" is meant. There are very few tests where both the ordering facility and patient state are DC. I filled in Washington for all patient cities since it was stated that the patient must reside in DC and Washington is the only city in DC. I will be uploading another version shortly that includes patient county and state instead since that one will be using either the ordering facility or the patient state are DC and we do not record patient cities.

**Comment by adegolier** [comment]
This is the query with the OR and using patient county instead of city

`SELECT testing_lab_name, testing_lab_city, patient_county, patient_state, 
sum(case when "public"."covid_result_metadata"."specimen_collection_date_time" >= DATE_TRUNC('month', (NOW() + INTERVAL '-12 month'))
   AND ("public"."covid_result_metadata"."specimen_collection_date_time" < DATE_TRUNC('month', NOW())) then 1 else 0 end) count_from_past_year, 
sum(case when "public"."covid_result_metadata"."specimen_collection_date_time" >= DATE_TRUNC('month', (NOW() + INTERVAL '-24 month'))
   AND ("public"."covid_result_metadata"."specimen_collection_date_time" < DATE_TRUNC('month', NOW())) then 1 else 0 end) count_from_past_two_years
FROM "public"."covid_result_metadata"
WHERE "public"."covid_result_metadata"."patient_state" = 'DC' or "public"."covid_result_metadata"."ordering_provider_state" = 'DC'
group by testing_lab_name, testing_lab_city, patient_county,patient_state
order by testing_lab_name asc`

And the results:
[query_result_2023-08-02T23_44_46.205101Z.csv](https://github.com/CDCgov/prime-reportstream/files/12245504/query_result_2023-08-02T23_44_46.205101Z.csv)

**Comment by adegolier** [comment]
That.... looks like the same file I provided so I'm not sure what you want me to review. And yes, that is the count for the past two years because in one place you said you wanted the past year and in another you said the past two, so I put both.

**Comment by sliu1000** [comment]
@adegolier I just added the total at the bottom and cleaned it up a little.
