### ISSUE TITLE
Create a tool to diff two HL7 messages

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#10795]
### User Story
As a report stream user/developer, I would like to identify the differences between an HL7 message entering and then leaving the pipeline

### Description/Use Case
As part of the ELIMS pilot, there were multiple tasks to diff HL7 messages by hand which can be error prone and time intensive, so this tool would replace the manual labor of comparing segment by segment

### Dev Notes
This [branch](https://github.com/CDCgov/prime-reportstream/tree/kalish/platform/hl7-diff-prototype) is a good starting point with a partially working solution

- Integration tests seem to do some type of diff, should investigate to see if we can reuse at some level

### Acceptance Criteria
- [ ] A tool exists to diff two HL7 messages
- [ ] That tool is integrated into the `fhirdata` CLI

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/10795?planning-poker) with Zenhub @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @luis-pabon-tf @mkalish @thetaurean @arnejduranovic

**Comment by MauriceReeves-usds** [comment]
@avnieldravid @mkalish is the intention of this tool be used manually on the command line and you pass in two files paths and get out a diff? Or is the is the intention to create an API endpoint that takes a message ID and then compares the message through its different points in the workflow and outputs a diff report at the end because I can read this case either way and those feel like very different sizes of effort. The CLI is simpler and smaller and a good first step for automation but will still require a human in the loop. The API way can be invoked by partners and integration engines but also risks outputting PII/PHI and depends on being run while the files still exist on the blob store. ALSO, the performance could really degrade on that if we're not careful.

cc: @bishoyayoub @mxk0

**Comment by arnejduranovic** [comment]
@MauriceReeves-usds the intention for this ticket is just a CLI tool to use to speed up engineering and onboarding processes

**Comment by avnieldravid** [comment]
@MauriceReeves-usds Wanted to tag you on this ticket to re-confirm that we did not build the "online" (API Endpoints) version of the diff tool.  Just the CLI version to be used to speed up testing and onboarding.  This ticket was discussed in our PO Sync this week.
