### ISSUE TITLE
Clean up githook precommit hook script

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#11009]
Add pipefail
remove linting checks (this is done in Github)
other cleanup as time permits.

I think this script is installed by running .environment/pre-commit-hook.sh, it's in the "Getting started" doc.

**Comment by jeremy-page** [comment]
Bumping SP since @dkrylovsb will be learning this from scratch

**Comment by dkrylovsb** [comment]
@jeremy-page I am adding `set -o pipefail` to scripts where pipelines are used; will PR shortly. I'm somewhat reluctant to remove the linting checks, because that would allow un-linted code to get committed. Even though GHA will catch that at a later point, I think the goal is to prevent unlinted code to even make its way into the repo in the first place.

Overall, the pre-commit bash scripts seem to be well-written, I don't have any suggestions for cleanup/improvements at the moment.
