### ISSUE TITLE
Content update: How to download your data

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#11120]
## User story

As a ReportStream prospective/current user, I want the website content to be up-to-date, accurate and timely so I can  trust the information to inform my decisions in my relationship with ReportStream. 

## Background & context

After completing basic outlines for key pages and IDing the new site structure, we need to create the actual content that will go in the wireframes. This ticket captures the work of updating the content for the **How to download your data**.

## Open questions
- Is this page still necessary? 

## Working links
-   Current RS page: [Manual data download guide](https://reportstream.cdc.gov/resources/data-download-guide)
- Content draft: TK

## Acceptance criteria
-   [ ] Drafted reviewed and approved content owner and/or SME
-   [ ] Capture questions that come up during the content and design work in the [Website redesign research plan](https://docs.google.com/document/d/1Hmxu_mTGvSJ0RnfS_SXoY84dBeAyUuy7KsCL08N0azg/edit#heading=h.sqsn2oxgx0ou)

**Comment by audreykwr** [comment]
@chris-kuryak @Andrey-Glazkv @jillian-hammer going to close this based on the convo at all teams. The plan is to incorporate information about downloading into onboarding receiver content and the current place it is already mentioned. Rather than updating this page. This page will be archived when the content is updated elsewhere.

**Comment by chris-kuryak** [comment]
Thanks for recording this disposition in the ticket and for the awareness!
