### ISSUE TITLE
Enable truncation for HL7 message types supported by the UP

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-reportstream#11288]
### User Story
As ReportStream, I want to truncate fields for HL7 messages types supported by the UP, so that receivers can get data in their expected format.

### Description/Use Case
Right now truncation logic only supports truncating ORU_R01 messages. We need to add support for OML_O21 and ADT_A01.

### Dev Notes
The function `formSegSpec` contains all the segment paths for an ORU_R01 message. This function needs to be redesigned so it works for the other HL7 message types.

### Acceptance Criteria
- [ ] Truncation works for  OML_O21 and ADT_A01 message types

**Comment by jalbinson** [comment]
After discussing approaches with @victor-chaparro, we think its a cleaner solution to use the full path we get from the UP rather than to update this existing function which was only designed for `ORU_R01`. This will require some refactoring of the truncation logic to be able to optionally accept a full path rather than just the segment.
