### ISSUE TITLE
Remove UP default filters associated with topics

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#11441]
### User Story
As a report stream developer, I would not like to have the topic enum associated with UP default filters so that the implementation can be cleaner when products requirements are completed

### Description/Use Case
UP default filters are currently associated with topics which muddies the water on what topics are doing and provide limited value since they are just pass throughs currently

### Risks/Impacts/Considerations
The impact should be low as CA is the only receiver in PROD and they have there own custom filters

We should also consider STAGING, for orgs like Trusted Intermediary.

### Acceptance Criteria
- [X] Remove the UP default quality and processing mode filter
- [X] Update the handling of the quality filter to set the default response to `true`
- [X] Update the ETOR receivers to match the current default
- [ ] ~~Rename `processingModeFilter` to `processingIdFilter`~~

Per SU 17th discussion, not to do rename in this PR.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11441?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @JessicaWNava @JFU-NAVA-PBC @jimmyfagan @thetaurean

**Comment by brick-green** [comment]
FYI: In addition to CA, New York is also in production for UP

**Comment by JFU-NAVA-PBC** [comment]
Migration plan:

1. Download the settings from staging:
2. Run: ./prime multiple-settings get > organizations.satging.yml
3. Patch the settings adding filters to the applicable receivers make sure the routing behavior stay the same after the topic wide filter defaults removal got deployed to staging
4. Find a way to test it out (download settings -> modify the receivers filters configuration -> upload back to the env), pick TEST? DEMO? or LOCALLY
5. Perform the upload of the modified settings with flag preventing overriding new changes on the env:
6. Run: ./prime multiple-settings set -i --check-last-modified organizations.patched.satging.yml

**Comment by JFU-NAVA-PBC** [comment]
@arnejduranovic appreciated if you could share info on how such migration is done historically.

**Comment by arnejduranovic** [comment]
Historically speaking, I don't think we've had to make such a large change before. Everywhere a receiver has an empty filter that used to have a default, you will have to manually enter the default. I recommend having someone review the changes you want to make before applying them to staging/production. So, run get settings and save that so you can diff your updated settings against it for the review.

**Comment by JFU-NAVA-PBC** [comment]
After research and compare, here is the migration approach seems reliable and less likely to cause interference to other users on the setting on staging, prod:

Using SQL to identify the receivers whose filters need to be patched:

QualityFilter Patch, Applicable to FULL-ELR, ETOR-TI, ELR-ELIMS:
=================================================
FULL-ELR receivers:

Query receivers need qualityFilter patch (qualityFilter = [])

This is the result on PROD MetaDB:

<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9UQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4ba3fdff21ea08fb0cedae724d561fdcc21d5a3/image.png" alt="image.png" />

Update the receivers qualityFilter with below SQL:

`SELECT jsonb_set(values, ‘{qualityFilter}’, ‘[“%messageId.exists()",
 "%patient.name.family.exists()",
 "%patient.name.given.count() > 0",
 "%patient.birthDate.exists()",
 "%specimen.type.exists()",
 "(%patient.address.line.exists() or %patient.address.postalCode.exists() or %patient.telecom.exists())",
 "((%specimen.collection.collectedPeriod.exists() or %specimen.collection.collected.exists()) or %serviceRequest.occurrence.exists() or %observation.effective.exists())",
]’::json)
FROM setting
WHERE values->>'topic'='full-elr' and values->>'qualityFilter'='[]'
` 
ETOR-TI receivers:

Query receivers need qualityFilter patch (qualityFilter = [])

SELECT setting_id, setting.name, values->'qualityFilter' as "qualityFilter"
FROM setting
WHERE values->>'topic'='full-elr' and values->>'qualityFilter'='[]'

On PROD, this returns empty result.

To update filters:

SELECT jsonb_set(values, ‘{qualityFilter}’, ‘["%messageId.exists()"]’::json)
FROM setting
WHERE values->>'topic'='etor-ti' and values->>'qualityFilter'='[]'

ELR-ELIMS receivers:

Query receivers need qualityFilter patch (qualityFilter = [])

`SELECT setting_id, setting.name, values->'qualityFilter' as "qualityFilter"
FROM setting
WHERE values->>'topic'='elr-elims' and values->>'qualityFilter'='[]'
`
On PROD, this return empty result.

ProcessingModeFilter Patch, Applicable to FULL-ELR, ETOR-TI:
===============================================

Query receivers of FULL-ELR with empty processingModeFilter:

Result from PROD:

<img width="789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--171951e94f8c211ef47ce9d5c0ae6d27976ee582/image.png" alt="image.png" />

Update filter with below SQL:

`SELECT jsonb_set(values, ‘{processingModeFilter}’, ‘["%processingId.exists() and %processingId = 'P'"]’::json)
FROM setting
WHERE values->>'topic'='full-elr' and values->>'processingModeFilter'='[]'
`

**Comment by JFU-NAVA-PBC** [comment]
Status of migration:

Per the SQL scripts approach, there is versioning of the setting which complicated the approach of query and update DB table records.

Just a FYI, tested migration scripts on setting on dev local, and noticed that the records in the setting table is versioned, and go with SQL updates could be complicated by the versions of receivers vs their organizations records, tried the approach of only download organization - but "prime organization get" only fetch the organization section - there is no receivers, so probably have to go with:

either download whole setting -> make changes -> upload back with that protection flag or if the number of places to change is small, login into RS front end admin, and make changes there.

@arnejduranovic @mkalish

**Comment by JFU-NAVA-PBC** [comment]
updates about processingModeFilter renaming:

Huddled with Michael and will proceed with name change, for migrate - will do it in 2 phase: before deployment, add processingIdFilter (dup the existing processingModeFilter filter values, still keep processingModeFilter for receivers who have it, after deploy, let the deployment bake a while and pick at time to deprecate the processingModeFilter across the setting)

**Comment by JFU-NAVA-PBC** [comment]
FYI, checked PR, AC: Update the handling of the quality filter to set the default response to true
has been taken care of.

**Comment by JFU-NAVA-PBC** [comment]
Update:

Made changes required by AC, for PROD, STAGING settings migration, have a good approach to perform the migration.

@arnejduranovic @Andrey-Glazkv

**Comment by JFU-NAVA-PBC** [comment]
A copy of Slack thread on migration of settings on staging / prod:
===========================
Qian (Jim) Fu [HDH0]
  3 days ago
@kalish (fmj0)
 I noticed settings on prod and staging "procesingModeFilter" are all replaced with "processingIdFilter" whatever the receivers' topics are, just wanted to confirm, it is Ok to proceed to put the corresponding default filters ("%processingId.exists() and %processingId = 'P'") for full-elr/etor-ti , thanks.
15 replies


Arnej Duranović [UMN2]
  3 days ago
I'm not sure I understand, were full-elr/etor-ti receivers using that filter before or not?


Arnej Duranović [UMN2]
  3 days ago
Also when changing staging/prod filter, we should make sure to check with engagement team if we are not confident in the changes we are making, they are the owners of those configs


Qian (Jim) Fu [HDH0]
  3 days ago
I am checking the diff between Dec29 vs Jan04..., I agree with collab with engagement team on changes, will compile a change list for them to review.


Arnej Duranović [UMN2]
  3 days ago
I'm pretty sure that filter was getting used as the default for full-elr, etor I'm not 100% certain but I think they also were including those values in their messages so the defaults should work for them as well


Qian (Jim) Fu [HDH0]
  3 days ago
processingModeFilter is used in PROD, at least I found this one (and there might be others):
- name: "full-elr"
    organizationName: "ny-phd"
    topic: "full-elr"
    customerStatus: "testing"
    translation: !<HL7>
      schemaName: "metadata/hl7_mapping/receivers/STLTs/NY/NY-receiver-transform"
      useTestProcessingMode: false
      useBatchHeaders: true
      receivingApplicationName: "ECLRS"
      receivingApplicationOID: null
      receivingFacilityName: "NYSDOH"
      receivingFacilityOID: null
      messageProfileId: null
      replaceValue: {}
      replaceValueAwithB:
        MSH-4-1:
        - '*': "CDC PRIME REPORTSTREAM"
        MSH-4-2:
        - '*': "10DRPTSTRM"
      reportingFacilityName: null
      reportingFacilityId: null
      reportingFacilityIdType: null
      suppressQstForAoe: false
      suppressHl7Fields: null
      suppressAoe: false
      defaultAoeToUnknown: false
      replaceUnicodeWithAscii: false
      useBlankInsteadOfUnknown: null
      truncateHDNamespaceIds: false
      truncateHl7Fields: null
      usePid14ForPatientEmail: false
      convertTimestampToDateTime: null
      cliaForOutOfStateTesting: null
      cliaForSender: {}
      phoneNumberFormatting: "STANDARD"
      suppressNonNPI: false
      processingModeCode: null
      replaceDiiWithOid: null
      applyOTCDefault: false
      useOrderingFacilityName: "STANDARD"
      valueSetOverrides: {}
      nameFormat: "STANDARD"
      receivingOrganization: null
      convertPositiveDateTimeOffsetToNegative: false
      stripInvalidCharsRegex: null
      convertDateTimesToReceiverLocalTime: false
      useHighPrecisionHeaderDateTimeFormat: false
      type: "HL7"
      truncationConfig:
        truncateHDNamespaceIds: false
        truncateHl7Fields: []
        customLengthHl7Fields: {}
    jurisdictionalFilter:
    - "(%performerState.exists() and %performerState = 'NY') or (%patientState.exists()\
      \ and %patientState = 'NY')"
    qualityFilter: []
    routingFilter: []
    processingModeFilter:
    - "%processingId = 'P'"


Qian (Jim) Fu [HDH0]
  3 days ago
and I searched settings prod snap shot Jan 04, all processingIdFilter is [], so some processingModeFilter with value are replaced with processingIdFilter: []


Qian (Jim) Fu [HDH0]
  3 days ago
Sure, we won't proceed until people feel confident about the changes...


Qian (Jim) Fu [HDH0]
  3 days ago
it is nice and quiet on prod, it might be that the incumbent code is still having the topic default, or the routes affected have not been hit yet...


Arnej Duranović [UMN2]
  3 days ago
so some processingModeFilter with value are replaced with processingIdFilter: []
This should not be the case, right?


Arnej Duranović [UMN2]
  3 days ago
If a receiver had:
processingModeFilter:
    - "%processingId = 'P'"
Then it should be:
processingIdFilter:
    - "%processingId = 'P'"
and NOT:
processingIdFilter: []


Arnej Duranović [UMN2]
  3 days ago
The new setting should be:
processingIdFilter: []
only when when the old setting was exactly:
processingModeFilter: []
(edited)


Arnej Duranović [UMN2]
  3 days ago
Because all we are doing with this filter is changing the name of it, the resulting config shouldn't change in terms of functionality for anyone.


Qian (Jim) Fu [HDH0]
  3 days ago
that's what I think


Qian (Jim) Fu [HDH0]
  3 days ago
probably we should get a clear picture on these changes before further migrate....


Qian (Jim) Fu [HDH0]
  2 hours ago
@arnej
 have a better way to migrate - leverage the per org topic filters, it seems there are issues on the current deploy, so might hold off until it is cleared up there

**Comment by JFU-NAVA-PBC** [comment]
@arnejduranovic @mkalish 

as discussion on renaming of "processingModeFilter" to "processiongIdFilter" in slack channel, I suggest that we don't do the renaming based on below reasons:

"
also the renaming of processingModeFilter to processingIdFilter seems to be a bad idea considering it's a breaking change impact both backend and on boarding and external users, the benefit is only the accuracy of naming - which is diminished since people are already used to call it processingModeFilter

Qian (Jim) Fu [HDH0]
  2 minutes ago
I suggest remove the rename request from the AC.

Qian (Jim) Fu [HDH0]
  1 minute ago
as can be seem, webUX has to be changed to pickup the new name too..."

**Comment by JFU-NAVA-PBC** [comment]
FYI, going to revert the rename processingModeFilter to processingIdFilter from the code base, before migrate the settings on staging, prod.

@arnejduranovic @mkalish

**Comment by JFU-NAVA-PBC** [comment]
Finally settled on a manual migrate approach after Slack discussion (attached):

For each receiver with topics - full-elr, eetor-ti, elr-elims:
Check qualityFilter, processingModeFilter:
If not present (null or empty), put below default filter respectively:

`{
      "topic": "etor-ti",
      "qualityFilter": [
        "%messageId.exists()"
      ],
      "processingModeFilter": [
        "%processingId.exists() and %processingId = 'P'"
      ],
    },
    {
      "topic": "elr-elims",
      "qualityFilter": [
        "true"
      ],
    },
    {
      "topic": "full-elr",
      "qualityFilter": [
        "%messageId.exists()",
        "%patient.birthDate.exists()",
        "%patient.name.family.exists()",
        "%patient.name.given.count() > 0",
        "%specimen.type.exists()",
        "(%patient.address.line.exists() or %patient.address.postalCode.exists() or %patient.telecom.exists())",
        "((%specimen.collection.collectedPeriod.exists() or %specimen.collection.collected.exists()) or %serviceRequest.occurrence.exists() or %observation.effective.exists())"
      ],
      "processingModeFilter": [
        "%processingId.exists() and %processingId = 'P'"
      ],
    }`

**Comment by JFU-NAVA-PBC** [comment]
Attached Slack discussion on the manual migrate approach, note, for now, this is still a managible process giben that there are 146 organizations in prod setting, and 165 organizations in staging setting.

Here are slack thread for migrate approach discussion:

> Jimmy Fagan
  19 hours ago
I thought the whole point of removing default filters is that we don’t have any organizations with accidental filters that they don’t intend. So I think the approach should be that we do this migration (I would say by manually adding the current defaults to any receivers that don’t already have filters at the receiver/organization level), but that the migration doesn’t have to be future-proof. The approach in the future would be that receivers define these filters if they want to be using them, and if they aren’t set then to allow everything. The exception would be the jurisdictional filter which if they aren’t set would be to disallow everything. I think if we want to talk about keeping the default filters in the code, that should be a discussion that happens outside of slack.





Qian (Jim) Fu [HDH0]
  19 hours ago
thanks for the input


Jimmy Fagan
  19 hours ago
(There might be good reason to keep something like a default quality filter if that will help prevent exceptions, just should be something that should be discussed as a 17th or in a separate meeting I think)
:+1:
1



Qian (Jim) Fu [HDH0]
  19 hours ago
yea, just weighing benefits and risks...


Michael Kalish (he/him)
  19 hours ago
Yea agree overall that the org stuff is maybe out of scope.  We really just want to remove linking the topic to a hardcoded filter


Qian (Jim) Fu [HDH0]
  19 hours ago
:+1:
