### ISSUE TITLE
Development of RADx MARS API

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#11854]
## Problem statement

The RADx MARs team is developing a RADx MARs API to simplify the process for developers to construct a MARS HL7v2 message and send that message to ReportStream or APHL.

## What you need to know

Their API developer is looking for access to the ReportStream API for the UP. This sender in particular would not ever go to production, we would onboard each Radx Mars sender individually and they would pass their credentials to the library they are building. This onboarding effort is just so they can test his wrapper for ReportStream and pretend to be a sender in staging.

## Acceptance criteria

- [x] Onboard RADx MARs to RS staging environment

## To do

- [x] Connect with Glenn/RADx MARs to discuss onboarding timeline and process
- [x] Onboard RADx MARs to staging environment of RS
- [x] Confirm with RADx MARs individual that they can successfully send a message to staging environment

**Comment by GilmoreA6** [comment]
Hi Andy et. al,

The org has been created and I've uploaded your public key on our end so you are good to try and send to the endpoint whenever ready. Your kid is meadowsdesign.default and your client name is meadowsdesign.

Example JWT:
{
    "header": {
        "kid": "meadowsdesign.default",
        "typ": "JWT",
        "alg": "ES384"
    },
    "payload": {
        "iss": "meadowsdesign.default",
        "sub": "meadowsdesign.default",
        "aud": "staging.prime.cdc.gov",
        "exp": 1660737164,
        "jti": "4b713fcd-2514-4207-b310-620b95b749c5"
    }
}
Example CURL command to get bearer token:
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "scope=meadowsdesign.*.report&grant_type=client_credentials
&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=<token-signing-secret>" "https://staging.prime.cdc.gov/api/token"
Example curl command to POST report:

curl -X POST -H "authorization:bearer <long-bearer-token>" -H "client: meadowsdesign"  -H "content-type:application/hl7-v2" --data-binary "@./meadowsdesign-nonPII-data.hl7" "https://staging.prime.cdc.gov/api/waters


Please remember to only send fake/deidentified data to the staging environment. No PII/PHI can be sent to the staging environment. Let me know if you have any issues with getting the bearer token or sending a report. Because the UP is async we will only return a  JSON object telling you whether the submission was accepted or not:

example:
{
   "submissionId":1604,
   "timestamp":"2022-02-10T13:50:19.162694Z",
   "sender":"simple_report.default",
   "httpStatus":201,
   "id":"3597ad7d-b92c-4bc0-a8fc-d909ed87bc90",
   "reportItemCount":2,
   "destinationCount":0,
   "destinations": [],
   "errors": [],
   "warnings": [],
   "topic":"covid-19",
   "warningCount":0,
   "errorCount":0
}
In order to tell what happened to a report post submission you will need to query our history API using either the submissionID or id returned in the JSON response to your POST. The history API can by queried by sending a GET request to the history endpoint.

Example:
curl -X GET -H "authorization:bearer <long-bearer-token>" -H "client: meadowsdesign"  "https://staging.prime.cdc.gov/api/waters/report/<submissionID> or <id>/history
Thanks,

James

**Comment by chris-kuryak** [comment]
Onboarded Friday. Waiting on them to try and test sending.

**Comment by GilmoreA6** [comment]
email from Andy Meadows on 10/23:

James:

Going to staging.reportstream.cdc.gov
CDC Prime ReportStream STAGING
ReportStream Dashboard Application
staging.reportstream.cdc.gov
, I can login and get to my submission data (haven't submitted anything yet).  Should I see anything else at this point?  For instance, I can't see the public key but it states it's configured so do I assume it's correct?

Thanks.
Andy M.

**Comment by GilmoreA6** [comment]
Response to Andy on 10/24:

Hi Andy,

That is correct. Since I uploaded your public key for you that's really all there is to do (we don't yet have the ability for users to fully manage keys through the site, that is upcoming). You'll be able to see submissions once you submit reports to the endpoint. Most of the website features are focused on receivers of data and not senders so there isn't a lot to do/see right now.

As far as sending data goes, is there a particular test plan or acceptance criteria you are working off of for your testing? Happy to support your testing in any way I can.

Thanks,

James

James Gilmore
Senior HL7 Data Analyst
AgileSix
Public Health Data Transmission Branch ​
Detect and Monitor Division​
Office of Public Health Data, Surveillance, and Technology​
Centers for Disease Control and Prevention

**Comment by chris-kuryak** [comment]
@GilmoreA6 I added an acceptance criteria to confirm that RADx MARs person has successfully sent a message to staging. If that's true, go ahead and check it off.

**Comment by GilmoreA6** [comment]
Received report Id: b9a826f0-04aa-42d3-b6a0-829051b007bb to staging environment on 11/12/23.
