### ISSUE TITLE
Re-surrect-PR: Refactor code to remove old dependencies

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#11928]
### User Story
As a ReportStream engineer, I want to keep our dependencies current so that use of unmaintained code is minimized.
Note, this round of work is to re-surrect the PR which was reverted from last de[ployment.

### Description/Use Case
A number of dependencies (see Dev Notes below for a list) appear to be no longer maintained or public. We should remove these dependencies and refactor any code that uses them to use alternatives.

### Dev Notes
Mo supplied these notes:

- `com.github.kittinunf.fuel:fuel-jackson:2.3.1` - we use (used?) fuel to invoke web services and use Jackson to serialize data to and from JSON/Yaml. This library helped bridge those two. We could replace fuel with Ktor and yoink this one
- `com.github.KennethWussmann:mock-fuel:1.3.0` - ditto above. We needed this to mock our Fuel calls. I don't think this is maintained anymore 
- `com.jcraft:jsch:0.1.55` - older SSH/SFTP library that's also no longer maintained. This one can probably get pulled entirely (and should be) it's almost certainly not being used actively. Prune it.

Additionally, `mock-fuel` appears to be the only remaining use of `jitpack`, which should also be removed (see #11938).

### Acceptance Criteria
- [x] Dependency `com.github.kittinunf.fuel:fuel-jackson:2.3.1` is removed or an explanation for its continued use is provided.
- [x] Dependency `com.github.KennethWussmann:mock-fuel:1.3.0` is removed or an explanation for its continued use is provided.
- [x] Dependency `com.jcraft:jsch:0.1.55` is removed or an explanation for its continued use is provided.
- [x] Dependency `jitpack.io` is removed or an explanation for its continued use is provided.

**Comment by snesm** [comment]
com.github.KennethWussmann:mock-fuel:1.3.0 appears to only be available from jitpack.io (cached), and not as source.

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11928?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @jimmyfagan @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11928?planning-poker) with Zenhub @JessicaWNava

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/11928?planning-poker) with Zenhub @JFU-NAVA-PBC

**Comment by JFU-NAVA-PBC** [comment]
@Andrey-Glazkv @arnejduranovic 

the Fuel http client is used across numerous commands and their corresponding utilities & tests, have done with OktaCommand using ktor http client, and refactoring to other commands / tests are in progress.

there are some chores asked to do for biding from client capture team, so it chip off some head down time.

this one is demoable in QA review state, and:

my estimate: 

this one will carrie with 1 point

thanks

**Comment by JFU-NAVA-PBC** [comment]
even there seems to be a recent commit to the repo with label 3.0 alpha:
`3.0.0-alpha01 Latest
@kittinunf kittinunf released this Apr 2
· 14 commits to main since this release
 3.0.0-alpha01
 93a6216 
Description
This is an alpha01 version for 3.0.0.

Fuel 3.0.0 is a new start-from-scratch implementation to support multiplatform. This is an alpha release and early version for Fuel, any feedbacks are welcome.

Thanks @iNoles for his fantastic work `

There is little sign of activities, and considering numerous prime commands depend on Fuel http to call the end points, it is more sustainable to move away from Fuel to something more sustainable / with large audience, e.g. ktor http client.

**Comment by arnejduranovic** [comment]
https://github.com/CDCgov/prime-reportstream/pull/11938 was recently merged, let's make sure to remove as part of this PR once refactor is complete.

**Comment by JFU-NAVA-PBC** [comment]
@arnejduranovic thanks for the heads up, will do

**Comment by JFU-NAVA-PBC** [comment]
Per request, here is a summary of trouble shoot during previous deployment:

In short, the test "server2serverauth" failed on an invalid jwt fetched from Okta staging:
==================================================================
"We finally found the root logged error for the failing staging smoke test Caused by: io.jsonwebtoken.IncorrectClaimException: Expected iss claim to be: https://reportstream.oktapreview.com/oauth2/default, but was: null."

the iss is missing.
------------------
Note, the token creation and token fetch calls used in the server2severauth tests ARE NOT using Fuel http, instead the azure http client is used (kotlin.azure.HttpUtilities.kt), hence the token operations between Okta API are not affected by the Fuel removal changes.

Why this did not happen on local tests?
=============================

because the tested area are STAGING bound, see code snippet:
AuthTests.kt : 945-949:

`            if (environment.envName == Environment.STAGING.envName) {
                // PrimeAdmin tests cannot be run locally as they need Okta credentials, even in Server2Server
                passed = passed and server2ServerSettingsAuthTests(environment, token1, org1, org2)
                passed = passed and server2ServerSettingsAuthTests(environment, token2, org2, org1)
            }`

Possible Location to look into: Staging Okta where the JWT is issued to see why the JWT issue is missing "iss".

**Comment by JFU-NAVA-PBC** [comment]
Ok, going back to this PR which was reverted a while back from deployment, due to smoke test "server2serverauth" failure.

Last time, at the deployment, worked with Jimmy and Angela since I could not run smoke tests against STAGING, I think I need VPN in ordfer to do that.

Now, I tried to run the smoke test against STAGING, still hitting the same DB access error.

Steps:

1. prime login to staging
2. export DB credentials (grabbed from pdhstaging-functionapps)
3. run: 
 
Here are the std out:

./prime test --env staging --key "faZtspbi6uhPbDkvSxoN7keEPssX4NYERdPQ4hXaOZyyAaZKIaLSmw=="
Running the following tests, POSTing to https://staging.prime.cdc.gov:
ping                Smoke Test                  CheckConnections: Is the reports endpoint alive and listening?
merge               Smoke Test                  Submit multiple files, wait, confirm via db that merge occurred
server2serverauth   Smoke Test                  Use server2server (two-legged) auth against various waters endpoints
qualityfilter       Smoke Test                  Test the QualityFilter feature
hl7null             Smoke Test                  The NULL transport does db work, but no transport.  Uses HL7 format
toomanycols         Smoke Test                  Submit a file with more than 2000 columns, which should error
badcsv              Smoke Test                  Submit badly formatted csv files - should get errors
strac               Smoke Test                  Submit data in strac schema, send to all formats and variety of schemas
waters              Smoke Test                  Submit data in waters schema, send to BLOBSTORE only
hl7ingest           Smoke Test                  Create HL7 Fake data, submit, wait, confirm sent via database lineage data
otcproctored        Smoke Test                  Verify that otc/proctored flags are working as expected on api response
jti                 Smoke Test                  Test the JTI Cache
sender-settings     Smoke Test                  Test that we can extract values from Sender settings and put into our data 
history             Smoke Test                  Test the History/Lineage API
livdApi             Smoke Test                  Test the LIVD API
end2end             Smoke Test                  Create Fake data, submit, wait, confirm sent via database lineage data
end2end_up          Smoke Test                  Create Fake data, submit, wait, confirm sent via database lineage data for UP
Running test ping...
********************************
Output for test ping...
Starting ping Test: run CheckConnections of https://staging.prime.cdc.gov
Response to POST: 200
Response message: {
  "id" : null,
  "submissionId" : 3763994,
  "overallStatus" : "Received",
  "timestamp" : "2024-02-16T21:47:05.645Z",
  "plannedCompletionAt" : null,
  "actualCompletionAt" : null,
  "sender" : "",
  "reportItemCount" : null,
  "errorCount" : 0,
  "warningCount" : 0,
  "httpStatus" : 200,
  "destinations" : [ ],
  "actionName" : "receive",
  "externalName" : "",
  "reportId" : null,
  "topic" : null,
  "errors" : [ ],
  "warnings" : [ ],
  "destinationCount" : 0
}
Test passed: Ping/CheckConnections
Running test merge...
********************************
Output for test merge...
Starting merge test:  Merge 5 reports, each of which sends to CSV,HL7_BATCH
Exception: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException, Failed to initialize pool: The connection attempt failed.: com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
gov.cdc.prime.router.azure.DatabaseAccess$Companion.getDataSource(DatabaseAccess.kt:1449)
gov.cdc.prime.router.azure.DatabaseAccess$Companion$hikariDataSource$2.invoke(DatabaseAccess.kt:1469)
gov.cdc.prime.router.azure.DatabaseAccess$Companion$hikariDataSource$2.invoke(DatabaseAccess.kt:1466)
kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
gov.cdc.prime.router.azure.DatabaseAccess$Companion.getHikariDataSource(DatabaseAccess.kt:1466)
gov.cdc.prime.router.azure.DatabaseAccess$Companion.getCommonDataSource(DatabaseAccess.kt:1477)
gov.cdc.prime.router.azure.DatabaseAccess.<init>(DatabaseAccess.kt:91)
gov.cdc.prime.router.azure.DatabaseLookupTableAccess.<init>(DatabaseLookupTableAccess.kt:18)
gov.cdc.prime.router.Metadata.<init>(Metadata.kt:131)
gov.cdc.prime.router.Metadata.<init>(Metadata.kt:127)
gov.cdc.prime.router.Metadata$Companion$singletonInstance$2.invoke(Metadata.kt:492)
gov.cdc.prime.router.Metadata$Companion$singletonInstance$2.invoke(Metadata.kt:491)
kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
gov.cdc.prime.router.Metadata$Companion.getSingletonInstance(Metadata.kt:491)
gov.cdc.prime.router.Metadata$Companion.getInstance(Metadata.kt:500)
gov.cdc.prime.router.cli.tests.CoolTest$Companion$metadata$2.invoke(TestReportStream.kt:851)
gov.cdc.prime.router.cli.tests.CoolTest$Companion$metadata$2.invoke(TestReportStream.kt:851)
kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
gov.cdc.prime.router.cli.tests.CoolTest$Companion.getMetadata(TestReportStream.kt:851)
gov.cdc.prime.router.cli.tests.Merge.run(BasicTests.kt:469)
gov.cdc.prime.router.cli.tests.TestReportStream.runTests$runTest(TestReportStream.kt:256)
gov.cdc.prime.router.cli.tests.TestReportStream.access$runTests$runTest(TestReportStream.kt:59)
gov.cdc.prime.router.cli.tests.TestReportStream$runTests$2$1.invokeSuspend(TestReportStream.kt:280)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
gov.cdc.prime.router.cli.tests.TestReportStream.runTests(TestReportStream.kt:279)
gov.cdc.prime.router.cli.tests.TestReportStream.run(TestReportStream.kt:227)
com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:279)
com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:292)
com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:41)
com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:457)
com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:454)
com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:474)
com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:481)
gov.cdc.prime.router.cli.MainKt.main(main.kt:298)
Running test server2serverauth...
********************************
Output for test server2serverauth...
Exception: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException, Failed to initialize pool: The connection attempt failed.: com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
com.zaxxer.hikari.HikariDataSource.<init>(Hi

**Comment by JFU-NAVA-PBC** [comment]
**Exception: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException, Failed to initialize pool: The connection attempt failed.: com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)**

**Comment by JFU-NAVA-PBC** [comment]
@arnejduranovic @Andrey-Glazkv Looks like need someone with VPN to push this PR through the finish line.

I did not see any need to make any changes to the PR, the code changes of replacing Fuel HTTP client does not impact server2serverauth where the HTTP client is still using the Azure HTTP.

Please make arrangement

Thanks a lot.

--Jim

**Comment by JFU-NAVA-PBC** [comment]
cc: @arnejduranovic @Andrey-Glazkv 

per input from SU on launch smoke tests against staging (or other deployed envs), still hitting the DB connection issue, thought about go to Azure shell (command line on azure) to do the smoke test, but the same VNET restriction applies, so basically, this is what I can push from my side, would be great if other team member with VPN could pre-smoke the PR. 

```
FYI, tried smoke test staging after white listed my IP at "pdhstaging-pgsql | Connection security" (saved), however, still hit the DB connection error:
Test passed: Ping/CheckConnections
Running test merge...
********************************
Output for test merge...
Starting merge test:  Merge 5 reports, each of which sends to CSV,HL7_BATCH
Exception: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException, Failed to initialize pool: The connection attempt failed.: com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:584)
com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:571)
com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:8
........
Sounds like vpn is still needed, quote deploy instruction "Add your VPN-assigned IP address to the database access whitelist (if necessary) "
(edited)





3:48
cc: 
@kalish (fmj0)
 
@Gabriel
 thanks for the input though...


```

**Comment by Andrey-Glazkv** [comment]
@adegolier please have a look
