### ISSUE TITLE
Test CDC-ELIMS messages: Part 7 - RS Overrides

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#12115]
### User Story
As ELIMS, I would like RS not to apply its default overrides so that the output HL7v2 can match the input as much as possible.

### Description/Use Case
Presently, there are four scenarios identified in this [spreadsheet](https://cdc.sharepoint.com/:x:/r/teams/ReportStream/Shared%20Documents/ELIMS-ELR/Gap%20Analysis/HL7%20IN%20vs%20HL7%20OUT%20_%20Gap_Analysis.xlsx?d=wfaed6c19ba414f03a1486c8490228a1c&csf=1&web=1&e=YXLfAV) that relate to differences in the output message from the input. **See rows 2-5 for details**.

UPDATE: Each of the rows 2 through 5 are related to the default sender transform that had been used with the ELIMS sender on staging. There is an ELIMS specific transform that is now being used on staging which will resolve those discrepancies for ELIMS. However, there is still a question of why those changes are present in the default sender transform. This ticket should be used to investigate the current default sender transform and for anything that really shouldn't be a default, find a new home for those elements, either in a different sender transform (for example, simple report), or in a receiver transform. This should involve coordination with Victor and the engagement team.

### Risks/Impacts/Considerations
Before the changes get deployed, we should update the sender transform from staging, just to make sure there isn't any gap where we are referencing a schema that doesn't exist. As far as prod goes, it should not be affected. 

Staging organizations using default:

connectathon
meadowsdesign
ignore-etor-ti
ignore-elr-elims
Staging organizations using Elims:

CDC-ELIMS-HL7
No one is set up to use either of them in prod.

### Acceptance Criteria
- [ ] Sample test message run through pipeline and output message confirmed to equal input message. (Done after updating sender transform for ELIMS)
- [x] Default sender transform only contains transformations that are generally safe for a default case

**Comment by arnejduranovic** [comment]
Blocked. Need test messages that repro this issue from ELIMS team

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/12115?planning-poker) with Zenhub @arnejduranovic @brick-green @jack-h-wang @jalbinson @JessicaWNava @jimmyfagan @mkalish @thetaurean @JFU-NAVA-PBC

**Comment by jimmyfagan** [comment]
We haven't seen these issues because locally, we’re using an ELIMS specific sender transform that prevents those few changes, but in staging, the elims sender uses the default sender transform, which does cause those changes. So the fix there is probably two-fold: 1) update the settings in staging to reference the elims transform and 2) consider moving some of those pieces out of the default sender transform and into a SR sender transform or into receiver transforms.

**Comment by JessicaWNava** [comment]
The elims transform just negated the default transform and since none of the things in the default transform actually belong there, I renamed it to something more appropriate, deleted the elims sender transform, and updated the places that it needed to be updated in the code. Once this gets pushed out staging will need to be updated so that they no longer have a sender transform.

**Comment by jimmyfagan** [comment]
In terms of rollout strategy here, I think we should remove the sender transform from staging before the changes get deployed, just to make sure there isn't any gap where we are referencing a schema that doesn't exist. Other than that, sounds like a plan!

**Comment by JessicaWNava** [comment]
Staging organizations using default:
- connectathon
- meadowsdesign
- ignore-etor-ti
- ignore-elr-elims

Staging organizations using Elims:
- CDC-ELIMS-HL7
