### ISSUE TITLE
Kansas - Missing LOINC 

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#12212]
## Problem statement

Kansas DOH has reported missing LOINC and Message ID.

## What you need to know

We received a message yesterday that was missing a LOINC in OBX-3. The MSH.10 is 352cd2b1-bb82-46f0-9426-956830944818. Could it be resent with the LOINC please? 

Tier 1 reviewed Metabase, screenshot attached for reference shows LOIN Code in message from sender, ImageMover.

## To do

Review message for errors or confirm transmission
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2914032677e77c809dc3a4315d51152824c7d5a/ImageMover.PNG)

**Comment by LaFreda1** [comment]
@adegolier Let me know if you need more details for this ticket

**Comment by adegolier** [comment]
James sent an email to ImageMover to see if they can update the deviceId and deviceName so that they will match the LIVD table. I manually corrected and ran the file through locally, but I can't drop it myself because they require IPs to be whitelisted for their system, so Ott did that for me since he was still whitelisted from their onboarding. @LaFreda1 @rnz6 do we need to confirm they received and it's good?

**Comment by TaneaY** [comment]
Follow-up sent to Kansas,

Hi Dane,

We have received confirmation that the below message has been corrected and resubmitted.

Please reach out to us if you have any further questions or concerns.

Thank you,

**Comment by adegolier** [comment]
Tyler on the ImageMover side said that he made the updates to help keep this from happening in the future.

**Comment by LaFreda1** [comment]
@adegolier Thanks for the update. Closing this ticket; will reopen if needed.
