### ISSUE TITLE
What are your topics for ReportStream Engineering discussion, June 7

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#1230]
Add your discussion items as a comment here.  Meeting is at 1pm ET.
@tlosbo
@mauricereeves
@Mr0grog
@mry-usds
@RickHawesUSDS
@ronaldheft-usds
@carlosfelix2
@joemeree
@pathikkothari
@td-usds

**Comment by MauriceReeves-usds** [comment]
We could put these in discussions as well. While we're discussing discussions, if you have not yet introduced yourself there yet, please do. 

https://github.com/CDCgov/prime-data-hub/discussions/1196


Also, I'll discuss the addition of ktlint to the gradle build.

**Comment by carlosfelix2** [comment]
1. Adding unit test coverage (e.g. jacoco)
2. Documenting code (e.g. Kdoc)

**Comment by RickHawesUSDS** [comment]
Changing to `prime-reportstream` repo name

**Comment by tlosbo** [comment]
1. Error reporting: Jim has mentioned the need for error reporting back to senders. Curious as to what we have in place and if we need to implement anything. This could include general bad requests on initial submit and failed retries on sending reports to receivers.
2. API end point versioning: any thoughts or plans to do this as our /api/reports payload changes between some releases
3. Best way for Pablo and me to ask questions or get feedback before submitting PRs? Slack or Discussions?

**Comment by MauriceReeves-usds** [comment]
I'd like to discuss the possible solutions for the Sofia 2 LIVD lookup bug. The PR is here: https://github.com/CDCgov/prime-data-hub/pull/1218

The background is that we are running into a bug for some test types that check for more than one type of condition, for example the Sofia 2 that looks for both COVID as well as Influenza A+B. In the case of the Sofia lookup, we sometimes return an influenza result instead of the COVID result, which is causing problems for some PHD's.

For a background on the LIVD table, a provider can order a test like the Sofia 2, and it has one LOINC code, but the actual execution of the test generates three distinct LOINC codes for the test performed.

Here are the three rows in the LIVD table for the Sofia 2 test
![Screen Shot 2021-06-07 at 10.24.15 AM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/593379ec-c786-4ad9-9ae0-abbc64b7e0c5)

And here are the test ordered code and test performed code for the Sofia 2
![Screen Shot 2021-06-07 at 10.24.31 AM.png](https://images.zenhubusercontent.com/5ff4880376fe251547594b05/7b29a404-63e8-46cc-9396-815d32aa47b0)

My initial proposed solution was to add the ability to perform additional filtering to the `LookupTable` class by passing in a `Map<String, String>` that would then filter down the `LookupTable` to just those rows where the column value (the map's key) matches the values we provide (the map's value).

Unfortunately, there is the additional complication that at least one of our Senders does not give us the `test_performed_code` which means the problem could persist even after this solution is merged.

There are, therefore four possible additional fixes we'd like to explore:
1. Asking all senders to make sure they give us the `test_performed_code`. We would communicate that we need this field and add it to our quality filters
2. Adding logic that would filter down the LIVD table by performing an in string search or regex search in some specific columns before doing additional filtering. I would recommending adding this to metadata, and therefore in yaml files that get loaded. For example, something like a LIVD jurisdictional filter
3. Adding a column to the LIVD tables that would specify which topic each row applies to, and then do a filter to only compare rows where the topic column matches the topic for the schema
4. Split the LIVD table into separate tables (and therefore separate files) for each topic, so we'd have a COVID LIVD file, and an influenza LIVD table, etc

These all, obviously, have different tradeoffs, and I'd love to get the feedback of the collective group of engineers before we commit ourselves to a specific path. 

I'd also really like to get this into production as soon as possible because this bug is causing serious heartburn for some PHDs.

**Comment by MauriceReeves-usds** [comment]
Final topic to discuss:

File name formats. How they work now and what's changed.

**Comment by RickHawesUSDS** [comment]
Change of repo from `prime-data-hub` to `prime-reportstream`
