### ISSUE TITLE
Add additional attributes to receiver - show/hide

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-reportstream#1242]

**Comment by jimduff-usds** [comment]
@jlusds Now I'm not quite sure I'm properly remembering the details on this.    Show and Hide receivers where?  And what exactly gets hidden?

Currently the receiver shows up visible to users in these places:

1. the json response to a report submission, listing which receivers are getting the data.
2. in the web-receiver download site
3. (someday) In our as-yet-unwritten history/lineage API
4. in Metabase

Can you confirm that this show/hide refers only to (2) in that list?    Also, that its the _data_ associated with the receiver you want hidden?

Thanks

**Comment by jlusds** [comment]
Sorry for the lack of detail

Correct, this would be to show/hide the data related for a given receiver in the web-receiver download site

**Comment by MauriceReeves-usds** [comment]
@brick-green-agile6 I am assigning this to you but I am putting this into the ice box for now because I am not sure if I want to keep adding information about display in with receiver information. I'd like to give this some additional consideration. One thing I was thinking about is adding a display settings table that would let STLTs order the receivers how they want to see them, and toggle display.

fysa: @jlusds @Adrian-Brewster @jimduff-usds
