### ISSUE TITLE
Prototype running GitHub Actions locally

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-reportstream#1255]
This will enable faster GitHub Action development. Could we use https://github.com/nektos/act?

**Comment by td-usds** [comment]
act _works_ but there are some subtle nuances:
1. a checkout action checks out the github repo, not your local repo; so you have to push things up (I'm still looking at whether a clone of a clone could circumvent this), but the actions that are being run do not appear to be the ones that are checked in, they appear to be whatever is the current state of the workflow in your working directory (this last thing makes sense because that's what you want to test anyway)
2. There appear to be some subtle differences between the images that are used by github and the ones used by act. For instance, on the github `ubuntu-latest`, you don't have to install `docker-compose` and it is present by default. Your local act-run will require you to install it if you want to use it.

So there is _some_ friction...

**Comment by ronaldheft-usds** [comment]
@td-usds Both of those sound like the differences from GitHub actions probably outway the costs of setting this up. Would you agree, or do you think this could be a time-saver with more time spent working through the issues?

**Comment by td-usds** [comment]
I think setting this up does not make sense at this point. For those tasks that may benefit from it (i.e. purely modifying github workflows and *nothing* else - which is rather rare), sure we can run it locally, but I don't think institutionalizing this makes sense.

**Comment by ronaldheft-usds** [comment]
Agreed. Thanks for investigating!
