### ISSUE TITLE
See if we can add another cipher to support AL-PHL

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#12714]
See if we can add `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384` as a supported cipher for incoming traffic.

From the TI folks:
We found out that the version of the Integration Engine HTTP client that AL-PHL is going to be using to call ReportStream’s APIs doesn’t support any of the cipher suites RS currently supports. The http client supports the following:
```
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
```
It seems RS already supports `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` , so we’re wondering if it is be possible for RS to support `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384` , or any of the others cipher suites so they can establish the connection

**Comment by snesm** [comment]
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 is considered weak because of CBC flaws, and dangerous for TLS 1.0 and earlier.  We use TLS 1.3 or 1.2 which has fixes for the immediate threats, but the algorithm is still considered flawed.  These flaws have been known since 2013, so I strongly recommend that they explore upgrading their software as the first approach.

**Comment by MauriceReeves-usds** [comment]
@pstonebu @snesm @jeremy-page given the possibility that senders won't easily be able to upgrade away from `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384`, we need to explore what it would mean to add support for it with the caveat that we recognize and document the risks. I feel a process probably needs to built around this, including documenting the reason for the exception and a potential migration plan? This would be a good way for us to identify potential areas for technical assistance we can offer to PHA's.

**Comment by JohnNKing** [comment]
Unfortunately, this particular partner isn't able to support GCM or POLY ciphers dues to limitations of their integration engine. As a work-around, we're currently exploring receiving ETOR messages via inbound SFTP instead of HTTPS.

@MauriceReeves-usds, @jeremy-page: Is there any appetite for pushing for an exception for CBC at this point?
