### ISSUE TITLE
Implement preview images to ReportStream website pages

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#12891]
## Problem statement

When the link to the ReportStream website is shared, we do not specify what the image preview should be. This ticket captures the work of implementing the select image assets to pages/URLs per design's specifications.

## What you need to know

- Images by location: https://docs.google.com/spreadsheets/d/1YiLtOr0NIIeuRYvxvox2r0L19U3bLagl9IFfHPH8yb8/edit#gid=529723033
- Sharepoint folder: [Image assets](https://cdc.sharepoint.com/:f:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/01_WebDesign/Assets?csf=1&web=1&e=efc4mG)

## Acceptance criteria

- [x] When sharing the ReportStream URL, the image previews reflect the specified image assets
- [ ] Refresh LinkedIn's cache for this issue (not currently working on LinkedIn)

**Comment by jpandersen87** [comment]
This can be used to verify the preview on pages: https://www.linkedin.com/post-inspector/

**Comment by audreykwr** [comment]
Thank you for catching that! Added now. @penny-lischer

**Comment by penny-lischer** [comment]
@audreykwr @chris-kuryak unfortunately we had a couple of issues when playing this story.
1. Since our app is a SPA the meta tags being read can only come from the initial html. I have added all of the meta tags required from the story but only the "default/homepage" meta tags will appear. If we ever decide to convert to next.js this will work as planned but for now we have limited capabilities.
2. When testing any other page besides the homepage via the LinkedIn post inspector, the post inspector returns a 404 due to the way our app is configured so even if #1 wasn't an issue the specific meta tags for each page would not appear.
