### ISSUE TITLE
Last Mile Failures API returning 503

### ISSUE THREAD

**Issue by adegolier** [CDCgov/prime-reportstream#13073]
## Describe the bug
Visiting the [Last Mile Failures page](https://reportstream.cdc.gov/admin/lastmile) on ReportStream returns an error.
<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1R4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df9c00b4089901c82892eb03610f879485b0b600/image.png" alt="FrontEndError.png" />

Using the dev tools to check the network shows that the `getsendfailures` API is returning a 503.
<img width="1296" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3p4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99a628e7702475770031d5c5ad785a3b1ff7c3b8/image%20%281%29.png" alt="getsendfailures.png" />

## Impact on ReportStream
It's difficult to see whether there are send failures and manual resends are also difficult.

## Steps to reproduce
1. Go to https://reportstream.cdc.gov/admin/lastmile
2. See error

## Expected behavior
The Last Mile Failures table should display.

## Logs
I wasn't able to find this error in Azure, but Jeremy was able to find an instance that appears to be it [here](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-data-hub-prod%22%2C%22Name%22%3A%22pdhprod-appinsights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-data-hub-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fpdhprod-appinsights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22ee1c9177-b6cf-11ee-ba97-000d3a12649f%22%2C%22timestamp%22%3A%222024-01-19T13%3A37%3A26.205Z%22%2C%22cacheId%22%3A%22495a49fe-9b51-496f-ae0d-03daf4225a27%22%2C%22eventTable%22%3A%22dependencies%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222024-01-19T13%3A55%3A02.834Z%22%7D%7D). (Note: I believe you will need to be logged into Azure as SU to access that link)

## Additional context
This appears to have been caused by something in the big deployment on Tuesday 1/16, as that morning prior to deployment is the last known good for the Last Mile Failures page. Juan checked it that morning and it was good, and was not good the morning before the deployment that Thursday 1/18.

**Comment by victor-chaparro** [comment]
The Last Mile failures page calls this API with this parameters: https://staging.prime.cdc.gov/api/adm/getsendfailures?days_to_show=15. The API uses this postgres function to return results:
`select * from list_send_failures(15)`
But the function is failing with this error: 
`[22P02] ERROR: invalid input syntax for type uuid: "" Where: PL/pgSQL function list_send_failures(integer) line 4 at RETURN QUERY`

**Comment by victor-chaparro** [comment]
It also seems like the issue happens when action_params is empty in the action table. Because the query above tries to get the report id from there  this way `split_part(a.action_params, '&', 3) as "report_id"`. To fix this we would have to populate the report ids on the table some way. To prevent from this happening in the future we need to find where these are not getting populated, and it's likely happening at the RESTTrasport, since that's where most of the failures seem to be happening with empty report ids.

**Comment by victor-chaparro** [comment]
It looks like this issue is related to the format changes on how we log errors in the database. The query that is failing is expecting action_params in the action table to be in this format: `report&SEND&2485d101-0412-4b14-927d-1c8a5424245d&false&2023-12-15T10:26:02.703775142Z` and it was changed to this: `{"type":"report","eventAction":"SEND","emptyBatch":false,"reportId":"aea12b20-26bd-48ba-8491-09a94ac40a38","at":""}`

**Comment by arnejduranovic** [comment]
We need to investigate if the azure queue message format affected any other part of the system as well
