### ISSUE TITLE
Log4j error logs during prime cli commands

### ISSUE THREAD

**Issue by jalbinson** [CDCgov/prime-reportstream#13269]
## Describe the bug
Log4j spits out a series of error logs when running any prime cli command. This does not affect functionality of the prime cli but is worrisome to engineers running commands against production.

## Impact on ReportStream
It is noisy and annoying when running any prime cli command.

## Steps to reproduce
1. run the following
```bash
./prime fhirpath --help
```

## Expected behavior
No error logs when a prime cli command is run.

## Resources
![image (1)](https://github.com/CDCgov/prime-reportstream/assets/1209453/eebe40b1-271f-4e76-80b3-c01510262fc4)

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/13269?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @JFisk42 @mkalish @thetaurean

**Comment by jalbinson** [comment]
Here's where the format is defined: https://github.com/CDCgov/prime-reportstream/blob/6edf2ef3068e145d0b3798a7d27533c33ab89e42/prime-router/src/main/resources/jsonTemplate.json

**Comment by david-navapbc** [comment]
<img width="1208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGhDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9477e52addee4ba56866176d45b69db38dae96e3/Screenshot%202024-04-08%20at%2012.12.43%E2%80%AFPM.png" alt="Screenshot 2024-04-08 at 12.12.43 PM.png" />

<img width="1208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80ffaec9f385457b53c79eeb789ff1582ee40bee/Screenshot%202024-04-08%20at%2012.12.43%E2%80%AFPM.png" alt="Screenshot 2024-04-08 at 12.12.43 PM.png" />

[prime-router-dependency-output.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--763e5190a713e3f718cfbd4e54eaa1e9ed5067cb/prime-router-dependency-output.txt)


I've run this to ground enough to where I'm pretty sure I know what's going on. However I'm confused by at least one thing. 

The simple statement is that there appears to be an interaction between the shade plugin and multiple versions of log4j such that something gets shaded in a way that nerfs the xformer's ability to create the json logging output. 

see

https://stackoverflow.com/questions/75838785/console-contains-an-invalid-element-or-attribute-jsontemplatelayout-even-after/76681723#76681723

https://stackoverflow.com/questions/71458136/log4j-jsontemplatelayout-doesnt-work-when-jar-file-built-by-shadowjar

https://stackoverflow.com/questions/44480197/log4j2-error-unrecognized-format-specifier-t

**Comment by david-navapbc** [comment]
follow up as I'm the kind of guy who can't resist a good puzzle. 

1. it hit me that if `org.apache.log4j.*` is included in the final uber jar but is not being picked up by the build system it's either got something to do with the shading or something we're pulling in has a local source copy that's namespaced as `org.apache.log4j.*` . 

2. I did some digging and I'm almost certain it's a stripped down version of log4j 1.x. I quick-compared the [vendor source of log4j1](https://logging.apache.org/log4j/1.x/download.html) against what's in the uber jar and the former appears to be a superset of what's in the uber jar. 

3. I looked at the [CVEs for log4j1](https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-37215/Apache-Log4j.html) because I know this library has a history for critical security defects.  [Here is another breakdown](https://blog.sonatype.com/new-log4j-1.x-cves-and-critical-chainsaw-vulnerability-what-to-do) of the more recent ones. I'm not seeing anything in the part of log4j1 we have that matches with anything severe in the CVE list. 

My hypothesis is that the presence of this second instance of log4j is somehow screwing with the shading plugin in the manner described in the SO links in the post above. We might be able to use the transformer plugin method (also in the SO links in my last post) and be done with it. That - if it works - will resolve the formatting error messages. 

We can also try to exclude the `org.apache.log4j.*` package from being included but that might be tricky if the build system doesn't see it as a dependency. The shading plugin takes arguments. There might be something there. 

It seems relatively harmless to have in there but I have to admit given the history of issues with that library and the fact that new issues continue to be discovered it would make me feel better if we could just get rid of it either now or at some future point.

**Comment by david-navapbc** [comment]
turns out the Transformer suggested by the SO folks is already baked into the shade plugin. 

https://imperceptiblethoughts.com/shadow/changes/#v4-0-0-2018-09-25

and it's not doing what we need it to do. My gut is telling me this is due to the fact that the second instance of log4j (the mini log4j1 one) is not registered with the build system as a dependency is making this complicated.

will try a few other things ...

**Comment by david-navapbc** [comment]
fixed the issue and a few others to boot! 

PR: https://github.com/CDCgov/prime-reportstream/pull/13994

tl'dr - using the baked in transformer ended up working - it just needed to be invoked in a particular manner.
