### ISSUE TITLE
Ideation: Speeding up back and forth user comms

### ISSUE THREAD

**Issue by audreykwr** [CDCgov/prime-reportstream#13979]
## Problem statement
We identified potential priorities and exploring areas we need to learn more about. Speeding up the responses we get from users was one of those priorities

## What you need to know

- [Onboarding Journey Improvement Synthesis](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B3ADDDFE6-961D-49CE-B237-813024723BF6%7D&file=Document1.docx&action=default&mobileredirect=true)
- [Initial pass at plan in mural](https://app.mural.co/t/primedatainput6410/m/nava4113/1672323752891/18dba3187f29b396293271285034f988f4189801?sender=uc55a7af3b66977fba12f5528)

## Acceptance criteria
- [x] List of ideas (documented)
- [x] How to measure the improvement of "speeding up back and forth comms with users"
- [x] Highlight how each idea will impact the original purpose of "speeding up back and forth comms with users"
- [x] Review with Product for Prioritization and next steps

**Comment by audreykwr** [comment]
Reviewing with Chris today

**Comment by chris-kuryak** [comment]
Notes from Chris:
- Idea 2 could provide a bigger impact for onboarding Senders, rather than Receivers. And therefore is not the highest priority.
- Idea 3 it is unclear on frequency and method of reminding external users, so this may be a heavier lift with unclear benefit.
- Idea 1 seems like the highest priority for this quarter given that it would also benefit just having clarity around process and status internally and externally.
- Get feedback from onboarding engineers

**Comment by chris-kuryak** [comment]
@audreykwr Please link the document you have been using for writing down these ideas in this ticket

**Comment by audreykwr** [comment]
[Doc with ideas](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B1D6D8422-28AE-4BEF-987E-444F3B99E659%7D&file=Improving%20response%20time%20proposal.docx&action=default&mobileredirect=true)
