### ISSUE TITLE
Authentication Programmer's Guide

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#1404]
Need: To create a programmers guide to walk new senders through the authentication/onboarding process.  We can use the Waters guide as a starting point. @BerniXiongA6

**Comment by BerniXiongA6** [comment]
My goal was to review @joemeree 's programmers user guide and provide any initial reactions and feedback by end of sprint. My comments and suggested edits are in the comments of the attached Doc.

[https://app.zenhub.com/files/304423150/9b2a3544-949f-4c23-8efd-05d507fd3fb9/download]

**Comment by BerniXiongA6** [comment]
7.6.2021 @jimduff-usds to review RS programmers user guide and then circle back to discuss next iteration

**Comment by BerniXiongA6** [comment]
7.16.2021 Here's the RS programmers user guide with both Joe's and my revisions. I've accepted most marked changes since they were design/formatting revisions. I've left the comments open in the right pane since they'll need input from the team. I used the RS content style guide when editing (so that's why you'll see a slightly different layout). If I missed anything, we can do a final clean up before sending it off. I'm happy to help with that. @jimduff-usds can you review the comments and take another peek at the guide? cc: @joemeree @hie1 

_[https://app.zenhub.com/files/304423150/e74d61f9-f7c8-4154-bcaa-47678c60cd34/download](https://app.zenhub.com/files/304423150/e74d61f9-f7c8-4154-bcaa-47678c60cd34/download)_

**Comment by BerniXiongA6** [comment]
7.21.2021 See my comment from 7.21.2021 on[ Issue # 1612](https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1612) for the latest on this current pass of edits to programmer "good enough" draft. 

7.23.2021 @joemeree and I agree to connect on Monday to discuss suggested edits / pending questions that need clarification before edits can be made.

**Comment by BerniXiongA6** [comment]
7.28.2021 See updates on "good enough" version of guide over on [issue # 1612](https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1612).
