### ISSUE TITLE
[BUG] E2E tests are failing on a Github action

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#14194]
## Problem statement
E2E tests are failing in the Front-end github action and creating exceptions and pager duty alerts.

## What you need to know
- [Slack Conversation](https://nava.slack.com/archives/C025F5W5Q7L/p1713809761731559)

## Acceptance criteria

- [x] E2E tests not failing in the Front-end github action
- [ ] Daily Data E2E tests to use Mock Data instead of staging data

**Comment by penny-lischer** [comment]
e2e currently points to staging and there could be many scenarios in which the e2e tests could fail during a build. i.e. backend is down, org that is being selected doesn't exist, dev updated code that an e2e test expected and forgot to run the e2e tests locally before pushing up PR etc... 
When the e2e tests fail, the PR will not pass Frontend checks and the owner of the PR needs to investigate/fix them at that time.
These failures are triggering pager duty since the tests run against staging.

**Comment by chris-kuryak** [comment]
Thanks @penny-lischer !
Let's align with Victor/other engineers on this proposed solution

**Comment by chris-kuryak** [comment]
Near term solution aligned on by the team was to have Daily Data E2E tests use Mock data instead of Staging data.

**Comment by snesm** [comment]
E2E tests appear to be failing on all frontend builds (including todays deployment [test](https://github.com/CDCgov/prime-reportstream/actions/runs/8885921818/job/24398359271?pr=14239#step:3:2465)).

The issue appears to have started at or immediately after https://github.com/CDCgov/prime-reportstream/pull/14090
