### ISSUE TITLE
Update FHIRRouter Azure Events to Store LOINC Code Info

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#14331]
### User Story

As a ReportStream developer troubleshooting issues,
I want to see the LOINC code alongside the condition ReportStream mapped it to,
so I can evaluate its accuracy when needed.

### Description/Use Case

Update `AzureEventUtils.getObservations` to include the `code` and `display` fields in the second to last box pictured below

![image](https://github.com/CDCgov/prime-reportstream/assets/118766341/ec31140e-075f-42f5-b526-c718259acfa1)

### Acceptance Criteria

- [ ] `ReportAcceptedEvent` and `ReportRoutedEvent` both include test performed LOINC code and display alongside the mapped condition info

**Comment by Andrey-Glazkv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14331?planning-poker) with Zenhub @adegolier @arnejduranovic @brick-green @jack-h-wang @jalbinson @mkalish @thetaurean

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14331?planning-poker) with Zenhub @JFisk42

**Comment by Andrey-Glazkv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14331?planning-poker) with Zenhub @david-navapbc

**Comment by arnejduranovic** [comment]
There appears to be an issue with the PR that completed this ticket. Observation is now unstructured:
![Screenshot 2024-06-28 at 9 33 22 AM](https://github.com/CDCgov/prime-reportstream/assets/118766341/105ac5a0-d8af-475e-9d4b-c309cbb08c29)

Whereas prior to this PR it was structured:
![Screenshot 2024-06-28 at 9 33 55 AM](https://github.com/CDCgov/prime-reportstream/assets/118766341/7a376638-6df2-49b1-a59c-7447088746eb)

Moving this ticket back to sprint backlog instead of creating a new one.

**Comment by JFisk42** [comment]
On Friday I investigated the unstructured observation results. This ended up happening whenever the amount of observations being logged caused the field to exceed the Azure character limit for a field (8,192 characters). This limit causes the logs to be truncated, thus producing invalid json causing the data to be unstructured in Azure (only when the limit is reached).

The limit being reached with the smoke tests that are run, specifically the end2end_up test because it has 26 observations in a single report. I looked into how many observations are getting logged per report in prod over the last 50 days and the maximum was 9 observations. Thus it is very unlikely to ever be an issue for how any of our current clients are using ReportStream. 

Thus there is no further action needed for this ticket.
