### ISSUE TITLE
Fix field truncation

### ISSUE THREAD

**Issue by JessicaWNava** [CDCgov/prime-reportstream#15110]
### User Story
As a user, I want to be able to specify which HL7 fields to truncate and have them truncated

### Description/Use Case
Some fields are not respecting the truncateHl7Fields setting.

### Dev Notes
Fields that we specifically noticed were not getting truncated: 
- PID 3-6
- PID 7-10-5
- SPM 2-2-2
- ORC-21-1
- OBX-23-1
- OBX-15-1
- OBX-23-10

### Acceptance Criteria
- [x] All of the HL7 fields can be listed in the truncateHl7Fields and they will be truncated.

**Comment by lucero-v** [comment]
- **PID-3-6** : fixed with #15409, will have to be specified as "PID-3-6-1" in order to to work. Length: 20
- **PID-7-10-5**: most probably a typo, didn't find it in the HL7 spec
- **SPM-2-2-2:** fixed with #15409, Length: 20
- **ORC-21-1:** already truncates, added test case, Length: 50
- **OBX-23-1:**  already truncates, added test case, Length: 50
- **OBX-15-1:** already truncates, added test case, Length: 20
- **OBX-23-10:** already truncates, Length: 20
