### ISSUE TITLE
AK - Test Discrepancy 

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#15156]
## Problem statement

Possible connection issue, 

"I just noticed a discrepancy in last test dates reported by SimpleReport’s daily ‘Alaska Updated CLIA Report’ and what we have recorded on NEDSS. It appears that all last test dates after May did not reach the State of Alaska. I’ve attached the daily report for active 2024 SR accounts with a second tab for last test dates in NEDSS. Highlighted in red are the discrepancies. Could SimpleReport please investigate and coordinate with Inductive Health?"

## What you need to know

 [Audits comparison SR and IH.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11796e68ad5a96348a43859fe0fe12d20e3acb40/Audits%20comparison%20SR%20and%20IH.xlsx)

Customer support investigated and confirmed the following:
All test results listed on audit sheet are showing in SimpleReport

Daily Data shows submitted results in May and beyond however unable to view HL7, file download appears as "undefined" 

May results expired for investigation, file names have changed formatting examples include: ak-phd.full-elr%2Fc1615864-0384-469e-9d64-72385eff3f9b.hl7, 
ak-phd.full-elr%2Fak-receiver-transform.yml-0fe7d840-b00b-4fd1-bb47-812449373e7c-20240620032534.hl7

## Acceptance criteria

Confirm connection to Inductive Health/Alaska

## To do

Verify results have been submitted to Inductive Health/Alaska

Investigate HL7 Undefined error

Advise support of updates

**Comment by TaneaY** [comment]
Feedback from Inductive Health,

"Hi Jonathon and all,

 

We were able to locate the files on the SFTP. They were populating in a directory called /prod/ rather than the standard /incoming/prod/.

 

We are adjusting the scripts on our side to pull from both /prod/ and /incoming/prod/ so the files will flow into the NBS. There are 166 files in there we will route in.

 

AK DOH team – Please let us know if you would like us to assist with any DRR or DRSA queue clearing.

 

Let us know what questions you have."

**Comment by chris-kuryak** [comment]
@GilmoreA6 to confirm on messages being sent (May through 7/10)

**Comment by chris-kuryak** [comment]
@TaneaY We can either change where we are sending data OR they can handle on their end. Whichever is their preference.

**Comment by chris-kuryak** [comment]
Platform is currently working to fix the File Download issue.

**Comment by TaneaY** [comment]
Follow up sent 
Hi all,

Lindsey, Thank you for locating the files. I have reached out to engineering to verify the receiver settings. 

Please confirm if you would like us to change to the /incoming/prod folder instead of the /prod/ folder or will the script changes be enough to prevent this error going forward? 

Johnathan- Once received, please verify that you have received all missing test results as it is confirmed that all test results received should have been transmitted during this time period.

Please let us know if there are any further questions or concerns.

Thank you,

Tanea

**Comment by TaneaY** [comment]
User confirmed no receiver settings can remain the same all files received.
