### ISSUE TITLE
Review and test Intake Form updates

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#15979]
## Problem statement
Once support team updates the intake form, we want to review test it via the RS website link(s).

## What you need to know

- [Intake form content update](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Website%20content/Sender%20intake%20form%20updates.docx?d=w310d0950cf7943cc8415445946bd7d74&csf=1&web=1&e=twYQF0)  - Approved and in Support team's hands to update
- [Live link](https://app.smartsheetgov.com/b/form/8c71931f25e64e42bf1fef32900bdecd)

## Acceptance criteria

- [x] Confirmed Intake form updated
- [x] Confirmed test submission working properly

**Comment by jillian-hammer** [comment]
Per Tanea 10/10: Sender intake form is updated and live at the [original link](https://app.smartsheetgov.com/b/form/8c71931f25e64e42bf1fef32900bdecd).

**Comment by jillian-hammer** [comment]
Flagged edits to Tanea that are outstanding: 

- Update "Onboarding Form" to "Healthcare Organization Interest Form"
- Update "Submitting Organization" to "Organization"
- Update "Submitter Name" to "Your name"
- Update "Submitter Email Address" to "Your email address"
- Update "What states do you report to?" to "What jurisdictions do you report to?"
- Typo - change "checkboc" to "checkbox"
- The colon after "I agree to the Terms of Service:" can be removed, since the checkbox is placed to the left of the text instead.

Waiting for Tanea to update.

**Comment by jillian-hammer** [comment]
Successfully fixed typos and tested a submission with Tanea. Closing ticket.
