### ISSUE TITLE
Monthly Comms for Nov 2024 - Content creation

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#16103]
## Problem statement
Monthly update content creation

## What you need to know

- Guidance for content/timeline provided in #15851
- Working space: [Nov 2024 Content doc](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Monthly%20update/20241105_ReportStream_Monthly-update-drafting_Nov2024.docx?d=w7fe3069aa8b64fb88d41fff568c43c81&csf=1&web=1&e=JRnc39)

## Acceptance criteria
- [x] Content created in accordance with guidance found in #15851
- [x] Content reviewed by Product Manager and Account Manager

## To do
- [x] Consider removing the following section (check with Chris or Glenn):
> Public health agencies: If you are receiving data and have not updated your connection, please contact...
- [ ] Consult with Chris -- can we make some of the Action Items dynamic based on if they are a sender or receiver? Would help reduce the length of the email make make it more targeted.

**Comment by jillian-hammer** [comment]
Moving to Blocked due to the SendGrid licensing issues. @chris-kuryak I'm testing out the viability of the Free tier to meet our needs, but it doesn't seem like it will work for ReportStream.

Although the Free tier is advertised as "100 free contacts" – this actually means 100 free _uploads_ of a contact. If I upload 100 contacts, send the first round of an email, then delete them and upload another 100 contacts, it will incur overages because they count that as storing 200 contacts. So, our original plan to work around the limit by segmenting the send into two groups will NOT work on the free plan. See the warning UI below.

<img width="1101" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16ff54a98ff496fe45e0a8ae0b3012908a93a822/image.png" alt="image.png" />

<img width="1290" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEdQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58620e772d74f0882bb526d886eed804b1bbb9ae/image.png" alt="image.png" />

So, we may need to flag this to the POs and/or look into an alternate solution.

**Comment by jillian-hammer** [comment]
[Content draft](https://cdc.sharepoint.com/:w:/r/teams/ReportStream/Shared%20Documents/Design%20and%20Research/03_Content/Monthly%20update/20241105_ReportStream_Monthly-update-drafting_Nov2024.docx?d=w7fe3069aa8b64fb88d41fff568c43c81&csf=1&web=1&e=d0FTBj) is ready to review with @chris-kuryak

**Comment by chris-kuryak** [comment]
Content approved. That monthly number is accurate.

**Comment by jillian-hammer** [comment]
@chris-kuryak thanks for confirming that #! moving on to scheduling the send in #16102. closing this ticket.
