### ISSUE TITLE
Find path to better deployment automation

### ISSUE THREAD

**Issue by devopsmatt** [CDCgov/prime-reportstream#16487]
- [x] Create a list of manual and brittle steps, pain points.
- [x] Identify steps that can be reasonably automated.
- [x] Create a resolution proposal.

DoD:  Identify all the gaps in the current deployment automation.

**Comment by emvaldes** [comment]
I have reached out to Jack Wang and asked for a time to meet so that we can work on setting up my environment as we talked about in our previous session. At this point in time, he has provided me with some information so I can follow the setup process on my own.

**Comment by emvaldes** [comment]
Good morning. If you haven't already, I would start by following [the documentation here.](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md) If there's something that needs clarity, let me know.
[README.md](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md)
Getting Started as a ReportStream Developer
Overview
These pages are a work in progress, please see the [old pages](https://app.slack.com/client/docs-deprecated/getting-started/) if something is  
missing
Table of contents
• [Table of contents](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#table-of-contents)
• [Locally installed software prerequisites](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#locally-installed-software-prerequisites)
• [Bulding the baseline](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#bulding-the-baseline)  
  • [First build](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#first-build)  
  • [Seed the Postgres db and vault](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#seed-the-postgres-db-and-vault)
• [Running ReportStream backend](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#running-reportstream-backend)
• [Debugging](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#debugging)
• [Running the frontend](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#running-the-frontend)
• [Running the static site](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#running-the-static-site)
• [Submit a sample message through the app](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#submit-a-sample-message-through-the-app)
• [Troubleshooting](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#troubleshooting)
• [Next steps](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/getting-started/README.md#next-steps)
Locally installed software prerequisites
You will need to have at least the following pieces of software installed locally in order to be able to build and/or  
debug this project:
• [git](https://app.slack.com/client/T01LG55J6AY/install-git.md) including git-bash if you're on Windows
• [Docker or Docker Desktop](https://docs.docker.com/get-docker/)
• [OpenJDK](https://app.slack.com/client/T01LG55J6AY/install-openjdk.md) (currently targetting 17)  
  • See the linked docs for important instructions on setting JAVA_HOME
• [Azure Storage Explorer](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer)
• An IDE. IntelliJ is recommended for Kotlin/debugging support.
To reduce the build-debug cycle time you can install these tools to run the code directly. These tools are required if  
you are using an Apple Silicon computer, otherwise they are optional.
• [Azure Functions Core Tools](https://app.slack.com/client/docs-deprecated/getting-started/install-afct.md) (currently targetting 4)
• [AzureCLI](https://app.slack.com/client/docs-deprecated/getting-started/install-azurecli.md)
• [Gradle](https://app.slack.com/client/docs-deprecated/getting-started/install-gradle.md)
• One or more [PostgreSQL Clients](https://app.slack.com/client/docs-deprecated/getting-started/psql-clients.md)
Warning
If you are using an Apple Silicon computer you will need to use Gradle as Microsoft's Azure Function Docker image is  
only amd64 compatible. There are  
also [known issues](https://docs.docker.com/desktop/mac/apple-silicon/#known-issues)  
running Intel Docker images on Apple Silicon. Both approaches to running the project are documented here.  
Many of our local developer tools are set up to run in Docker containers. Looking at our docker-compose.yml file,  
the prime_dev service does not work on Apple Silicon. Likewise, the builder service in  
our docker-compose.build.yml does not work.
Bulding the baseline
First build
The cleanslate.sh script does the base work needed to start developing for ReportStream. It only needs to be run once.  
This script runs on Apple processors, but it skips a few steps. We will need to do these missing steps by hand.
1. [Clone the prime-reportstream repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository)  
to your workstation using git.
2. Initialize your environment and run an initial build by running the following command using a Linux shell.  
Note you can run cleanslate.sh script to reset your environment as well (run ./cleanslate.sh --help for more  
information). The cleanslate.sh script not only cleans, but also performs a first build and setup of all artifacts  
needed for the build
cd ./prime-router
./cleanslate.sh
Docker Desktop* If you are using Docker Desktop, verify that it is running prior to building or running ReportStream locally. Gradle/Apple Silicon
Run cleanslate.sh
# build the project
./cleanslate.sh --verbose
# ...
# Check that a Postgres instance is running
docker ps
# CONTAINER ID   IMAGE         COMMAND                  CREATED          STATUS          PORTS                    NAMES
# 2962fb214203   postgres:11   "docker-entrypoint.s…"   57 minutes ago   Up 57 minutes   0.0.0.0:5432->5432/tcp   prime-router_postgresql_1
Run support services
ReportStream depends on set of services to be up before running the main Azure service. The cleanslate.sh script  
starts a Postgres database but skips starting a few more that are otherwise started by default when cleanslate.sh  
start is run on a non-Apple processor:
• Azurite - a simulator of Azure storage
• Vault - a secret store
• SFTP - an SFTP server
• soap-webservice - SOAP web service emulator
docker compose -f docker-compose.build.yml up --detach
Additionally, to ensure that Vault is running and the credentials are stored correctly, run the following (which is  
normally covered by cleanslate.sh on non-Apple processors):
docker compose up --detach vault 1>/dev/null 2>/dev/null
You can take down these services by running ./gradlew composeDown or docker compose down command.  
For now, leave these services running and open up a new terminal session.
Seed the Postgres db and vault
To run tests, the Postgres DB and the credential vault need to be seeded with values.  
We will need to have ReportStream running for these steps to work (see previous steps).  
Again, we will use a Gradle task to do these steps.
Warning
If you are getting a connection error during the reloadTables step, you're probably on a mac with the custom Apple  
CPU. Use command gradlew run to get the app up and running and try again.
./gradlew primeCLI --args "create-credential --type=UserPass --persist=DEFAULT-SFTP --user foo --pass pass"
./gradlew reloadTables
./gradlew reloadSettings
Running ReportStream backend
Verify that your docker engine is running prior to building or running ReportStream locally (either Docker Desktop or  
through the command line).
Building and running ReportStream requires a locally accessible PostgreSQL database instance that is initially setup and  
run by the cleanslate.sh script. This database instance runs as a Docker container defined by  
the docker-compose.build.yml file. You will need to start this database instance upon a workstation reboot by using  
the following command:
cd ./prime-router
docker compose --file "docker-compose.build.yml" up --detach
Gradle/Apple SiliconUse Gradle to launch ReportStream, as it will set up the environment variables that ReportStream needs. If you are on a Mac with the custom Apple CPU and are following this guide step by step you've already done this step when you seeded Postgres db and vault.
./gradlew run
ReportStream should continue to run after launching. A successful build will appear like so:
[===========--](https://app.slack.com/client/T01LG55J6AY/===========--) 90% EXECUTING [46s]
> :azureFunctionsRun

A ctrl-c will escape the running ReportStream instance.
Tip
The recommended way to rapidly develop on the ReportStream backend is to use `./gradlew q…

**Comment by emvaldes** [comment]
I have to perform a secondary shadow to those performing a deployment to production that hopefully will be better than my previous one (was too random for me to find any logic).

**Comment by emvaldes** [comment]
Arnej Duranović has kindly provided additional context on this:

The deployment process is documented here: [https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B30F[…]eployment%20Process.docx&action=default&mobileredirect=true](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B30FBCC7D-02B3-4FDE-BBF2-3EEE980B11E1%7D&file=ReportStream%20Deployment%20Process.docx&action=default&mobileredirect=true)

Before you can do a deploy, you need to clone the repo and get it building on your local machine. Here is the developer setup instructions: https://github.com/CDCgov/prime-reportstream/tree/main/prime-router/docs/getting-started

**Comment by emvaldes** [comment]
I have done a lot of progress on this front. I am happy to report that after shadowing Jamie Albinson I was able to finally understand what are the pain points to the teams when it comes to the portion of the process where they manually drives the building and testing and deployment of the overall application deployment process.

**Comment by emvaldes** [comment]
I will simplify it for everyone. Please, see attached PDF file where I am detailing the solution for the existing processes that are followed by the development team.

Basically:

1. the team generates a **deployment/yyyy-mm-dd** branch.
2. Then, they requests the on-call engineer to build and test the site locally in their system.
3. Then, it triggers the same process using the GitHub workflows (which duplicates the same process).
4. Then, once the front-end app and the back-end (router) are build.
5. Then the front-end support (on-call) engineer tests the front-end manually and gives his ok.
6. Then the engineer driving this entire process triggers the approval process (manual stops) to push the branch into the production branch.
7. This in term, deploys these components into the Azure Production environment.

This is just an absolute waste of time (countless hours of duplicating efforts while babysitting this process). We can fix that by removing the overhead and simply split the GitHub Workflows actions into two distinctive stages.

1. Build & Test: Continuous Integration (CI)
2. Deploy the artifacts to the production environment: Continuous Deployment (CD)

Note: The goal here will be to simply create an autonomous process that will drive this in a continuous workflow. Allowing the development team to focus on their work and not on the processes that we are supposed to manage.

[Back-End Deployment Workflow-181124-174447.pdf](https://github.com/user-attachments/files/17805153/Back-End.Deployment.Workflow-181124-174447.pdf)

**Comment by emvaldes** [comment]
We will continue to track these improvements via the EPIC unit and its STORIES here:
https://app.zenhub.com/workspaces/prime-reportstream-5ff4833beb3e08001a4cacae/issues/gh/cdcgov/prime-reportstream/16608

The goals we aimed to accomplish in this Issue are now achieved and we can close it.
