### ISSUE TITLE
Print Displayed List of Successful Submissions 

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1657]
## Problem Statement
As a Sender, I need to be able print my submission history so that I will know for certain what files I have already submitted and so that I can prove I submitted the data.

## Design
[[https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=1597%3A4628](url)](url)

## Acceptance Criteria
- Given I
    - Am logged into ReportStream with **Sender permissions**
- When I
   - Log into ReportStream
   - Choose to view my Submission History
   - View the list of my successful submissions
   - Optionally filter and sort my list
- Then I
   - Can print my list and 
       - Only those results that match the selected filtering criteria will be printed 
       - All results that match the filtering criteria will be printed regardless of how many are displayed on the screen
       - The printed list will be sorted based on the current user-specified sort order
       - All information for the submissions that is displayed will be included in the printed version

## TO DO
- Dev:

**Comment by victorialb-usds** [comment]
Email from Lemoore 2/24/22: "will there be a way to retrieve a report to know what has been submitted, I think this would help us prove we are submitting and meeting all HHS requirements, instead of saving a screen shot daily we could print it weekly or monthly." .... cc @drew-usds @rachelhanster I added this here and deleted new issue that described this part of submission history. User story for this if needed/helpful:
As a facility that uses the RS CSV upload pilot program to submit COVID test results
I want to be able to see and have a record of data submitted.
So that we can prove [have evidence/record] we are submitting and meeting all HHS requirements.
&
for others who submit to be able to see what was submitted previously.

**Comment by rachelhanster** [comment]
Ticket moving to simplereport for its product backlog consideration

**Comment by chris-kuryak** [comment]
Closing by committee. Old issue.
@drew-usds @lizzieamanning
