### ISSUE TITLE
Azure client keys are expired

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#16687]
# DevSecOps Issue

## Summary

The `Release to Azure` step is currently failing with the following error:

```
AADSTS7000222: The provided client secret keys for app '***' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: 70204cb3-0833-49e2-8509-b2f1e5b55300 Correlation ID: fae93d94-d4a4-47e0-ad26-29af5dee568d Timestamp: 2024-11-27 13:52:59Z
```

As a result, we currently cannot merge any PRs into `main` or deploy to the staging Azure environment.

More details are available in this specific run: https://github.com/CDCgov/prime-reportstream/actions/runs/12051720860

## Environment

- [ ] Local
- [ ] Dev
- [x] Stage
- [ ] Prod

This is known to affect the staging environment but other environments may be affected as well.

## Priority

- [ ] **Critical** - affecting prod systems
- [x] **Major** - blocking major functionality, deployment, etc
- [ ] **Minor** - improvements, bug fixes
- [ ] **Nice-to-have** - feature request

## Contact

**Team**: Platform

**Slack Team Channel**: #prime-reportstream-engineering

**Slack Contact (Full Name):** Jack Wang

**Technical Team Lead:** Arnej Duranovic

**Comment by emvaldes** [comment]
@jack-h-wang: Do we have a clear timeline of when this issue was identified?
When was the last time this occurred and do we have any information on what was done to resolve/address these?

**Comment by jack-h-wang** [comment]
> @jack-h-wang: Do we have a clear timeline of when this issue was identified? When was the last time this occurred and do we have any information on what was done to resolve/address these?

We only know that the issue appears to have started between November 25 (https://github.com/CDCgov/prime-reportstream/actions/runs/12018694678/job/33503756596) and November 27 (time of the run linked in the description). I have no other context.

**Comment by emvaldes** [comment]
The recommended/suggested approach documented here [NewClientSecret](https://aka.ms/NewClientSecret) -> [add-a-client-secret](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-register-app?tabs=certificate#add-a-client-secret) seems to be discouraged in favor of using the [certCreds](https://aka.ms/certCreds) -> [certificate-credentials](https://learn.microsoft.com/en-us/entra/identity-platform/certificate-credentials)
We should explore the use of the certificate credentials as soon as we have addressed and resolved the issue at hand so you can continue to have a functional process.

**Comment by emvaldes** [comment]
Sometimes called an application password, a client secret is a string value your app can use in place of a certificate to identify itself.

Client secrets are considered less secure than certificate credentials. Application developers sometimes use client secrets during local app development because of their ease of use. However, you should use certificate credentials for any of your applications that are running in production.

In the Microsoft Entra admin center, in App registrations, select your application.
Select Certificates & secrets > Client secrets > New client secret.
Add a description for your client secret.
Select an expiration for the secret or specify a custom lifetime.
Client secret lifetime is limited to two years (24 months) or less. You can't specify a custom lifetime longer than 24 months.
Microsoft recommends that you set an expiration value of less than 12 months.
Select Add.
Record the secret's value for use in your client application code. This secret value is never displayed again after you leave this page.
For application security recommendations, see Microsoft identity platform best practices and recommendations.

If you're using an Azure DevOps service connection that automatically creates a service principal, you need to update the client secret from the Azure DevOps portal site instead of directly updating the client secret. Refer to this document on how to update the client secret from the Azure DevOps portal site: Troubleshoot Azure Resource Manager service connections.

**Comment by emvaldes** [comment]
It's important to mention that when we see this error:

**AADSTS7000222: The provided client secret keys for app '***' are expired. ...**, the application's name is masked because we have this legacy strategy in place where everything is a secret (attempting to protect configurations in a public repository) and it's understandable but problematic to troubleshoot.

``` console
2024-11-27T13:52:54.9693787Z ##[group]Run azure/login@a65d910e8af852a8061c627c456678983e180302
2024-11-27T13:52:54.9694294Z with:
2024-11-27T13:52:54.9695305Z   creds: ***
2024-11-27T13:52:54.9695681Z   enable-AzPSSession: false
2024-11-27T13:52:54.9696008Z   environment: azurecloud
2024-11-27T13:52:54.9696431Z   allow-no-subscriptions: false
2024-11-27T13:52:54.9696855Z   audience: api://AzureADTokenExchange
2024-11-27T13:52:54.9697317Z   auth-type: SERVICE_PRINCIPAL
2024-11-27T13:52:54.9697668Z ##[endgroup]
2024-11-27T13:52:55.0072709Z Running Azure CLI Login.
2024-11-27T13:52:58.5544979Z [command]/usr/bin/az cloud set -n azurecloud
2024-11-27T13:52:58.7788922Z Done setting cloud: "azurecloud"
2024-11-27T13:52:58.7791244Z Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.
2024-11-27T13:52:58.7793322Z Attempting Azure CLI login by using service principal with secret...
2024-11-27T13:52:59.8482749Z ##[error]AADSTS7000222: The provided client secret keys for app '***' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds. Trace ID: 70204cb3-0833-49e2-8509-b2f1e5b55300 Correlation ID: fae93d94-d4a4-47e0-ad26-29af5dee568d Timestamp: 2024-11-27 13:52:59Z

2024-11-27T13:52:59.8485850Z ##[error]Interactive authentication is needed. Please run:
az login

2024-11-27T13:52:59.9516746Z ##[error]Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```

The error is listed as part of the MS Azure credentials validation process. The output is listing the Application Name but it gets masked by the **GitHub Pipeline** because the value (name) matches a **GitHub Secret** that contains the application's name. We need to re-evaluate this strategy and define certain values as **Environment Variables** instead of as **Environment/Repository Secrets** when in fact not everything is a secret.

**Comment by emvaldes** [comment]
At this point, we do not know what the Application's Name is but it should not matter as the Service Principal is at the MS Azure level so this becomes an irrelevant issue. The solution is to work in collaboration with the MS Azure Support team and let them resolve the renewal of these credentials. We are assuming this is not already performed by some automated process and if it's not, it should be.

Regardless, we are more concerned with a process where we can get the GitHub Secrets updated once these other processes get to update system and/or account credentials, etc.

**Comment by emvaldes** [comment]
We have now updating the GitHub Secret **SERVICE_PRINCIPAL_CREDS** key with the values 
for the application **PRIME-ReportStream**. We are encountering some issues with the current configuration.

``` console
Run azure/login@a65d910e8af852a8061c627c456678983e180302
  with:
    creds: ***
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
##[debug]Reading creds in JSON...
::add-mask::***
::add-mask::***
Running Azure CLI Login.
##[debug]Azure CLI path: /usr/bin/az
##[debug]Azure CLI version used:
##[debug]***
##[debug]  "azure-cli": "2.67.0",
##[debug]  "azure-cli-core": "2.67.0",
##[debug]  "azure-cli-telemetry": "1.1.0",
##[debug]  "extensions": ***
##[debug]    "azure-devops": "1.0.1"
##[debug]  ***
##[debug]***
##[debug]
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.
Attempting Azure CLI login by using service principal with secret...
Error: No subscriptions found for ***.

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
##[debug]Error: The process '/usr/bin/az' failed with exit code 1
##[debug]    at ExecState._setResult (/home/runner/work/_actions/azure/login/a65d910e8af852a8061c627c456678983e180302/lib/main/index.js:2333:25)
##[debug]    at ExecState.CheckComplete (/home/runner/work/_actions/azure/login/a65d910e8af852a8061c627c456678983e180302/lib/main/index.js:2316:18)
##[debug]    at ChildProcess.<anonymous> (/home/runner/work/_actions/azure/login/a65d910e8af852a8061c627c456678983e180302/lib/main/index.js:2210:27)
##[debug]    at ChildProcess.emit (node:events:519:28)
##[debug]    at maybeClose (node:internal/child_process:1105:16)
##[debug]    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
##[debug]Node Action run completed with exit code 1
```
