### ISSUE TITLE
Admin Views the Confirmation for a Selected Submission

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1869]
## Problem Statement
As an RS Admin, I need to be able view the confirmation details for a specific submission so that I will know to which PHD(s) the file was sent.

## Design
https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=1868%3A15072&node-id=1868%3A15230&viewport=241%2C48%2C0.84&scaling=min-zoom&starting-point-node-id=1868%3A15591

## Acceptance Criteria
- Given I
    - Am logged into ReportStream **RS Admin**
- When I
   - Log into ReportStream
   - Choose to view Submission History
   - Select a specific Sender
   - See the list of successfully submitted files for the Sender
- Then I
   - Can select a specific submission and view the following details for the selected submission
       - Date and time submitted
       - File (filename & extension)
       - Confirmation Code       
       - For each PHD to which the data was sent
           - Name of the PHD           
           - Date/Time Transmitted to PHD (is this value available to use now?)
           - Records actually sent to the PHD
    - Each details page has a unique url

## TO DO
- Dev: Allow user to select a specific submission
- Dev: Display the details for the selected submission

**Comment by kevinhaube** [comment]
Blocked by #3539

**Comment by kevinhaube** [comment]
@loripusey Two notes as I merge this in:
1. The endpoints for `/submissions` (both the list endpoint and details endpoint) currently don't return the filename, so this AC could not be met, though I don't think it's a blocker. We can easily add this on as an iterative upgrade to this page. ~1-2 SP

2. There was no AC for a printable page, but the designs showed a print button. I forewent it this time around. Ctrl+P works a treat; the button can be added in pretty easily later as well. ~1-2 SP

I'll create a ticket for 1, but I'm unsure whether 2 is a design or product decision; I'll hold off on making a ticket for that until there's clarity.

**Comment by jimduff-usds** [comment]
@kevinhaube, A bunch of thoughts and comments:

1. We are adding the missing externalName (aka the "filename") field to the History Details response with this ticket:  #4241.
2. In addition, be aware that ticket #4241 will also tweak a couple field names in the History Details, so that when #4241 is done, the History Details will be backwards compatible with the current json response to any submission.
3. The externalName _does_ appear in the list/summary response! - but only if its non-null, which is confusing.   This could be fixed that to always appear, even if null.  (Ticketed as #4309)
4. Per this question from above, _"Date/Time Transmitted to PHD (is this value available to use now?)_", the answer is YES, this is now available in the HistoryDetails.  There are examples in ticket #4263 - scroll down to find an example where `sentReports` is filled in with details.  You'll see we now have both "sending_at" (when we _intend_ to send it) and then "sentReports" is details on _actually_ sending it.
5. Last, I've been trying to sketch out some useful high level summary/status fields, but they get complicated quickly.  I'd love your feedback on what's useful so we don't expend effort when its not needed.   See #4310.

**Comment by kevinhaube** [comment]
@jimduff-usds 
Thanks for the heads up on #4241! I've left a note on the ticket to reach out to Experience since that'll loosely break some of our front-end display (defaults text will be displayed instead of the API-retrieved information)

Ahh, I must have old submissions without the `externalName` property. Thank you!

I believe the question of transmission date/time was an old one that didn't get removed after we discovered the answer, apologies! We are currently displaying this information.

I'll take a look at #4310 and leave some thoughts on the ticket 👍🏼
