### ISSUE TITLE
SPIKE (3 days) -- Research Tom's Work to Consolidate Sender Error & Warning Messages

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1966]
## Problem Statement
As a Sender, I need to see error and warning messages in a structured way so that I am not confused and overwhelmed by a lot of the same type of messages.

## Timebox
- 3 days

## Notes
Refer to the following ticket:
- https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1285

## TO DO
- Understand and document the work that Tom did towards this effort
- Determine and document a plan for 
   - How to finish the work that Tom started
   - Return consolidated messages from a Sender submission (via any submission method) 
   - Return consolidated messages without affecting messages that existing users are getting through the API or vbScript or Simple Report
- Determine the effort involved
- Determine what changes to the CSV uploader will be necessary to display these consolidated messages

**Comment by sean-usds** [comment]
For my own understanding, I went through the entire upload flow and compared it with the [Figma designs](https://www.figma.com/file/ctpYEoOBWGkUnk9cmXzVp2/ReportStream-Submitter-Front-End?node-id=980%3A3216). Here is the current status of each step. Not everything is relevant to to this task, but documenting here in case it is helpful for anyone else 

![image.png](https://images.zenhubusercontent.com/61310371004bdd52b9b7d2c4/2f40871c-bbcd-4adc-8ea2-3464f82b7d06)

The goal of this task will be to come up with a plan for how to rollup warnings and failures (lines 6 and 8 above.)

**Comment by sean-usds** [comment]
Takeaways from Tom's proposed changes https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1285 
- This proposal would simplify the error messages sent to the client, however the messages still would not be a format helpful to match the current figma mocks. It is helpful for displaying unique errors and the the error counts, but not for including the column numbers
- For the `ResultDetail` data class, creating a `ResponseMessage` interface will make the code more extensible and testable compared to just using a `String`. This convention should be adopted

**Comment by loripusey** [comment]
Will had changed the system messages to be able to include the row & col for each message.  Also, I think there were decisions made on-the-fly as we were developing, so it's not surprising that the syncing with the mocks is not 100%.

**Comment by sean-usds** [comment]
No worries about the mocks not matching 100%, figured I'd document here just in case

**Comment by sean-usds** [comment]
## Overview
To complete the work Tom started and roll up warning and error messages in order to match the mocks, there are 3 main steps: 

1. (Server) Implement the `ResponseMessage` interface for each error type defined in the `ResponseMsgType` enum 
2. (Client) Roll up the error messages by grouping them by `ResponseMsgType`
3. (Client) Display consolidated errors in the table format shown in the mocks

I anticipate this taking **5 days for 1 developer to complete.**


## Details
1. (Server) Implement the `ResponseMessage` interface for each error type defined in the `ResponseMsgType` enum 
In `Element.kt`, instead of creating error/warning strings, instead create a `ResponseMessage` as defined by:

```
enum class ResponseMsgType { NONE, PAYLOAD_SIZE, OPTION, ROUTE_TO, REPORT, MISSING, UNEXPECTED, INVALID_DATE, INVALID_CODE, TRANSLATION }

interface ResponseMessage {
    val type: ResponseMsgType
    fun detailMsg(): String
    fun groupingId(): String {
        return ""
    }
}
``` 
Implementation of the interface above would consist of creating the message template in the `detailMsg()` function. The `groupingId()` method can be used as a key for aggregation of messages. For the example message above regarding invalid dates:
```
data class InvalidDateMessage(
    override val type: ResponseMsgType = ResponseMsgType.INVALID_DATE,
    val formattedValue: String = "",
    val fieldMapping: String = ""
) : ResponseMessage {
    override fun detailMsg() : String {
        return "Invalid date: '$formattedValue' for element $fieldMapping"
    }

    override fun groupingId(): String {
        return fieldMapping
    }

    companion object {
        fun new(formattedValue: String, fieldMapping: String): InvalidDateMessage {
            return InvalidDateMessage(ResponseMsgType.INVALID_DATE, formattedValue, fieldMapping)
        }
    }
}
```
ResultDetail` data class should now change to:
```
data class ResultDetail(val scope: DetailScope, val id: String, val message: ResponseMessage, val row: Int)
```
The `ResponseMessage` allows for the data to more easily be consolidated and the row number will be needed to display to the end user. 

2. (Client) Roll up the error messages by grouping them by `ResponseMsgType`
On the front end (Upload.tsx), the errors will come in as an array of `ResultDetail` detailed above. In order to create the data needed for the table, loop through the errors array tracking unique errors and row numbers. This will look roughly like:
```
let consolidatedErrors = {}; // map of error types to an array of their row numbers
errors.forEach(error => {
  if (consolidatedErrors[error.message.type]) {
    // add row number too existing array
  } else {
    // create new key to track row numbers
}
```
This will create an arrays for each error type that has the full list of rows (for example, [1,3,4,5,8,9,10]. A nice to have is to then simplify even further to [1,3-5,8-10] but this feels like a nice to have, not a must have. 
3. (Client) Display consolidated errors in the table format shown in the mocks
Now that the errors are nicely grouped by error type, they can be displayed in a table where one column is the error message, and the second is the row numbers. Since there could still be a large number of rows to this table and the column lengths could be long, truncation should be the fall back with a "See more" that expands the list.

**Comment by loripusey** [comment]
I definitely like the idea of having the message in one column and then the row numbers in a separate column, as opposed to showing text with the rows embedded. There has been talk (just talk for now) of allowing Senders to edit their file in-place on the website. So, I would hate for us to get into a situation where we have to parse out the column & row numbers from the message in order to figure out which cells they would need to edit. The more we keep the individual pieces of information separate up until we need to display it the more flexible we can be with future feature requests.
