### ISSUE TITLE
Clean CSV Data:  Clear Illness Onset Date Field when Date is Invalid

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#2246]
## Problem Statement
As an **Experity EMR platform user**, the platform does not force me to enter a valid dates so I need the Illness Onset Date value cleared if it is invalid so that this non-essential field does not cause my file to fail.

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a user with Sender permissions
    - Am a Sender who is using the Experity schema
- When I
    - Log into ReportStream
    - Upload a CSV file
- Then 
    - The System, prior to submitting the file to ReportStream for processing, extracts a properly formatted date from a part of a provided data string. E.g. "10/1/2020", "10/1/20", "a week ago". Dates written in words like "a day go" is invalid. Decode only proper dates.
        - If a date cannot be decoded then the field is left blank.
        - If the field is blank then the field is left blank.
        - Refer to the vbScript for more specific criteria: https://drive.google.com/drive/folders/12qqnBP1JCkLXvJBQBatNxgErn8e74FzG     

## Design Considerations
Looks like the data is mostly two of four digit year dates with no extra text.  Can the date mapper handle this conversion?  Other data like "3 days ago" will be ignored/set to blank.

**Comment by carlosfelix2** [comment]
Suggested acceptance criteria:
1. ReportStream is capable of extracting a properly formatted date from a part of a provided data string.  E.g. "test date 10/1/2020".
2. If a date cannot be decoded then the field is left blank.
3. If the field is blank then the field is left blank.

**Comment by sethdarragile6** [comment]
A version of this went to production, but upon review with @rhood23699 and @carlosfelix2 there are a few things that need ironed out

1. A parse error at build time when trying to use the MM/dd/yyyy format (or any format with a / in it). This is a simple fix
2. When using the "MM/dd/yyyy" in the new nullDateValidator, it would seem that some validation occurs upstream from mapper (CsvSerialize, I believe), replacing the name with the value "**^^validationFail**". The new mapper will currently transform that value into an empty string, when it should be validating it. A fix for this will have to somehow circumvent that upstream validation in order to achieve this
3. Closer attention to emulating the OG VBScript is needed. Particularly, some of the examples outlined at the beginning of the DateFormatting() function. The rest of that code may be helpful in manipulating some of those incoming funky dates so that they validate in kotlin.

**Comment by loripusey** [comment]
@sethdarragile6 I'm confused by "a version of this went to production". Was there another related ticket out there?

**Comment by sethdarragile6** [comment]
@loripusey no, no related ticket. what I meant by that was that the code was approved and merged to master (and thus deployable and I _believe_ deployed to production). then, the issues above were discovered while "stage testing" with Rick Hood. Unfortunate, but it doesn't impact anything unless someone actually tries to use this new mapper.

**Comment by rhood23699** [comment]
@loripusey I'll help Seth and Aurora on the issues found.  I apologize.  You were nice enough to create this ticket for me back in September, but I didn't review the AC closely enough, so it doesn't reflect exactly what the existing VBScript is currently doing.  I'll do better in the future.

**Comment by loripusey** [comment]
sounds good, I just wanted to clarify and make sure there was not a related ticket
