### ISSUE TITLE
Add the ability to filter senders to the receiver

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2266]
## Description 
We need the ability to filter the senders a receiver gets. The current plan is to use the quality filters (which are actually jurisdictional filters under the hood) and rely on the `matches`, `doesNotMatch`, and `orEquals` filters to pass in lists of senders that are allowed or are not allowed to go to the receiver's primary feed.

By default ALL receivers will allow `simple_report` through. We will need to ask the sender pipeline and sender tools teams which other senders are allowed through by default, and to which receivers. For example Reddy Family Medical is always sent to LA. Before we can complete this work we will need to have a grid of which sender goes to which receivers.

## Testing process
In order to test this completely we would need to make sure that we send many files through our local Docker container and then compare the outcomes of the ingestion and routing to verify they match our intended outcomes. For example, if I send in a file from `simple_report` that is high quality we would expect that to go to the receiver. But if I send in a lower quality file from `simple_report` will it still route to the secondary feed or will it just not get routed?

We would need to create a synthesized file from Simple Report that we then send in for every sender in our system and confirm that only the ones we have set to allow through go through. We also need to create a low-quality file and send that through as Simple Report to verify that it falls into our secondary feed as we expect. We should also create a persistent set of tests that do this, and run in the command line as part of the smoke tests.

## Acceptance criteria
- All incoming schemas will have a value for the `sender_id` field. This value should be agreed upon by us, the sender pipeline team, and the sender tools team
- The default quality filter in code is changed to use a `matches` jurisdictional filter to check for Simple Report's client id
- Based on the grid identified above, we need to add jurisdictional filters for every receiver that who accepts data from more than just Simple Report (e.g. Louisiana would not use the default filter, but would have a custom one that allows Reddy Family Medical and others to pass through)
- According to the testing process above, we will need to add a new set of tests to the command line test process that will be included in the smoke test feature that sends a battery of files through for different senders and then verifies they go to the correct feed at a receiver.

fysa: @jimduff-usds @Adrian-Brewster @carlosfelix2

**Comment by jimduff-usds** [comment]
I guess my main worry is that the qualityFilter as its designed is already very hard to maintain, and maybe become unmanageable.  Its ease of use depends heavily on most states choosing the default.   If most or all receivers are NOT using the default, we'll need to make several improvements first:
- Particularly, to support this we urgently need the option to sent a default quality filter per organization, so that the secondary feed can simple be the "not" of the organization's primary feed.   Right now, if you hand-craft a quality filter for the primary feed, you then have to hand craft its negative, which given de-morgan's law, can be extremely tricky to get right.  (This is why I invented the "reverseTheQualityFilter" flag - which lets you copy/paste the ascii text of the primary qualityFilter into the secondary qualityFilter, then use reverseTheQualityFilter to say you _really_ want the opposite of that).  
- Then we keep individual feeds qualityFilters, and they get "AND-ed" onto the organization's qualityFilter.
- And we need to move the default qualityFilter out of code, into a global setting.  This is important for testing - we need to be able to modify it per-environment to adequately test.

Other thoughts:

- I don't think I agree with SimpleReport getting a special opt-in.   I suggest we opt-in everyone, then do opt-outs in cases where states definitely say no to a particular sender.   Like what they do with 401k plans these days.

- There's talk of scaling to hundreds or thousands of senders.    And perhaps similar with receivers?   Who's going to maintain this NxM table?    The "opt out if the state requests" approach would help here as well -- hopefully this becomes a sparse matrix, and can be implemented as a more maintainable data structure.   For example, a simple sparse-matrix approach would be to attach to each Sender in the Settings table a list of Organizations who should NOT get its data.

- There are senders which choose not to send to certain receivers (eg, simple report does not send to HHSProtect), and there are receivers that want to opt-out of certain senders.

### Generalization of the Filter principal

Another possible angle here would be to generalize the concept of filter.   To understand this, first remember that there is only one difference right now between jurisdictionFilters and qualityFilters:    the default for jurisdictionalFilters is to allow everything thought (bad!) and the default for qualityFilters is the one hardcoded in the .kt file.   Instead, there should be filter-types.   Start with three filter types:   jurisdictional, quality, and now introducing ... routing type filters, to meet the needs in this proposal.
- each would have a global default. (Set the global juris filter default to "remove everything" to prevent accidents)
- each would have the ability to be overridden at the organization level.  (Obviously the juris filter for states belongs at the Org level!)
- and the organization filter can't be overridden, but can be further AND-ed by receiver and sender level filters.
- The new "routing" filters per this proposal will sit

The pseudo-yaml might look like this:

```
- name: "nj-doh"
  filters: 
    - jurisdictionalFilters:     "orEquals(ordering_facility_state, NJ, patient_state, NJ)"
    - qualityFilters:  "hasAtLeastOneOf(order_test_date,specimen_collection_date_time,test_result_date)"
    - routingzFilters:   doesNotEqual("Bob's Fly By Night Testing Company")
  receivers:
  - name: "elr"
    additionalFilters:
      - jurisdictionalFilter:  "matches(processing_mode_code, P)"
      - qualityFilter:     - "isValidCLIA(testing_lab_clia)"
  - name: "secondary"
    additionalFilters:
      - jurisdictionalFilter:  "matches(processing_mode_code, T)"
      - reverseTheOrganizationFilter: true
```

**Comment by jimduff-usds** [comment]
Proposing to implement support for this in #1244
