### ISSUE TITLE
Mississippi not receiving data from Chickashaw County

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#2361]
MS reached out to ask why they are not receiving data from Chickashaw County School District. @brick-green-agile6 already checked the DB and dont see any data coming in so we are moving upstream to SimpleReport.

**Comment by brick-green-agile6** [comment]
@Adrian-Brewster I got with Tim Niehoff and he did not see any results where the testing facility is "Chickasaw County School District". We did find results from schools in Chickasaw county: Houston Lower Elementary, Houston Upper Elementary, Houston Middle School, Houston High School. Between those school there have been 186 results with 18 positives.

Can you confirm with MS what facility the results that they're missing are being entered under?

**Comment by brick-green-agile6** [comment]
@mlighdc

**Comment by mlighdc** [comment]
@brick-green-agile6 not sure where the issue is but both Leslie and I found test events. Here is the Org External ID. 
MS-CHICKASAW-COUNTY-SCHOOLS-b0e22cee-9ea1-4ab6-a382-ba4c01b50ccf

Let me know if you want to screen share.

**Comment by mlighdc** [comment]
Could there have been a duplicate?

**Comment by brick-green-agile6** [comment]
@mlighdc Tim sent me a list of 181 results from the four schools I listed above. So I don't think that list is what we're looking for. To be able to search for the results I need either the testing lab name or testing lab CLIA.

**Comment by mlighdc** [comment]
@brick-green-agile6 did you mention to Tim what you needed, like the CLIA because we can get that for you? The testing lab name is the school. 

I guess I need to understand what you need. You said there wasn't any test results but there were.

**Comment by mlighdc** [comment]
@Adrian-Brewster I think we can close this ticket. @brick-green-agile6 don't you agree?

Summary:
- Mississippi (MS) was unable to find the school district name (which is the Organization name in SimpleReport) in NBS. That is because Organization name is not map to anything in ReportStream.
- Sent MS an Excel file broken down by the schools in the school district. The total test events for August matched the number of tests the school district said they conducted.
- MS was able to find the test records in NBS by school name.

**Comment by Adrian-Brewster** [comment]
Closing now. Thanks @brick-green-agile6 for your work on this!
