### ISSUE TITLE
Org Switcher Missing from React App

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#2462]

**Comment by kevinhaube** [comment]
The org switcher is showing and visibly working within React now (:tada:), but the implementation is a bit more tricky than that. The calls to our API require an `organization` header. To share this organization choice from the component over to the `ReportsTable` and `FacilitiesTable` would require insane prop piping, OR ... the `useContext()` hook. :sunglasses: The coding of this is going to introduce something in the JSX hierarchy of views that looks like this: `<GlobalStateContext.Provider>` <- this is a wrapper; anything in it can use the context. I chose this instead of a full Redux package because our need for global state is minimal and does not require a full application state management system.
