### ISSUE TITLE
A new user cannot sign into ReportStream 

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#2658]
**Describe the bug**
A new user cannot sign into ReportStream when the user is not provisioned with ReportStream(test) application. 

**Impact**
All users must be given access to ReportStream test to login into ReportStream prod. 

**To Reproduce**

Start with a group like DHaz_phd which only has the ReportStream (prod) app and doesn't have the ReportStream (test) app assigned to it. Open two browser tabs, one for the admin and one for the user. 

In Okta:
1. In Okta logged in as an admin
2. add a new user (associated with the group)

In a user browser
2. User does activation process
3. User browses to reportstream.cdc.gov 
4. User signin in
=> Error: User not associated with app

Back in Okta:
1. add the ReportStream (test) app to the user

Back in the user browser
1. User does a sign-in
=> Successful login

**Expected behavior**
Should be able to sign-in with a group that only has the ReportStream app assigned to it. 

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Additional context**
This happened on the non-React site. 

There is likely a configuration that is missing in the ReportStream prod app. 

## TO DO
- This ticket is for the front-end change

**Comment by sean-usds** [comment]
@RickHawesUSDS @MauriceReeves-usds We had a conversation with the Okta reps yesterday and based on their recommendations here is a solution:

1. (Sean) Change all Okta groups to be linked to both "ReportStream" and "ReportStream (test)". This can be done via the Okta web interface. There are only a few dozen groups so it shouldn't take too long.
2. (@kevinhaube) Change the client code to check for Okta clientId based on env var so that it uses "ReportStream" in production and "ReportStream (test)" for staging and testing

Once these changes are in a new user will only have to be added to an Okta group and they will automatically have access to both staging and production. 

Let me know if there are any objections to this solution!

**Comment by kevinhaube** [comment]
@RickHawesUSDS @MauriceReeves-usds I drafted a PR for you to review alongside the release plan
