### ISSUE TITLE
NJ - Error with OBX-23.1

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2702]
## Problem statement

On 10/20, NJ reported errors in ELR file with issue for OBX-23.1 - field limited to 50 chars
ELR file: covid-19-a42ec627-5954-4db4-ac0f-37be945f2032-20211020131556.hl7

## To do

- Investigate root cause and alert NJ of resolution process

**Comment by anshulkumar-usds** [comment]
@jorg3lopez  I checked with NJ on 11/21 if failed messages need to be resubmitted, and if so, which message IDs. You're cc'ed, so please follow up with NJ to finalize the ticket.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez NJ confirmed no resubmissions are needed as they're fixing the issue manually on their side. So once the fix is in place, please reach out to NJ and ask them for confirmation that it's working on their side.

**Comment by Adrian-Brewster** [comment]
@jorg3lopez Has this fixed been deployed? No resends are necessary.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @mlighdc below are the specimen IDs that seem to have caused the issue because they were over 50 chars:

Specimen ID
---
e84dfc89-b330-4c9e-91b3-06b8544a3bf9
7b673517-fae6-4a78-9f2e-ce163b3836a5
7b17e800-bab7-4fe6-99b4-7213d1f79d2c
a35888e6-89d0-4d16-bc7a-e7f1f30e937d
a09380db-ba4d-4cc7-8c77-11091ba53304
c6dd3e33-ebc3-42eb-8a1e-cccdb52d099c
689b47b3-4a51-408e-a673-90055826a2e2
100df49f-5727-4d66-b9f4-f836d0667d35
05305d94-ce26-4865-bd8d-01a3794b88be
fb5eb17d-d2a9-4a1e-ae3a-9bd90ca5c401
7ed498eb-1705-4bba-a26a-46a71a3505d6
4ab083f4-1103-48a8-9e87-04d2be43a51d
6500e1a9-46c2-405a-96fa-6b826bc8eea4
bc66b331-987d-43b9-9cd3-91d063a8da02
99c1b6e9-3294-4d5c-bfb8-06764ee6ca6a
ee461a1c-7cbf-4c59-b835-fed0c2a8a09e
34b48daf-cffb-46df-a201-ad81ea589011
---
All came from Waterford Township School District-Waterford Elementary School

The batch file where these came from has close to 1700 lines of HL7 code. It would be nice if the receivers could send the message id or specimen id whenever they have failed messages (If they are able to). I will work on this tomorrow, Wednesday (11/24/2021).

**Comment by anshulkumar-usds** [comment]
@jorg3lopez I will commit to ensuring we have message IDs included in all tickets to reduce the investigative burden on your you and other engineers. On this specific issue, what are next steps?

**Comment by jorg3lopez** [comment]
@anshulkumar-usds Thank you, Anshul. Let's confirm NJ has accepted the test file @mlighdc,, and I'll start resending these files.

**Comment by mlighdc** [comment]
@jorg3lopez you may want to connect with @Adrian-Brewster or @anshulkumar-usds. Looks like no resubmissions are needed.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez confirmed that NJ does not expect us to resubmit. So if you're confident the fix is in place and will be sustained in all future deliveries, please close the issue.

**Comment by anshulkumar-usds** [comment]
Dependent on PR from Rick: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3205

Earliest expected deployment on 12/7

**Comment by mlighdc** [comment]
FYI - Got an email back from NJ on 12/7 regarding test file that was sent on 11/24  (test-covid-19-e09a2ed3-9c1e-46da-9458-891e9eae8ca5-20211124191607)

They said the test files processed successfully in their test environment.

**Comment by anshulkumar-usds** [comment]
Given the confirmation noted above from @mlighdc, no further steps needed. Closing.
