### ISSUE TITLE
Concatenate OBX-23.10 onto OBX-23.1

### ISSUE THREAD

**Issue by brick-green-agile6** [CDCgov/prime-reportstream#2709]

**Comment by Adrian-Brewster** [comment]
CDPH wants to have the ability to set a single CLIA per sender.  Primary focus is on SimpleReport but will likely expand to other senders.  EPIs are not able to see the sender name because they only receive a portion of the original message.  OBX is originally in obx23.10 segment but EPIs dont receive that, so they are asking we also include it in 23.1.

**Comment by Adrian-Brewster** [comment]
CDPH is going to test this when they test the centralized CLIA, which has merged and should deploy tomorrow.
