### ISSUE TITLE
VT - MSH-4 contains space as last character

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#2933]
VT is reporting that some namespaces in MSH-4 have a space as the last character. Following up with VT to get message IDs. Need to update the truncation logic to remove the last character if it is a space.

Accession #: 0111d7b2-abba-46db-9e8d-7ac97f8876be
MSH-4: |North Country Union ^47D2240822^CLIA|

Accession #: a214f4aa-7395-4772-8502-c96261290245
MSH-4: |Shelburne Community ^47D2241033^CLIA|

Accession #: c728bbe8-2790-44aa-bdc3-c3c9c5d33606
MSH-4: |Hinesburg Community ^47D2241033^CLIA|

**Comment by jorg3lopez** [comment]
All files above were resent on 11/17/2021. Three files under their Prod/ToVDH folder.
- covid-19-04b239d6-4433-4783-902b-f0a2d14facb3-20211117060200
- covid-19-59a94ee6-dad9-4bf6-8cbe-01d6ce4a592c-20211117053305
- covid-19-2904374a-7c6b-4abf-8ad6-a061ae040ce1-20211117060000

**Comment by mlighdc** [comment]
Thanks for the update @jorg3lopez in regards to the fixes. I will let VT know today and they should see the fixes sometime on Thursday after the production deploy.

**Comment by mlighdc** [comment]
@jorg3lopez can you please look at this one from VT. It just came in

We have encountered messages beginning to fail due to the namespace no longer being truncated. This has so far affected three records from the following facilities:

Accession # a214f4aa-7395-4772-8502-c96261290245
Accession # c728bbe8-2790-44aa-bdc3-c3c9c5d33606
Accession # 0111d7b2-abba-46db-9e8d-7ac97f8876be

Please re-institute the truncation logic for namespace ID for all facilities submitting results through SimpleReport ASAP and re-send these three results, as they are not able to process successfully into our system in the current format. Please let me know when this is complete so I can confirm. 

In the future, please submit a test message for review and approval before implementing any changes to the production feed. Due to the volume of results received through SimpleReport and the time-sensitive nature of these test results, we do not want to risk disruptions caused by untested changes in the production environment.

Please let me know if you need the names of the facilities.

**Comment by mlighdc** [comment]
@jorg3lopez can you send the fix for the trailing space to VT's secondary feed.

> Re: trailing space issue – please send a few example messages with this change in place to the ELR Secondary feed (to our test environment) prior to deploying the code change to production. We have a large volume of senders utilizing this feed and do not want to risk untested code in the production environment.

**Comment by mlighdc** [comment]
@jorg3lopez any update on this issue? I know you were also trying to get back the 20 char truncation, as well as remove the trailing space.

**Comment by mlighdc** [comment]
@jorg3lopez here some test names:

1. less than 20 - High Meadow
2. longer than 20 char - The Vermont Farm and Forest School
3. truncated trailing space (this is 17 char with trailing spaces) - Oxbow High School
4. truncated trailing space (with 19) - brownington central
5. 19 user entering with a trail - "Woodbury Elementary "
6. leading spaces (you will need to create the leading space) - " The Dorset School"

**Comment by jorg3lopez** [comment]
Uploaded test file to VTs test feed.

**Comment by mlighdc** [comment]
@anshulkumar-usds @jorg3lopez I have not heard any feedback from VT. Please do not push changes to production for VT until they had a chance to review the test files and given us their feedback. Thanks.

**Comment by jorg3lopez** [comment]
PR waiting review and approval. It will probably go into production by Tuesday, next week (11/30/2201); unless there is a deployment on Thanksgiving Day.

**Comment by mlighdc** [comment]
@jorg3lopez as mentioned in the Slack message, please do not deploy on Thanksgiving or this week until we hear back from VT. cc- @MauriceReeves-usds 

Sent a message to VT on 11/23 to let them know we delivered two test files for them to review. Also communicate that we are targeting all updates to be in production by 11/30. Would be this ticket and [2881](https://github.com/CDCgov/prime-reportstream/issues/2881).

Awaiting their review and feedback.

**Comment by mlighdc** [comment]
@jorg3lopez the changes that were made caused the leading 0 in the zip code to be dropped. Please investigate what happened and correct. VT does not want the updates to go into production until the zip code issue is resolved. The zip code issue will cause a big issue for them as it will caused all messages to fail.

**Comment by jorg3lopez** [comment]
@mlighdc @anshulkumar-usds File uploaded to their test feed on 2021-11-30. File name: 
test-20211130-covid-19-61e77aa7-596a-45db-8636-f0f52adf7387-20211130205405

**Comment by anshulkumar-usds** [comment]
VT confirmed on 12/1 that test file fixes the issue. Resubmission for effected files in prod will be tracked here:
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3267

Closing this.
