### ISSUE TITLE
Update Date Validation to Handle Additional Scenarios

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3081]
## Problem Statement
We created a custom mapper to handle dates that come from a Sender submission as a string:
https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2246
However, what we didn't know was that the CSV Serializer was doing date validation based on the field being typed as a date (often from the base COVID schema) before the custom mapper would run, thereby, nullifying the effects of the new mapper.

## Acceptance Criteria
- Remove the custom mapper that was created as part of this ticket:
https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/2246
- Enhance the checkForError/toNormalized method to handle the DATE and DATETIME Element type normalization to include the following formats
    - "2008-09-05 0:00:00.000"
    - "2008-09-30 03:00 PM"   
        - NOTE: have received both AM and PM
    - "8/1/2021 1:17:01 PM"   
        - NOTE: have received both AM and PM
    - "8/1/2021 13:00"
    - "20210101"
    - "01012021"
    - "01/01/2021" and "1/1/2021"
    - "01-01-2021" and "1-1-2021"    

## Notes
- What does Simple Report use for date validation?
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/f4b533cc-c77c-436e-9ffc-719de9171fda)

**Comment by ahay-agile6** [comment]
reference back to this ticket for context
https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3056

there are also attachments that will help debug/test the issue

**Comment by ahay-agile6** [comment]
i changed the pointing for this story to a `13` because:
1. the architecture of the application is not conducive to make changes in the area where this was needed. it was complex to navigate and write reusable/clean code 
2. code that was put in before a few of the building actions were put in place does not pass the build requirements now - so i had to refactor a lot of code that i did not write to pass the build
3. local development builds were botched by pulling in `master` and attempting to rebuild the application... _**constantly**_
