### ISSUE TITLE
MA - OBX.24 of type OBX.24.XAD Missing

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3134]
An issue came in (11/19/21) from MA about missing OBX.24 of type OBX.24.XAD

> Error: Performing Organization Address (OBX.24 of type OBX.24.XAD) field is missing.
> Message rejected.

Please review, edit, and resubmit as necessary

**Comment by anshulkumar-usds** [comment]
MA delivered sample messages that contains PII in secure mail. Check with Anshul for this info.

**Comment by anshulkumar-usds** [comment]
MA reported similar issue on 11/23 via secure email:

In today’s file there was an error due to a missing OBX.24 section.  Can you please review, edit, and resubmit as necessary.

MSH|^~\&|CDC PRIME - Atlanta, Georgia (Dekalb)^2.16.840.1.114222.4.1.237821^ISO|None^39D0701535^CLIA|MA-MDPH^2.16.840.1.113883.19.3.2^ISO|MA-MDPH^2.16.840.1.113883.19.3.2^ISO|20211123141539.3802+0000||ORU^R01^ORU_R01|758361|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO

SPM|1|758361&None&39D0701535&CLIA^binax_0a282562e2c8335c61765d6cadb356cd&None&39D0701535&CLIA||258500001^Nasopharyngeal swab^SCT^^^^2.67|||||||||||||202111220901-0600|20211122090106.0000-0600

Error: Performing Organization Address (OBX.24 of type OBX.24.XAD) field is missing.

Message rejected.

**Comment by anshulkumar-usds** [comment]
@hermanAlexCordero can you try taking a look at this one. Haven't seen this before from MA or another state recently.

**Comment by hermanAlexCordero** [comment]
Missing testing lab schema entries
Added schema entries and tested 
Will create a pull request to update schema entries.

**Comment by anshulkumar-usds** [comment]
@hermanAlexCordero could you please update in the status of the PR?

**Comment by Adrian-Brewster** [comment]
Herman needs to recreate PR and wants to include ticket 3287.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @mlighdc I emailed Becky letting her know that we are working on a fix for the OBX-24 issue. It seems that the test file that I sent to them on 11-24-2021 had the same issue as well. Once we fix this issue, I will resend the same file. Once they approve the changes, I will resend all the files that have failed in the past.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez to review next steps

**Comment by anshulkumar-usds** [comment]
@jorg3lopez MA requested following messages to be resent after fixing OBX-24:
767294
740086
758361
778515
818558

**Comment by jorg3lopez** [comment]
@anshulkumar-usds Fix is in master as of today (12/27).

**Comment by jorg3lopez** [comment]
> @jorg3lopez MA requested following messages to be resent after fixing OBX-24: 767294 740086 758361 778515 818558 926925

@anshulkumar-usds Ok, I will get on it.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds Test results with below specimen_ids have been sent today 12-28-2021,  in two files to MA.
- speciment_id:
  * 767294
  * 740086
  * 758361
  * 778515
  * 818558
  * 926925

- File name:
   * prime-20211228213300
   * prime-20211228213400

**Comment by anshulkumar-usds** [comment]
MA accepted files.
