### ISSUE TITLE
Update Live States on SVG Map

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3251]
## Problem Statement
As ReportStream Product, we need to keep our map of live states up-to-date so that we communicate the state of our application to our current and prospective users and other stakeholders.

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/b2c1d406-eb24-44b4-b53b-194e3911f53c)

**Comment by loripusey** [comment]
@anshulkumar-usds @drew-usds @sean-usds I created this Epic with a story for each sprint for us to update the "Live" map in RS. We can evaluate at Sprint Planning if there are new states to add, based on the tracking spreadsheet, and pull in the story if there are new ones to add. If not, we can close the ticket for that sprint.
cc: @rachelhanster

**Comment by HeatherRienks** [comment]
@BerniXiongA6 - I think we can prob close this Epic since we have now defined the process ([noted here](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/doc2.aspx?sourcedoc=%7B9640218C-586E-42B0-9FCC-0324D8C7B4F5%7D&file=Update%20SVG%20Map%20and%20List%20Process.docx&action=default&mobileredirect=true&cid=3eaf4dd2-134b-45ee-bb71-55e2de84a5d8)) for updating the SVG map for states who have gone live, but wanted your feedback first since this ticket is on both or our boards. 

cc: @brandonnava

**Comment by BerniXiongA6** [comment]
I agree!

**Comment by LaFreda1** [comment]
Closing sue to changes in map update tickets
