### ISSUE TITLE
VT - Invalid Value in OBX-15.3 (Producer’s Reference/Name of Coding System)

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3267]
VT reported an issue where all test results from SimpleReport received around 3:15 pm Eastern on 11/30 were failing HL7 validation due to an invalid value in OBX-15.3 (Producer’s Reference/Name of Coding System). 

The value they are receiving is “CLIA”, which is not a valid value for this field defined in the HL70396 table. In files received prior to 3:15 pm today, OBX-15.3 was being left blank and the messages were processing successfully.

**Comment by mlighdc** [comment]
@jorg3lopez put some sample resend messages in VT's test feed. I informed VT test files were ready for review. Awaiting approval to resend the batch of test results.

Jorge, please use this ticket for updates related to the resends for OBX-15.3 issue.

**Comment by jorg3lopez** [comment]
OBX-15-3 has been suppressed.

**Comment by anshulkumar-usds** [comment]
@jorg3lopez VT has validated the test messages. So please resubmit the messages to their prod directory.

**Comment by mlighdc** [comment]
@jorg3lopez let us know when all the files in  3:15 pm batch and when the fix was put into place and working have been resent so we can let VT know. You may need to double check how often we sent files to VT to make sure we don't miss anything. Thanks.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @mlighdc I have located all the files that failed due to OBX-15-3.  Do you want me to send one of the files to their test feed first for approval?

**Comment by anshulkumar-usds** [comment]
@jorg3lopez yes please, and share the file name here in comments so I can follow up with VT.

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @mlighdc I uploaded all the files that failed due to OBX-15-3. I also uploaded the file that they accepted in their test feed. All files were uploaded to their prod folder. 
Files:
covid-19-61e77aa7-596a-45db-8636-f0f52adf7387-20211130205405
covid-19-9b58f7bd-fc34-44ba-9ff7-e1f445730c49-20211206234000
covid-19-40c9a8f8-2401-4dc5-aa80-6c75f90be4ee-20211206233901
covid-19-988aacb2-5d70-49a7-9ec2-1d2ed45bfec7-20211206233504
covid-19-cdafd608-3c84-4855-8727-9ed5ad5a2fe8-20211206234000
covid-19-fea642c8-9640-4db5-8050-e2cea82a1586-20211206233901

I will email Theresa to let her know.
