### ISSUE TITLE
[On Hold] Bump react-router-dom to 6.x

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3281]
Re https://github.com/CDCgov/prime-reportstream/pull/3152

This will require:
- Convert usage of react-router-dom components according to v5 -> v6 guide
- Ensure all dependencies are updated and support v6 if they use react-router-dom components. Currently an @okta library is incompatible with react-router-dom^6.0.x

**Comment by kevinhaube** [comment]
Update as of March 25, 2022:  `@okta/okta-react` and other blockers have updated to use `react-router-dom` v6, but we still encounter issues due to our application's implementation being heavily biased towards the v5 method. When attempting to swap over to v6, the lift is much heavier than is worth the time. 

I advise we follow `react-router`'s own advice and wait for backwards compatibility to ship so we can make incremental improvements over time to how our app's routing is structured without taking up a hefty chunk of a sprint (or two) to do it. 

See: https://reactrouter.com/docs/en/v6/upgrading/v5#backwards-compatibility-package

**Comment by bgantick** [comment]
This work has been completed
