### ISSUE TITLE
Find Cohort 2 Participants for CSV Pilot (PHD Discovery Calls)

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3288]
## Problem Statement
As the Experience Team, we need to find some participants for Cohort 2 for the CSV Uploader Pilot so that we can conduct round 2 of the pilot.

## Notes
Please refer to this spreadsheet for documentation
https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B5C057B81-BEDB-4FE0-941D-A519206701A2%7D&file=Data%20sharing%20pilot_csv_cohorts.xlsx&action=default&mobileredirect=true&cid=b0966aa0-d529-426d-97e1-5649d772cd90

**Comment by victorialb-usds** [comment]
Criteria as per conversation with Kevin T. prior to VT call on 12.1.21
(1) eager and will be responsive [wants to engage in co-design]
(2) not under a fixed deadline of STLT to get off other system
(3) for COVID-only reporters [not sure what this means fully]

VLB reflection on this 12/2/21
Other considerations so we have data that will help us understand broader set of needs in order to scale
- Rural versus urban
- Serves low ses pop
- tribal clinic 
- high v low tech

**Comment by loripusey** [comment]
@victorialb-usds @rachelhanster I'll add these criteria to the slide deck and add the other considerations somewhere as well.
