### ISSUE TITLE
Stop batch and send functions during deploys

### ISSUE THREAD

**Issue by cwinters-usds** [CDCgov/prime-reportstream#3385]
At the start of a deploy disable the batch and send function.

When a deploy is complete, enable the batch and send function. If possible we should ensure this step runs even if the deploy failed.

**Comment by JosiahSiegel** [comment]
[Disable a function](https://docs.microsoft.com/en-us/azure/azure-functions/disable-function?tabs=azurecli#disable-a-function)
```sh
az functionapp config appsettings set --name pdhtest-functionapp \
--resource-group prime-data-hub-test \
--settings AzureWebJobs.batch.Disabled=true
```
![image](https://user-images.githubusercontent.com/5522990/166291808-0e4d8a67-a4cf-42a1-b017-b2ea599ec8c0.png)

Re-enable
```sh
az functionapp config appsettings set --name pdhtest-functionapp \
--resource-group prime-data-hub-test \
--settings AzureWebJobs.batch.Disabled=false
```
![image](https://user-images.githubusercontent.com/5522990/166291880-e04b3e7e-61b4-463a-af30-e807c4c28eea.png)

Note: By default, app settings also apply to apps running in deployment slots.

**Comment by JosiahSiegel** [comment]
No longer needed.
  * [Carlos Felix](https://semanticbits.slack.com/archives/C01HFHPNJEL/p1651670050627429?thread_ts=1651668609.536919&cid=C01HFHPNJEL)
  Note that on of the primary reasons was to disable it due to the problems we get when deploying schema changes, but that has been fixed.  Not sure what other use cases this has right now.

If needs to be re-created, action [JosiahSiegel/disable-azure-function](https://github.com/JosiahSiegel/disable-azure-function) is available.
