### ISSUE TITLE
Add test_correction_reason to COVID-19 schema and SR schema

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3432]
Per CDCGov/prime-simplereport#2913, we need to add a field for the `test_correction_reason` to a covid-19 schema and the simple report schema. It should be a text field, and it should probably be marked as PII because it's possible that it could contain information that refers to the patient.

Once we are receiving this field, it should go into the `NTE` segment in the HL7 document.

FYSA: @anshulkumar-usds @Adrian-Brewster @LGFranklin @zdeveloper

**Comment by brick-green-agile6** [comment]
In the COVID-19 schema there are fields for comments that map to NTE: 
![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/e2e3aa65-db5e-43b8-b28d-28188f31d10a)

Those fields are not currently available in the simple report schema. I propose that we make them available rather than build out a new field. This solves multiple potential issues. If we were to add test_correction_reason today then down the road added comment, we would have to adjust the hl7serializer code to append the values in the NTE segment creation otherwise one would overwrite the other. Also, any subject can be described in the "comment" field so it's multi-use whereas test_correction_reason has a specific use case. 

@MauriceReeves-usds any objection to adding the comment fields to the simple report schema rather than test_correction_reason?

**Comment by anshulkumar-usds** [comment]
Not merged in yet; awaiting until 1/25/22

**Comment by brick-green-agile6** [comment]
the PR was merged. Ready for the 1/25 deployment.

**Comment by brick-green-agile6** [comment]
deployed to production. Need to confirm functionality with SR.

**Comment by Adrian-Brewster** [comment]
@LGFranklin can you confirm functionality on the SR side?  Brick commented on 2913 to see what the next steps are. Thanks!

**Comment by anshulkumar-usds** [comment]
@LGFranklin can you please share an update?

**Comment by anshulkumar-usds** [comment]
I'll wait until @brick-green-agile6 is back so he may review. Thanks everyone for helping.

**Comment by brick-green-agile6** [comment]
Can confirm this is working. The states are receiving the data in the comment as expected although the X is causing errors. @anshulkumar-usds Can we close this or do we need to move to external review?
