### ISSUE TITLE
MINI DESIGN SPRINT - Display Messages for Senders in Simple Language with Actionable Next Steps

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3574]
## NOTE
We will wait until we have gathered feedback on the clickable prototypes for the Submission History feature before looking at having this mini design sprint.

## Problem Statement
As a Sender, I need to understand all of the messages that reportStream is telling me so that I can take the required next steps to get my data to my PHD(s).

## Open Questions
- When are the quality filter message available to us to display
    - Can we display the quality filter messages along with warnings immediately after upload?

## Acceptance Criteria
Assuming we have access to display the quality filter messages, design how best to display errors, warning, & PHD quality filter messages, so that Senders understand messages, review dataset, make edits, and resubmit dataset.

Design sprint will be to get enough information to move forward with a design story.

## Considerations:
Context: https://usds.slack.com/archives/C02HJ43AE8Z/p1640121538425000
- [ ] content edits
- [ ] design edits

**Comment by loripusey** [comment]
@drew-usds @inkandsound Rachel and I pulled this into the current sprint; Rachel will touch base with you on Thursday

**Comment by victorialb-usds** [comment]
Noting sounds like there will be a meeting to discuss this. Also Louisiana PHD mentioned they have some language that they use that they will share that might provide an idea for us. They described in terms of tiers. They said they would send it to us in a call we had with them on 12/22/21

**Comment by rachelhanster** [comment]
@drew-usds and I met. Dawn is OOO today.
Drew to connect w/ @jimduff-usds 
Drew to share info w/ @inkandsound, so she is set up for success upon return on Monday to start this.
Thanks all!

**Comment by inkandsound** [comment]
A couple drafts of different ways to handle this are in the main ReportStream Figma here: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=1746%3A5889

Look for "Upload - user feedback revisions + messages" in Sender 3.0.

To make this less confusing for users, I think the UI should handle errors, warnings, and data quality filters in the same way - this is based on feedback from our user test. (There are some other changes in this design to reflect the user test as well, like how "validate" didn't make sense to her as a discrete process.) 

For v2, the idea is that we would display some rows/columns that contain the error/warning/quality filter that they're bumping into so they have an immediate visual for comparison to our error message. The easiest version to implement would still have them upload a totally new, corrected CSV file rather than trying to have the UI allow them to edit in the app.

Language is all placeholder/draft.

@drew-usds you can take over from here or we can discuss as a team when I'm back on Monday. @rachelhanster

**Comment by loripusey** [comment]
@BerniXiongA6 welcome email has "Centers for Disease and Control", should be "Centers for Disease Control and Prevention"

**Comment by loripusey** [comment]
We will wait until we have gathered feedback on the clickable prototypes for the Submission History feature before looking at having this mini design sprint.

**Comment by loripusey** [comment]
@drew-usds @inkandsound I'm going to go ahead and close this ticket since it has been out there for over a month and nothing is happening with it right now; we can re-open later if there is work to do
cc: @rachelhanster
