### ISSUE TITLE
Std CSV - Testing in Staging / O&O Team

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3598]
**Description:**
Complete testing of all requirements and scenarios defined in the document "CSV-StandardFileFormatAndNotes-v2.docs".

**Main Objectives & Tasks:**
- [ ] Validate all requirements and scenarios and make all necessary changes.

**Comment by rhood23699** [comment]
The staging yaml along with the standard CSV schema is targeted for deployed on Thursday, Dec 30th.

**Comment by rhood23699** [comment]
Deployment should be done Tuesday, 1/4/21.

**Comment by rhood23699** [comment]
Changed the name because YAML definition is built and moved to Staging while Building the Schema.  The new purpose of this ticket is to track the O&O Teams progress on testing all requirements and scenarios defined in the requirement document "CSV-StandardFileFormatAndNotes-v2.docs".

**Comment by rhood23699** [comment]
This should start today.

**Comment by rhood23699** [comment]
Added the OKTA group DHSender_manualupload and assigned myself to the group.  Sent a test file and it worked.  I'll begin testing all requirements and scenarios tomorrow.

**Comment by rhood23699** [comment]
Aurora found a potential problem with our logic to use one schema and retain the ability to identify each Sender.  Our logic may break the Submitter History API, so Mo, David Gage, Aurora and I have a meeting tomorrow to review resolutions.

**Comment by rhood23699** [comment]
1/5/21 - Meeting with David Gage, Aurora, Mo, Rick Hood and Lori to discuss the problem with using one OKTA group and for all Std CSV Senders. Aurora was correct.  Our logic works, but Submitter History will not work properly because all Senders will be under the same "manualupload" Sending Org.  Mo is researching potential resolutions with David Gage and will have discussion with the Simple Report engineers to make sure his ideas on resolution will not affect Simple Report.  @loripusey has created another EPIC to track this issue.

In the meantime, we'll revert back to using "sub-schemas" and setting up an OKTA group per Sender.

**Comment by rhood23699** [comment]
I'll complete the schema and YAML changes needed for moving from a single OKTA account for all CSV Senders to OKTA accounts for each Sender.  This changes will be ready for the Tuesday, 1/11/2021 deployment.

**Comment by rhood23699** [comment]
The schema and YAML changes are in-place in Staging.  @loripusey I'm testing, but any help testing from the Experience Team would be helpful.
