### ISSUE TITLE
IL - Missing LOINC Codes

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3783]
**Describe the bug**
Illinois reporting missing LOINC codes. These files need to be corrected and resent. There are over 100 different instances from two SimpleReport Facilities: Vernon Hills and Villa Park 

**Impact**
 Because of this, they are unable to determine what tests are being used. 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/4c75c3da-9486-44aa-aa0b-e65203d10559)

**Comment by anshulkumar-usds** [comment]
@timothybest-usds the messages stated above originated from SR. 

3b7cb8b7-0346-424a-961a-219b76463b23: Equipment name = BD Veritor System for Rapid Detection of SARS-CoV-2*
fb313e06-a477-4537-9924-98a1cd827472: Equipment name = BD Veritor System for Rapid Detection

Can you please verify if the above equipment aligns with the latest LIVD mappers. I suspect the LOINCs  were blanked because there is a mismatch. SR will also need to resubmit these records.

**Comment by anshulkumar-usds** [comment]
Anshul checking with IL to get full list of impacted message IDs for resubmission.

**Comment by anshulkumar-usds** [comment]
@zdeveloper I reached out to Tim on this, but I think he's ooo. Can you please resubmit these for IL? They are from SR.

**Comment by anshulkumar-usds** [comment]
@zdeveloper can you please take a look at these?

**Comment by zdeveloper** [comment]
Done, resent 136 events
