### ISSUE TITLE
[Design] Receivers: Add paging functionality to list of reporting facilities on daily data report details page

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#3795]
## Problem Statement
As a public health department employee, I want to easily understand who sent in data and associated descriptive metadata.

## Acceptance criteria
- On daily data page, I click an individual report ID, I see list of reporting facilities in a table
- Table is paginated

## Assumptions
- Back end is already done

## Design
- Page design is similar to [senders' submission history](https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=2513%3A22007), with "number of records per page 25 50 100" on the lower left hand side and "previous" "next" on the right hand side.

**Comment by drew-usds** [comment]
@inkandsound can you connect with @bgantick here on the design/Figma front?

We can probably use a lot of what we already did/are currently working on for submission history, but there may be something specific for Receivers that we need to account for. Since this is the second time pagination/sorting/filtering is coming up, this could be the start of a more standardized set of things we expect to see when there is a table view of _anything_ in RS.
