### ISSUE TITLE
Display 1 Entry Per CSV File Successfully Submitted (i.e. Filter out Errors)

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3886]
## Problem Statement
Currently, all actions are shown in the submission history, which will be very confusing for Senders.  Senders want to see one entry per CSV file that they successfully uploaded.

## Acceptance Criteria
- Given I
    - Am logged into ReportStream as a Sender OR RS Prime Admin
- When I
    - Choose to view my submission history (or for any Sender when Primary Admin)
- Then I
    - See 1 entry per CSV file that I successfully uploaded (i.e. remove submissions that produced errors)

**Comment by TomNUSDS** [comment]
Submission history server-side does not support dynamic filtering.

Options: 
1. Remove entries on client
   Pros: no server changes, easy/quick to do.
   Cons: because this list is paged, the page sizes can vary in length as items are removed. If the ratio of removed items approaches the page size, empty pages could be an issue.
2. Modify current API to **_always_** filter out errors.
  Pros: Relatively easy server side change.
  Cons: More work than Option 1. Will impact other users of the API and needs more through review since we don't want break API calls others may be using.
3. Add filtering parameters/support to API call.
  Pros: This is where we eventually want to get. Can be done in way to not break backward compatibility.
   Cons: A LOT more work than other options. New code to process filters and filter results. API change but in compatible way, but still needs more regression tests, etc. Longer to implement.

**Comment by TomNUSDS** [comment]
Related to work https://github.com/cdcgov/prime-reportstream/issues/1556
