### ISSUE TITLE
Create a New Slide in the CSV Dataset & Quality Improvements Slide Deck for Synthesis of Discovery Calls

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3896]
## Problem Statement
As the Experience Team, we need to document our findings from the recent discovery calls with receivers/states so that we can share the findings with all ReportStream team members.

## Acceptance Criteria
Please create a new slide in the [CSV Dataset & Quality Improvements Slide Deck](https://cdc.sharepoint.com/:p:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7BDE566704-B7F3-4B2E-9EAA-332B8FE7CD0B%7D&file=ReportStream%20CSV%20dataset%20and%20quality%20improvements.pptx&action=edit&mobileredirect=true) to document the synthesis from all recent receivers/states discovery calls.

**Comment by rachelhanster** [comment]
@victorialb-usds I created slides 15, 16, 17 in the csv deck and added some content, particularly slide 15 and 17. I'll let you take it from here and then we can regroup.

**Comment by victorialb-usds** [comment]
@rachelhanster I added data to the slides and needed to add some. You can edit as you need to craft your narrative.

**Comment by victorialb-usds** [comment]
See [here ](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B538209E2-77EF-408D-9E1B-B30D4B3C66BD%7D&file=Cumulative%20Errors%20CSV%20pilot%20Cohort%201.xlsx&action=default&mobileredirect=true&cid=f59cc669-f52f-49db-8dbb-09419477629b)for the error data. 
[Here ](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B431D9FDE-C408-43E7-B643-E1D30652155C%7D&file=CSV%20pilot%20cohort%201_Pre%20Post%20Data.xlsx&action=default&mobileredirect=true) for the pre post data. - Time saved is not clear. Data suggest time is being saved not in the unique uploading experience unless they were doing  a manual entry or SR like entry. Or they would be forced back to doing that as the places where they were reporting to were sunsetting their provider portals. Most users were doing CSV upload before and they commented that it was easy for them because they had done it before. The lower tech folks at COVID clinic struggled more with meeting the specs and that perhaps shows in the number of error messages.
