### ISSUE TITLE
BUG - Store pagination results for submission history

### ISSUE THREAD

**Issue by sean-usds** [CDCgov/prime-reportstream#3906]
## Problem Statement
While paginating back and forth through submission history, results are re-fetched every time

## Acceptance criteria
- When navigating to "Next" and then back to "Previous" the results should be stored and not refetched (react caching)

**Comment by TomNUSDS** [comment]
This problem is directly related to how we do cursor-based navigation of lists and it not easily fixed without a redesign.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/74203452/152427584-df40e491-e9cb-4b8a-95da-18bbf8ad2ad2.png">

If you look at the urls used when navigating, they are different when doing a `Prev` and therefore cannot be cached at the network layer. 

Potential solutions:
 - Use actual pagination versus cursors
 - UI can use an "ever scroll"
 
@loripusey  I don't think we can easily fix this bug, but I also don't think we should close it because it's not fixed. Maybe just move into the backlog.

I also found a couple of other related issues (#4196 and #4144  (4144 is now fixed).

**Comment by rachelhanster** [comment]
Ticket moving to simplereport for its product backlog consideration

**Comment by TomNUSDS** [comment]
I'm not sure I understand why this was moved to SimpleReport. This is a generic engineering issue related to performance and caching. 

@kevinhaube might have some input on this issue since he refactored the list loading logic.

Maybe the performance can be improved with pre-featching api for the next page.

**Comment by kevinhaube** [comment]
Right now, as of the pagination behavior working fully in ascending and descending order (#5127) the calls are default cached by the browser, so paging back and forth will result in no re-fetching (i.e. no loading spinner). There are two ways to break this:

1. The browser invalidates the cache based on its default cache settings
2. The user refreshes the single-page application, resetting the browser cache

**Comment by TomNUSDS** [comment]
Based on @kevinhaube, I think we can just close this bug. The next big win will probably be from gzipping the api response.
