### ISSUE TITLE
Display Quality Filter Messages as Errors on CSV Upload

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#3922]
## Problem statement
As a Sender, when I submit a CSV file, I would like for my data to be validated and, if there are errors, I would like the opportunity to fix the data and then re-submit.

## Acceptance criteria
- Given I
    - Logged into ReportStream as a user with Sender permissions
- When I
    - Navigate to the new Upload page
    - Choose a file to upload (i.e. browse or drag/drop) 
    - Submit the file that has certain quality filter messages returned
- Then 
   - If the file has **ANY** quality filter messages 
       - I see the quality filter messages, along with any errors, listed in order by rows affected
   - If the file has jurisdictional, routing, or processing mode filters 
       - I DO NOT see these types of filter messages (i.e. they are ignored)

## To do
- [ ] Dev:

**Comment by rachelhanster** [comment]
Current API output per @sethdarragile6 is below. We need to consider a few factors:

1. These messages can be improved. What's the best way to improve "oh-doh.elr." "ohio11," and "for filter..." so it's more plain language and actionable for users? What happens if data needs to be sent to multiple public health authorities?
2. What's the minimum we can do while Uploader gets transitioned to simplereport?
3. Useful enough for users, for the next 3 months, April to June?

"For oh-doh.elr, filter isValidCLIA[testing_lab_clia, reporting_facility_clia] filtered out item Ohio12",
                "For oh-doh.elr, filter isValidCLIA[testing_lab_clia, reporting_facility_clia] filtered out item Ohio11",
                "For oh-doh.elr, filter hasAtLeastOneOf[order_test_date, specimen_collection_date_time, test_result_date] filtered out item Ohio11",
                "For oh-doh.elr, filter hasValidDataFor[patient_dob] filtered out item Ohio12",
                "For oh-doh.elr, filter hasValidDataFor[patient_dob] filtered out item Ohio11",
                "For oh-doh.elr, filter isValidCLIA[testing_lab_clia, reporting_facility_clia] filtered out item Ohio12",
                "For oh-doh.elr, filter isValidCLIA[testing_lab_clia, reporting_facility_clia] filtered out item Ohio11",
                "For oh-doh.elr, filter hasAtLeastOneOf[order_test_date, specimen_collection_date_time, test_result_date] filtered out item Ohio11",
                "For oh-doh.elr, filter hasValidDataFor[patient_dob] filtered out item Ohio12",
                "For oh-doh.elr, filter hasValidDataFor[patient_dob] filtered out item Ohio11"

**Comment by sethdarragile6** [comment]
@rachelhanster @jimduff-usds sorry about the confusion over [my slack post](https://agilesix.slack.com/archives/C02HJ43AE8Z/p1649109573262459), I didn't mean to suggest that those existing messages were what I was going with, necessarily- just that that's all we had at the moment. This confused Kevin as well, and so I followed up with an example of what Jim just posted above. Basically I was just trying to start the conversation around this, and I did that poorly. My apologies.

But now we're here, and we're having a conversation! Great! 👍 Perhaps Jim can help flesh out what's possible here as well, as I haven't deeply dug into it yet. (still trying to get the backend part of this out the door - #2091)

My initial thoughts are to employ a simple helper method in the front end for this, at least in the short term, but long term probably some sort of lookup table containing more human readable elements of some of this stuff. Because my questions right now are in line with Rachel's #1 from above, on how/where we can currently pull some of this information. 

I know I can get the actual name of the org via the settings API, so I think something like 'oh-doh.elr' can be mitigated (although we might want to try adding that to the API response, otherwise another call from the front end will be needed). 'Ohio12' from above is actually just the last name, so a "real world" example here might be ok. As far as the filter name is concerned. Transforming the filterName into something less geeky is different story. I'm not sure (yet) if there is any metadata I can programmatically access to grab a human readable version of something like "isValidCLIA", so a first deliverable pass of this might just need to do all that transformation in the front end- and just accept that this will be a maintenance item should we add a new quality filter type. Thoughts, Jim?

**Comment by sethdarragile6** [comment]
@HeatherRienks it was decided that this story and #2091 were to be pulled out when it became apparent that there was no clean way to submit and then reject a file with quality filter messages without leaving a trace of the report within the system- which could lead to confusing artifacts in the UI, as well as the accidental transmission of said report. After discussing the situation with Jim and Brian, Jim created [a new story](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5058) on the pipeline backlog to address this lack of clean validation, with the ultimate goal to create a "validation service" that would be more useful to hand off to the SimpleReport team when CSV Upload is transitioned over to them.

**Comment by bgantick** [comment]
Closing per https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3557#issuecomment-1091729391
