### ISSUE TITLE
NM - Validate PMG test files

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#3943]
Work with NM to validate sample test files from PMG

**Comment by anshulkumar-usds** [comment]
@jbiskie noted timeout errors when attempting to deliver files to NM SFTP. 

NM now checking internally on this issues, and the need to whitelist IP address from CDC.

**Comment by jbiskie** [comment]
Checking to see if we can send the files to NM via secure email.

**Comment by anshulkumar-usds** [comment]
Files delivered to NM after getting IP whitelisted

**Comment by Adrian-Brewster** [comment]
Heard back from NM. PMG had some changes to make. Changes made last week and PMG sent over new test files.  @jbiskie Will forward to NM this week.

**Comment by Adrian-Brewster** [comment]
Second batch was sent to NM. NM is having contract issues with the contractor who handles these.  Joel notified PMG.  Hoping to check in today to see if we can make more progress on this.

**Comment by BerniXiongA6** [comment]
8/1: @sarahnw will look into and flesh out details

**Comment by jbiskie** [comment]
We had to put PMG on hold for NM because of contract issues between NM and their vendor, Syncronys. These have been resolved, so they are ready to start validating again.

This is the latest from David at Syncronys, and it appears they have just 1 potential issue in the file. No feedback yet from Pear on how this looks in NMEDSS.

-------
We’re back working on onboarding! I ran an analysis of the file you sent and found the following:

Examined files PREMIERMG-Lab-TEST-20220216-PREMIER-ELR-TEST-20220215222701.hl7 through

PREMIERMG-Lab-TEST-20220216-PREMIER-ELR-TEST-20220215222701.hl7

There were 9 messages.

                OBX.18.1 is type EI and is missing required subfields. The (sub)Field contains BD Veritor Plus System_Becton Dickinson^^MNI for 9 segments. Example ControlIDs: b5000c0b-5030-4847-96d1-9c07ff6fcfe2, 22353370-d50b-46d7-96cd-5e1bd7ebfeac

As you can see, the only issue from a structural perspective is the OBX.18. I’ve asked Pear at NMDOH to try running it into their NMEDSS system to see if this causes a problem for them. If so, it’ll need to be fixed.
------

On the notes above regarding whitelisting - they wanted us to send the test files to their sFTP and whitelisted my IP to allow that to happen. If you need to send more test files to them, I may have to do the upload since my IP is the one that they've whitelisted other than our production environment. (Presuming my IP hasn't changed in the last 7 months!)

**Comment by BerniXiongA6** [comment]
Hi @jbiskie -- @sarahnw says this would be a good ticket for you to continue on now that you're back. Let us know if you have any questions!

**Comment by jbiskie** [comment]
NM has validated and is ready for data. I emailed PMG to coordinate a date/time to turn on the feed to NM.

**Comment by jbiskie** [comment]
NM is ready. Contact made with PMG to turn on NM as soon as they're ready.

*Also sent list of new + in progress states to PMG per their request.

**Comment by jbiskie** [comment]
PMG feed to NM is turned on as of 9/12/22.

**Comment by shy2cdc** [comment]
@jbiskie Email from David today:

Hi Joel,

I can’t find any Premier files in the feed. Have you actually sent anything?
