### ISSUE TITLE
MA - Performing Org Address Format Issues

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4032]
On 1/26, MA reported that in file PRIME_20220126103554 they received a message where the performing organization address was misformated. 

What was sent:
Department of Youth Services, Paul T Leahy Campus^^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^22D1096659|363 Belmont street, Worcester Mass.^^^MA^01604

MA's claimed correct format:
363 Belmont street^^Worcester^MA^01604

Following up with MA to get additional message IDs and samples.

**Comment by anshulkumar-usds** [comment]
1/28: MA reported that this issue is isolated to this facility address only.

**Comment by jorg3lopez** [comment]
@Adrian-Brewster We ( @oslynn ) were unable to locate prime-20220126103554 on the db. We located another file that was sent out on 01/26, prime-20220126141615. In this file we found the same issue with one of the test results. The specimen_id for the test result with this issue is: `65e28c39-7a1d-46f9-8b8e-eb108bd4e493`. Ott will work on this using this specimen_id.

**Comment by oslynn** [comment]
@anshulkumar-usds @Adrian-Brewster.  After @jorg3lopez helped me to locate the file prime-20220126141615.hl7 from Azure storage.  We get the specimen_id (report_id) from the file.  Using the report_id to locate the input CSV file.  We then found the wrong formatted address is in the CSV file.  Do we want to fix the CSV file or fix in the backend?

**Comment by oslynn** [comment]
Responded to @Leslie Garner Frankin: 
Hi @Leslie Garner Franklin (AVL, she/ her) (cc: @Maurice Reeves @Adrian Brewster @Anshul) I was looking into the ticket 4032: https://app.zenhub.com/workspaces/onboarding--ops-62012871b0f8520011170cc6/issues/cdcgov/prime-reportstream/4032.  By examining the CSV customer input file, I found that they have the wrong address (363 Belmont street, Worcester Mass.) inserted into the column of "Testing_lab_street".  Therefore, our ReportStream does what it suppose to do.  It generates the address (363 Belmont street, Worcester Mass.) instead of (363 Belmont street, Worcester) as their want.  @Maurice Reeves advised them to input the correct address and resubmit.  Hope my explanation is making sense.  If I confuse you, please get with me.  Thank you.

**Comment by oslynn** [comment]
After confirming with Leslie, I will move the ticket to Done.

**Comment by Adrian-Brewster** [comment]
Adrian will follow up with Leslie

**Comment by leslie** [comment]
Hi All,

You all have the wrong Leslie tagged on this project.

Cheers!
