### ISSUE TITLE
OH - Duplicate Submissions (Failures from 1/30)

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#4079]
Date: 1/28 - 29/2022

OH is experiencing the same issue as IL with duplicate submissions. Following are the message IDs. 

Please correct and resend with new message control IDs if possible.

**Comment by anshulkumar-usds** [comment]
Issue is being addressed

**Comment by anshulkumar-usds** [comment]
OH has requested we resubmit all failed messages with valid LOINCs and new message IDs
"Ideally, we would like to receive only the corrected results with valid LOINC codes with new message control IDs then than their original values so they do not fail."

**Comment by anshulkumar-usds** [comment]
OH also sent us additional failures they saw on 1/31. These need to be added to our backlog of resubmissions. Please see attached.

[https://app.zenhub.com/files/304423150/c172ecf9-e8ad-42fd-8e8f-c58e787b0312/download](https://app.zenhub.com/files/304423150/c172ecf9-e8ad-42fd-8e8f-c58e787b0312/download)

**Comment by anshulkumar-usds** [comment]
@jorg3lopez any update on this?

**Comment by MauriceReeves-usds** [comment]
@jorg3lopez @anshulkumar-usds @Adrian-Brewster I'm looking at this now. I have a few ways we can tackle this:

1. We can send them the spreadsheet for the LOINC failures as we did with the other states, and they can update their system. This is the easiest path
2. Or, we can get the all the original SimpleReport submissions, create new files, and resubmit manually on our own after updating the message ID. This is more difficult and requires more steps but is doable.

I do not want to just manually update the HL7 files and copy them up to their server with new message IDs because we lose chain of custody on those message IDs. Therefore I'm really hoping they'll let us do #1. I have that ready and I will forward that to you in KeyBase. If they want #2 instead we can have that ready by end of day today.

**Comment by anshulkumar-usds** [comment]
2/7: Checked with OH on their preferred path. Awaiting response from OH.

**Comment by anshulkumar-usds** [comment]
Resubmissions completed on 2/8. OH acknowledged receipt. Awaiting confirming and accuracy of data by OH.

**Comment by anshulkumar-usds** [comment]
2/10: Checked with OH on anything pending

**Comment by anshulkumar-usds** [comment]
2/11: No further news from state. Closing.
