### ISSUE TITLE
Ticketing Tool for End Users

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4160]
## Problem Statement
As the O&O team, when our users report issues to us, we need a way to let them know where their issues are in our list of priorities and understand how and when they get resolved so that can provide excellent customer service to them.

## Background Info
[Mural board](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1643814910324/dfb5ed0e10d45cbac2356ec9c4178f94d535d34f?sender=ud3aa760e30b39bcf436d4473) from discussion on 2/2

## Background Info
- When a RS user has an issues with our platform, the only way currently to notify the development/product team is via email - directed personally to team members, or to the share mailbox. Managing inboxes is not fun for anyone, and leads to backlogs of email management and customer communication delays.
- Let's explore creating issue forms in Github. @kjt9cc suggested this: https://beyondco.de/blog/github-issue-forms; This may also auto-tagging of some sort, and will remove the intermediate step of someone in the O&O team or PRIME Ops team having to create tickets.
- We are exploring alternatives using CRM, but actual implementation of that is months away (potentially).
- FYSA: @mlighdc @kjt9cc 

Must Haves: 
- 
- 

Nice to Haves:
- 
-

**Comment by loripusey** [comment]
@anshulkumar-usds @Adrian-Brewster @sarahnw Please add your list of wants for this tool
cc: @rachelhanster

**Comment by Adrian-Brewster** [comment]
As a STLT, I want to be able to:
 - Click on a link that would bring me to a form that allows me to enter the issue name, when it started occurring, what that submitter severity level is and attach files/images
 - When the form is submitted, I would like to receive an email response with a ticket number
 - I would like to have access to an issue form where I can search my issue number and see what progress has been made on the ticket

**Comment by Adrian-Brewster** [comment]
As a member of O&O, I want to be able to:
 - be notified when a new ticket is opened
 - have a space to triage ticket and assign priority level before it automatically becomes part of zenhub product backlog
 - NOT have to update ticket progress in multiple places (must integrate with ZenHub or be tracked separately)
 - System automatically sends submitter email when issue is ready to be retested
 - Have access to a dashboard that shows all open tickets to help facilitate meetings with STLTs

**Comment by victorialb-usds** [comment]
I am adding some user quotes to add more context: We got a  question from a state that likely feeds into the user story: 

I have a question for you: Currently, our pipeline detects issues with data integrity on incoming files (e.g., missing valid LOINC codes in OBX 3.1) and generates an automated email to the sending facility, asking them to review, correct, and resubmit the problematic records or files. With CDC Prime as the sending facility, these notifications will all come to you. Do you have a mechanism by which you will serve as the intermediary between us and the facilities that submit data through you in order to resolve issues? For example, we work with APHL for issues with data submitted via AIMS, and APHL has a ticketing system that allows both sides to participate in a conversation to resolve individual issues.

**Comment by victorialb-usds** [comment]
@loripusey @rachelhanster this seems like a feature that could be useful to get some design on and we could ask of future calls with Nevada and Idaho since we will be meeting with STLTs anyway. cc @drew-usds

**Comment by kjt9cc** [comment]
might be able to use this: https://docs.clickup.com/en/articles/3714856-public-sharing
