### ISSUE TITLE
[Bug]: Navigating back to first page of results never shows newer items.

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#4196]
1. Got to Submission History.
2. Navigate to 2nd page using Next
3. Add new items so they show up at the start of the Submission history.
    - May have multiple tabs open or API user has stuff submitted while they have this page open
4. Hit the Prev button to return to the first page.
Result: the new items don't show up.

Cause: the first page of results is using a starting cursor of the 2nd page with a limit of 10 (or whatever the pagesize is) in ASC mode.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/74203452/152427584-df40e491-e9cb-4b8a-95da-18bbf8ad2ad2.png">

**Comment by kevinhaube** [comment]
A proposal for a general solution when designing for this cursor-based pagination is to grab our own "cursor" as an 11th item, rather than pulling 10 items only. While we still only display 10, the 11th is indicative of further data to pull and can be checked to show/hide the `Next ->` button.

In ascending order (clicking Previous), this 11th item would be the one prior to the first displayed item in descending order. With the addition of a stored timestamp as a means of checking our 11th item, we can ensure that the 11th item is indeed a new item that was not part of the original first page and show a "New Items" indicator that, when clicked, refreshes the table.

Steps to modify:
- [ ] Modify API call to pull 11 items
- [ ] Store original results[0] (1st item) 
- [ ] Check results[10] (11th item) before showing Next button when call uses DESC (navigating backwards)
- [ ] Check results[10] (11th item) before showing Previous button when call uses ASC (navigating backwards)

**Comment by kevinhaube** [comment]
Fixed with #4743
