### ISSUE TITLE
Document and share Washington's data validation rules 

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#4252]
## Problem Statement
As part of research, we are finding out what validation various state PHDs do as part of their system that takes in COVID test results. We need to get the rules from Washington and evaluate what rules they have.

## Acceptance Criteria
- [ ] Get R scripts from Washington public health department team

- [ ] Document data validation rules in Washington's R scripts

Note: As of 2022.02.08 most, recent common errors are missing data (first name, last name) and bad column header fields

- [ ] Share findings with the team

**Comment by victorialb-usds** [comment]
Here is a link to the document shared from WA text of email where I requested it below for context - this was part of the CSV pilot: https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B00e2e75a-2b2a-4868-835a-844f4785dbe5%7D&action=edit&wdPreviousSession=4fefe8be-2c34-41c6-bb99-f708159d2a2b 

Hi Emily and Benjamin,

 

Hope you are doing well.

 

I am following up as we mentioned in the call that ReportStream is piloting a CSV upload feature. We are trying to learn from states about the validation processes they have built and have needed in order to get good quality data. Could you share with me respectively:

R transformation script (annotated or with notes as needed)
-      R validation script (with notes if possible)

 

We are hoping that the first wave of pilot users will wrap up here in the next month and we will have news and more concreate plans for expanding to other states like Washington.

 

Thanks so much,

 

Victoria

**Comment by victorialb-usds** [comment]
@HeatherRienks tagging you here as I was looking through the board and found this thread. This is the validation work that WA does. Did this and others state validation process already get summarized and shared for the validation feature? Would this be useful? This was collected for CSV upload pilot. CC: @fmccaf1 @drew-usds @kevinhaube

**Comment by fmccaf1** [comment]
@victorialb-usds I don't think so, since the validation service is aimed at senders, not receivers. I think this is the info needed for O&O to make sure that receivers are getting data in the correct format for them.

**Comment by chris-kuryak** [comment]
Closing by committee. WA is onboarded.
@drew-usds @lizzieamanning
