### ISSUE TITLE
Clean and Present Final Design for Sorting & Filtering Submission History

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4271]
## Acceptance Criteria
- Consolidate Figma designs
- Use 2 element date picker
- Put default sort arrows on the header
- Address feedback that came out of user research

**Comment by drew-usds** [comment]
### Index

[Submission history index](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=754%3A0&node-id=1142%3A565&viewport=298%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=1150%3A470)

_Notes_
- Use [USWDS date picker](https://designsystem.digital.gov/components/date-picker/) to create start + end range
- Use [USWDS dropdown](https://designsystem.digital.gov/components/dropdown/) to select records per page. Use 25, 50, 100 as options. Default to 25.
- "Clear filters" can just be a standard link for now
- Use [USWDS pagination links](https://designsystem.digital.gov/components/pagination/), not the current buttons. Since we can't use the `1, 2 ... 9, 10`, we can just pull out the `prev / next` links from it

_Dev questions_
- What is the best option for default dates? Do we start with them blank? Or use current/all-time range?

### Report detail

[Report detail page](https://www.figma.com/proto/VrSkTA87t8PPeXPugQ0i8O/ReportStream?page-id=754%3A0&node-id=1142%3A829&viewport=298%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=1150%3A470)

_Notes_
- Add [USWDS breadcrumb](https://designsystem.digital.gov/components/breadcrumb/) to take you back to `submission index`
- Turn jurisdiction sent-to details into table

**Comment by drew-usds** [comment]
Followed up with Kevin on #1922, made some small changes to factor in how React works.

**Problem:** The filters will auto-update as you enter in a date, and will therefore error out if it isn't complete. Ex: If you type in the first date range but haven't entered in the second, the table will update and show zero results until you type in an end range.
**Fix for now:*** Add buttons for`Filter` and`Clear filter`. The filter won't apply until you hit the button.

**Comment by BerniXiongA6** [comment]
@drew-usds @inkandsound can this ticket be closed yet?
