### ISSUE TITLE
SPIKE - How Can we Find Out if a Sender is in T or P Processing Mode

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#4272]
## AC
- Get answers to these questions
    - what field tells ReportStream if a sender is in T or P mode?
        - upload-covid-19.schema it is the processing_mode_code, but it pulls from customerStatus
    - where is the field's value stored?
        - it is stored in the settings table on the sender or receiver level
    - Is there a different field for senders who use the standard schema vs. senders who have a custom schema?
         - no, but it is processed differently (see notes)
    - Does ReportStream application use the "customerStatus" json field for anything?
         - yes, absolutely!

**Comment by loripusey** [comment]
@ahay-agile6 I assigned this to you, let me know if you have any questions or want to speak first

**Comment by ahay-agile6** [comment]
2/18/2022
Meeting with Joel and Rick Hood
Notes:

processing mode code for receiver: 
are senders in test mode or production?
customerStatus:
- set within the organization level of settings table
- internal flag to report or include or exclude certain senders
- where are errors coming up?
- don't really follow up in production for troubleshooting if there are errors
- drive list of current states that have been onboarded rather than updating manually
- DOES NOT PROVIDE ANY INHIBITING FOR SENDING OR RECEIVING DATA

processing mode code:
- usually t or P
- can explicitly set it in the message
- P = any receivers check the mode code only P gets sent through
- T or D, or any other value does not get sent through, ever
- T = testing in production phase (can contain PII) 
- on a `message` level basis, can override per message
- also set at the schema level
- confusing: set through okta??
- confusing: set _kinda_ at a sender level...
- receivers will have in their qualityFilter `doesNotMatch(processing_mode_code,T,D)` to filter out messages


upload-covid-19.schema 
-
