### ISSUE TITLE
MP Biomedicals - Sender Onboarding

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4288]
- [ ] Kickoff and Introduction to ReportStream & TOS
"• Get and analyze sample/dummy data from sender
• Finalize schema and share with sender"
Onboard to Staging
Send staging private key to sender (keybase.io)
Sender tests in staging until mutually agreed stability of data and connectivity is reached (no PII)
Validate sender data with receiver states
Onboard to Production (in test mode)
Mutual agreement to RS/Sender TOS
Send production private key to sender (keybase.io)
Sender and RS perform final validation data in production (using PII)
Onboard to full Production (connectivity with states)
Fully in production; onboarding complete

**Comment by anshulkumar-usds** [comment]
@jbiskie moving this to sprint backlog.

**Comment by jbiskie** [comment]
Attaching 3 versions of a sample file MP Biomedicals sent us on 3/11. 

[mpbiomed-01.csv](https://github.com/CDCgov/prime-reportstream/files/8264234/mpbiomed-01.csv) - Original xlsx file saved as csv
[mpbiomed-01a.csv](https://github.com/CDCgov/prime-reportstream/files/8264235/mpbiomed-01a.csv) - removed the "null" values from all columns
[mpbiomed-01b.csv](https://github.com/CDCgov/prime-reportstream/files/8264236/mpbiomed-01b.csv) - same as 01a with the equipment_model_name changed to BinaxNOW, since MP's test does not have EUA yet

**Comment by anshulkumar-usds** [comment]
@jbiskie Are these files meant to be shared with any state? Not finding any thread on this.

**Comment by rhood23699** [comment]
4/7/22 Test file based on existing NIH OTC specs look good, and Sender has been informed that this specs will change.  We need to discuss criteria for moving them to PROD.

4/8/22 Security key created and sent via keybase.io.  TOS was received. Zoom call today.  Fixed API connectivity. Reviewed JSON messages.
