### ISSUE TITLE
[Bug]: Admin Settings: Error notification alert too small for some messages

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#4314]
**Describe the bug**
Some error messages that popup when saving changes are too long to fit in the existing "toast" popup. Dialog needs to be bigger and with a Close or Dismiss button (i.e. the dialog that occurs when hitting the Delete button)

**Impact**
Error messages are truncated, and thus not readable, and the dialog might go away before the user has the chance to read it or screenshot it.

**To Reproduce**
hey @TomNUSDS , I was unable to repro an existing example of this. Do you remember what specific operation made the too-lengthy dialog?

Once [this story](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4313) is completed, more lengthy error messages are guaranteed to display and develop against

**Expected behavior**
Error messages readable

**Screenshots**
TBD

**Comment by kevinhaube** [comment]
Stale description, should be verified, but likely a good bug ticket to work on!

**Comment by HeatherRienks** [comment]
@brandonnava & @brick-green - is there a need for this ticket?

cc: @BerniXiongA6

**Comment by brick-green** [comment]
I don't think there's enough information here to really know what the issue was

**Comment by TomNUSDS** [comment]
Did you ever find yourself going "what was that error that flashed briefly on the screen?" or maybe "I wish I could copy that error that just displayed and disappeared into an email"?

You can see these errors (aka "toast" since it briefly pops up from the bottom of the screen) in this clip:

https://user-images.githubusercontent.com/102491809/208483134-494b5a8e-4c34-4814-bc42-7759f287bfa4.mp4

If O&O doesn't feel like they need this ability, then it's probably to close this issue.

**Comment by HeatherRienks** [comment]
FYI @chris-kuryak and @stephenkao

**Comment by chris-kuryak** [comment]
@HeatherRienks I will bring this up in O+O and Exp sync today.

@brandonnava @brick-green - referencing Tom's response above, does that provide enough info to determine if this is a bug/enhancement you want?

**Comment by HeatherRienks** [comment]
Per O&O/ Exp Sync, not an issue, closing
