### ISSUE TITLE
ImageMover - Investigate Data Quality Issues for Performing Facility Name and Ordering Facility Name

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#4385]
During the resolution process for address missing MSH-4 values for LA, @jorg3lopez noted that several messages from ImageMover are missing Performing Facility Name and Ordering Facility Name.

LA issue: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/2666

Please investigate the scope of this issue for ImageMover supplued data and assess which other messages (regardless of states) are also missing this data. We can then take this metadata, and work with the sender to improve data quality.

cc @MauriceReeves-usds

**Comment by jorg3lopez** [comment]
@anshulkumar-usds @Adrian-Brewster @MauriceReeves-usds I ran this query to get a count of the files affected:

```
SELECT count(*)
FROM public.report_file A 
INNER JOIN public.covid_result_metadata B 
ON A.report_id=B.report_id
WHERE A.sending_org = 'imagemover' and B.ordering_facility_name is NULL and B.ordering_facility_state = 'LA'
```
Total files with ordering facility name null : 1,076,981

Total files with ordering facility name null and ordering facility state LA: 3,806

**Comment by MauriceReeves-usds** [comment]
@jorg3lopez don't forget that the CRM table has all the duplicates in it. You'll want to count by distinct message ID.

**Comment by jorg3lopez** [comment]
#### Update
This issue should be resolved by now. It so happened that the schema from imagemover was blanking the fields to prevent phi leaking. Imagemover asked us to black the fields because some OTC test results had the patient's name and lastname in those fields. We reached out to imagemover around september 2022, and they told us that they had fix this issue on their end. 

Imagemover disabled those fields. Now, some states like DE wanted those fields populated but they are now blank. To fix this issue, the flag of `replaceValueAwithB` was modified to replace blanks.

This ticket can be close.
