### ISSUE TITLE
NJ - OBX 23.1 Issue

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4435]
NJ is still having issues with OBX-23.1 for the AOE’s.  For the COVID test itself this is OK, but for the other OBX segments this continues to be an issue.  NJ has to manually fix these and it is creating delays in their processing. 

@MauriceReeves-usds @jorg3lopez can you confirm if this is in reference to the truncation work you didnt for OBX 23.1 previously?

**Comment by jorg3lopez** [comment]
@Adrian-Brewster Truncation logic was not working properly. The fix is in production and I have resubmitted a total of 97 files to NJ.
file names:
`covid-19-cdd3cc12-6903-4122-9463-d7ee3afbe278-20220223231406` (02/23/2022)
`covid-19-d884d2b4-8693-4af7-9dcf-e25e4074b994-20220225225904` ( 02/25/2022 )

**Comment by Adrian-Brewster** [comment]
@anshulkumar-usds Will follow up with NJ to make sure messages uploaded well.

**Comment by anshulkumar-usds** [comment]
3/1: Checking with NJ to have them review the two files above and get confirmation the truncation is working fine.

**Comment by anshulkumar-usds** [comment]
3/3: NJ validated the data. Closing.
