### ISSUE TITLE
Update our Submission History endpoint name.  Update openApi spec to match.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#4557]
needs a little grooming.

### Current state of affairs

To my knowledge, we have:
`api/reports`   the old original endpoint using azure function keys.  Supports POST submissions only at this time.
`api/waters `   Same as api/reports, but uses twolegged auth.  Supports POST submissions only at this time.  We promised to use this name.
`api/history/report`     Supports the old download page.  Same as HistoryFunction.kt.   Can return a list, or if a reportId is passed in, this can return an actual individual report file (the actual data!).    This is actively in use, but let's please consider this deprecated and we'll trash this, and move this functionality over to the new API as soon as we can.
`api/history/<org>/submissions`    Get a summary list of submissions.  paginated.   `api/history/<org>/submissions/<actionID>`   Get a single lineage-history-details.
`api/history/<org>/reports/<reportID>`    Get a single lineage-history-details.
`api/history/<org>/reports/<actionID>`    Get a single lineage-history-details.
Furthermore, this is what's in the openapi.yml, which I believe is not correct?
  ```
# The submissions end-point handles receive actions.
  #
  # END-POINTS
  # /submissions
  # /submissions/submission/{actionid}
```
Let's take a step back and design something reasonable, then fix the code to match that.  No-one is using the new API yet except our own frontend team, so now is the time to clean this up.

### Design Considerations

- Want to support both Admin users and per-org users.
- Regardless, all queries should always require an Org (?)
- Don't use plurals when single item is returned.
- Need to continue supporting 3 auth styles:   azure function key (deprecate soon!), two-legged, and Okta.
- Continue supporting both actionId and reportId queries
- Don't make current submitters to api/reports have to change.  However, its ok to change any endpoint not widely used yet.
- Note that api/history/report is only used by our webpage.   It would be nice to just leave it alone, until it gets replaced.
- We have to keep the 'waters' name.
- Will eventually need to support both sender queries and receiver queries.  Also, will need to support queries that get actual data, as opposed to metdata.

## Acceptance Criteria Proposal (working draft proposal for review)

This story is done when

1.  We have these endpoints:

`POST api/waters`   Main submission endpoint for POSTs using two-legged auth and Okta.  Already in use, so prefer not to change this.   
`GET api/waters/org/<org>/history/`       returns the history of submissions for one org.
`GET api/waters/org/<org>/history/<actionId>`    returns the history of one action taken
`GET api/waters/org/<org>/history/<reportId`>      Returns the history of one report

Old/Deprecated, but will stay unchanged for now:

`POST api/reports`   Our original submission POST endpoint.
`GET api/history/report`    Our original download site API

### Follow-on work:
This work was moved to #4949
- The endpoints are correctly documented properly in the openapi.yml file.
- The lineage details response returned by these endpoints is also correctly documented in the openapi.yml file.

### Looking ahead

Its worth thinking ahead about other queries we know we want to support, in particular, those queries done by recievers of data.

`GET api/waters/org/<org>/history/`    Same endpoint as for senders!   Returns a history of data sent to a receiving org.
`GET api/waters/org/<org.receiver>/history/`    Return history for just one "feed".  For example, `GET api/waters/org/oh-doh.elr-secondary/history`
`GET api/waters/org/<org>/history/<reportID>`     Same endpoint as for senders!  Returns history details of one report sent.
`GET api/waters/org/<org>/report/<reportID>`    Downloads the actual report data

If an org ever has a mix of senders and receivers, this will not work well.   To date, there are no such cases.
 
### Is this future work, or part of this ticket?

@TomNUSDS suggests these:

- standardize our 'language' for filtering across all calls that return lists of things.
- do pagination the same way across all calls that return lists of things.
- Sometimes we take the org in the header, sometimes the org in the URL, and sometimes the org implicit in the auth.    Simplify.   Note that we want to allow for admin role whose auth != their Org.

**Comment by TomNUSDS** [comment]
GET `api/waters/org/<org>/history/` returns a list so maybe the plural: `api/waters/org/<org>/histories/`?

This different name also helps with the path parser because it can be tricky to route `api/waters/org/<org>/history/<reportID>` to one function and what looks like a "truncated path" of `api/waters/org/<org>/history/` to a different one.  (e.g. is `api/waters/org/<org>/history/` missing a parameter or want a list?)

**Comment by jimduff-usds** [comment]
> GET `api/waters/org/<org>/history/` returns a list so maybe the plural: `api/waters/org/<org>/histories/`?
> 
> This different name also helps with the path parser because it can be tricky to route `api/waters/org/<org>/history/<reportID>` to one function and what looks like a "truncated path" of `api/waters/org/<org>/history/` to a different one. (e.g. is `api/waters/org/<org>/history/` missing a parameter or want a list?)

I'm not a big fan of 'histories'; I liked history because it can be thought of as both plural and singular.    If we have to go that route, maybe switch back to 'submissions' and 'submission'.  However, I prefer 'history' because it suggests getting metadata, as opposed to the actual data.   

Also, I think it would be ok if both the list and the individual details requests are the same Function.

**Comment by whytheplatypus** [comment]
I think `history` is ok as a list endpoint, but there might be a better word for the data being retrieved / how it's being used.

For the download flow: the endpoints that let the user see what's available for download and the action of downloading itself should be related. (e.g. if it's `/reports/<report_id>` there should be a list endpoint at `/reports`)

Re: Implementation we should make as much use of what little framework azure functions gives us, specifically to set the path, arguments within those paths, and http methods. Even if under the surface multiple azure Functions call the same underlying code.

**Comment by TomNUSDS** [comment]
> [@whytheplatypus](https://github.com/whytheplatypus):
> For the download flow: the endpoints that let the user see what's available for download and the action of downloading itself should be related. (e.g. if it's /reports/<report_id> there should be a list endpoint at /reports)

Agreed. (I go into gruelling details below.)

> [@whytheplatypus](https://github.com/whytheplatypus):
> Re: Implementation we should make as much use of what little framework azure functions gives us, specifically to set the path, arguments within those paths, and http methods. Even if under the surface multiple azure Functions call the same underlying code.

Excellent point. On a related topic, I heard talk about possibly using the [Azure API service](https://azure.microsoft.com/en-us/services/app-service/api/#overview) to handle a bunch of things for us. But I'm not sure how far in the future this is.

> [@jimduff-usds](https://github.com/jimduff-usds):
> Also, I think it would be ok if both the list and the individual details requests are the same Function.

I'll try to explain my rationale for clearly separating the two endpoints:

- Usually, list operations queries return just minimal information in _an array_ so that it can be returned and displayed quickly in a table. It use filters and a cursor as cgi parameters and ONLY supports the GET (Read) action.

- Individual item API queries return deep, detailed information on just one entity and use the identity key. This endpoint typically supports CRUD operations (via http verbs POST, GET, PUT, PATCH, DELETE). It does not support filters/cursor.

(Reference because I have a hard time keeping the mapping straight)
  HTTP Verb | CRUD 
  -- | -- 
  POST | Create | 201 (Created)
  GET | Read
  PUT | Update/Replace
  PATCH | Update/Modify
  DELETE | Delete

Regarding naming convention, I suggested unique names for the two different endpoints because of how I seem to remember Java Spring and React handle routing internally. The two endpoints could _both_ be matched if both start with `api/waters/org/<org>/history/` and both are GETs. How does the router know which one should be called?

Maybe it's not an issue if it's `api/waters/org/<org>/history` vs `api/waters/org/<org>/history/`? I'm see discussions online saying if there's a cgi parameter that can be matched, then it's possible?

Just think we should be willing to self-correct the API if, when implementing, the developer hits issues.
