### ISSUE TITLE
Submission history QA

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4753]
## Problem statement

Submission history is coming along! Let's collect any and all things we ID while doing QA on this feature. Let's collect any design and engineering edits/adjustments here and fix them.

This is following on from #1922, which currently has been merged #4743

## Acceptance criteria

CSV user
- [ ] User can log in
- [ ] User can view list of submissions
- [ ] User can filter by date range
- [ ] User can change number of results per page [25, 50, 100]
- [ ] User can page back and forth between results, both filtered and not
- [ ] ~~User can sort date table col header~~ need to break this out into a new issue based on feedback from Kevin
- [ ] User can see `success` status for each submission
- [ ] User can click through each item to the details page
- [ ] Page works reasonably well on smaller screen sizes (desktop focused for now, but should be not completely broken on smaller screens)

## To do

- [ ] ...

**Comment by inkandsound** [comment]
**Submission History:**

- Filter section layout/text needs to match design more closely: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=2515%3A24581
- Calendar icon - could we make the hover state link blue on the icon instead of having the gray box background?
- If we keep the gray box background: overlapping calendar icon box is a little off - should move over a couple pixels so it doesn't cover the focus state 
![screenshot](https://images.zenhubusercontent.com/611a905f814eda0684979aed/654e6680-4c1b-44bf-9432-72f32d347c26)
- Expected behavior clicking into a calendar date text field would be to bring up the calendar underneath - would be nice to adjust this
- Next/previous should be text instead of button styling
- Let's flip the order of next/previous given how the dates are being sorted on the list (it's confusing to click "next" and go backward in time)
- Pagination: Pages feel like they take a long time to load
- Small screens: Would be good to break the filter area into a couple of lines and introduce a Y scroll on the table so you can see the content (right now a lot of it disappears and there's no way to see it if it's under around 560px wide
![screenshot](https://images.zenhubusercontent.com/611a905f814eda0684979aed/b75506d5-7f6b-4d96-9af5-d52cdeb8efcf)

**Details Page:**
- Details page takes a long time to load
- Remove "null" 
- Capitalize "ELR"
- Headings (e.g. "Transmission Date") should be #71767A
- Move things around slightly to match the latest designs (combine date/time onto one line, update heading text): https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=2515%3A24581
- Can we implement the breadcrumbs from the design at this stage? Should be a small thing.

**To Implement:**
- Submission history: Need "Number of records per page" options at the bottom left : 25, 50, 100

@kevinhaube

**Comment by inkandsound** [comment]
Ticket from engineering to address QA items: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4834
