### ISSUE TITLE
AOE Age LOINC Code Change

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4839]
For the age AOE, NIH has LOINC Code: 35659-2 and the new April guidance has 35659-2.  Previous HHS specs had 30525-0.

We need to do three things for this ticket:
1. Communicate this to the states so they are aware the change is coming, and we need to ask the ones that receive the AOE questions if they are okay receiving the updated LOINC code or not.
2. Update the COVID-19 schema with the new code for the age AOE question
3. For the states that receive the AOE questions *AND* are not able to handle it, set up a replaceValue configuration option for them that replaces the LOINC code value with the old one.

Communication to states and updates should be completed by April 4

**Comment by anshulkumar-usds** [comment]
3/23: This is the latest COVID-19 lab data reporting implementation specifications link. It states Age at time of collection:
https://www.hhs.gov/sites/default/files/hhs-guidance-implementation.pdf

**Comment by anshulkumar-usds** [comment]
3/23: Sent the following note to all STLTs:

Please note that due to recent updates issued by HHS for COVID-19 reporting specifications, ReportStream will be making the following changes to Ask-On-Entry (AOE) questions for reporting purposes. If your jurisdiction has opted not to receive AOE questions, you may disregard this notice. The changes will be made effective April 4, 2022.

Change:
Patient age collected at the time of specimen collection in OBX-3 will be updated with a LOINC of 35659-2 (previously 30525-0).

If you have any questions or concerns, please write to us at reportstream@cdc.gov


Sincerely,
The ReportStream Team

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds States were notified last week. No questions or objections since. You may proceed with next steps.

**Comment by anshulkumar-usds** [comment]
@MauriceReeves-usds any next steps here

**Comment by MauriceReeves-usds** [comment]
@anshulkumar-usds we should make sure the change was actually made, and then we can close it out.

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds have you confirmed these changes have been applied?

**Comment by Adrian-Brewster** [comment]
Mo taking a look today.
