### ISSUE TITLE
HL7 Serializer setTelephoneComponent Errors Out on Malformed Phone Number

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#4877]
During testing a cardinality issue with @rhood23699 we found a situation where a blank phone number fails in setTelephoneComponent in the HL7 serializer. We should not fail when the number is blank text.

Example, the code below is in upload-covid-19.schema.  testing_lab_phone_number and ordering_facility_phone_number are both blank, so I expected an error since the cardinality: ONE is set; but I don't receive an error on ingest, and the outbound HL7 has blank for the ORC.23.6 & ORC.23.7.

We replaced mapper: ifNotPresent with mapper: coalesce(ordering_facility_phone_number, testing_lab_phone_number and the blank phone number fails in setTelephoneComponent in the HL7 serializer.

For testing use the attached CSV file.  I've also attached the YML for the inbound sender cadph-csvuploadertest and outbound receiver al-phd.

curl -X POST -H "client:cadph-csvuploadertest" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test-AL.csv"  "http://localhost:7071/api/reports"

    - name: ordering_facility_phone_number
      cardinality: ONE 
      csvFields: [{name: ordering_facility_phone_number}]
      mapperOverridesValue: true
      mapper: ifNotPresent($mode:lookup, testing_lab_phone_number, ordering_facility_name_temp, ordering_facility_street_temp)

[https://app.zenhub.com/files/304423150/771a7857-c60f-4ec1-afbc-da1e0d4c9a07/download](https://app.zenhub.com/files/304423150/771a7857-c60f-4ec1-afbc-da1e0d4c9a07/download)

[https://app.zenhub.com/files/304423150/72e3561d-b725-4b17-a231-f57824423f87/download](https://app.zenhub.com/files/304423150/72e3561d-b725-4b17-a231-f57824423f87/download)

[https://app.zenhub.com/files/304423150/3161b734-56d3-4092-9360-041175eaf7f8/download](https://app.zenhub.com/files/304423150/3161b734-56d3-4092-9360-041175eaf7f8/download)

**Comment by oslynn** [comment]
This is the same problem as ticket 4918.  Up on investigated, during translator.filterAndTranslateByReceiver(inputReport, getDefaultValues(), emptyList()), it always returns reports schema = covid-19 instead of the input-schema specified in command line. This will cause the HL7 generation to use covid-19 instead of upload-covid-19.schema as input schema. Therefore, regardless of what we change element in upload-covid-19 schema, it will not affect the HL7 generation. @MauriceReeves-usds greats a ticket for me to fix the filterAdnTranslateByReceiver. Therefore, this ticket is put into Spring Backlog.
