### ISSUE TITLE
Import current staging environment into terraform

### ISSUE THREAD

**Issue by acoushawk** [CDCgov/prime-reportstream#5022]
Based on the refactored code, we need to import staging using the new terraform code. Once that is complete, there will be new tickets created for objects that exist in Azure that are not represented in terraform. This should be done by way of adding a module for the aforementioned item(s).

**Comment by jeremy-page** [comment]
I checked, there are several resources that are imported in the wrong order (i.e. [0] as [1] or the other way around). Working on it

**Comment by JosiahSiegel** [comment]
Status after migrating staging to same terraform as prod/test. Minor changes not yet applied:
# Staging
## No changes
```sh
terraform plan \
-target=module.app_service_plan \
-target=module.container_registry \
-target=module.database \
-target=module.key_vault \
-target=module.metabase \
-target=module.nat_gateway \
-target=module.network \
-target=module.application_insights
```

## Pending minor changes
* front door reorder
* SFTP recreate from sftp_vnet_network_profile
* Storage removes a few container/public subnets
* Function app firewall reorder and subnet change, autoscale adjustment, and candidate env to "test"
* LAW diags recreated due to case change
```sh
terraform plan \
-target=module.front_door \
-target=module.sftp_container \
-target=module.storage \
-target=module.function_app \
-target=module.log_analytics_workspace
``
