### ISSUE TITLE
API sender documentation: draft how programmers guide could become web pages

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5092]
## Problem Statement

As an API sender, I want to easily access information on the product, onboarding, and product use. Currently I can view this as a pdf, however when revisions are made any given downloaded file will be out of date.

## Background

- The existing guide is a doc/pdf. The doc is currently getting updated in several places (Sharepoint, github, RS website)
- The doc is currently versioned (sort of), but has gotten out of sync with multiple teams working on it.
- [Existing programmer's guide](https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v2.1.pdf), currently linked on [getting-started/.../overview](https://reportstream.cdc.gov/getting-started/testing-facilities/overview)

## AC

- [ ] Design/Content: Create outline to show how Programmer's guide could live on RS website
- [ ] Design/Content: Draft template of what Programmer's guide could like look on static web page

## To Do

- [ ] Share deliverables (sitemap and template) via SharePoint to Exp. team 
- [ ] Get deliverables reviewed/QA by Exp. Design crew and Engineers

**Comment by mreifman** [comment]
Could we use GitHub Pages (https://pages.github.com/, https://docs.github.com/en/pages) for this? It would require a bit more digging and experimentation, but we could either write Markdown directly in the GitHub UI or use [Jekyll](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll) to generate a static site and host it on GitHub Pages.

**Comment by HeatherRienks** [comment]
Per Backlog refinement mtg on 5/4, we will revisit this after #5391 has been completed.

**Comment by sethdarragile6** [comment]
Not only is there a Jekyll but also a Mr. [Hyde](https://hyde.github.io/) because of course there is.

**Comment by HeatherRienks** [comment]
Discuss in standup on 5/25/22.

**Comment by a-chappelear** [comment]
Figma template: https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3210%3A21984
Almost identical to the "what's new" section. A couple of considerations unique to this is the need for code snippets and some of the guide is table heavy.

For now - it lives under "How it works"

Next steps for this would suggest - 
Building only a mark-down template & section for this. (Looks mostly complete already!) And having the content from the programmers' guide migrated into pages via design to implement (since there may be some adjusting of content pieces.)

@drew-usds @bgantick @kevinhaube @RakshindaAslam

**Comment by HeatherRienks** [comment]
@kevinhaube. @fmccaf1  - FYI!
