### ISSUE TITLE
Help center: service blueprint for help processes

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#5134]
## Problem statement

Map out how RS can help users resolve common problems with public content/etc. Map out how we can offer further help to users if our help center doesn't answer a question.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Existing mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1654716456535/43504cdbe7f2a29f80df032f9874d2eab20a71e1?sender=ud6a3555dd1821b626a2b3726)

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by fmccaf1** [comment]
Closing this ticket because it has overlaps with some research we're doing currently, such as [epic 7341](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/7341)

[Also already mapped some of O&O's support process here.](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1664828377684/37d40ca8316ccc49451a96901ae70dd08050aaf7?sender=ua604735c5cf1162b042a4310)
