### ISSUE TITLE
Operations: email uploader users about transition

### ISSUE THREAD

**Issue by rachelhanster** [CDCgov/prime-reportstream#5140]
## Problem Statement
As an organization, we want users to know about the transition from reportstream to simplereport via a series of email messages to current Uploader users.

## Acceptance criteria

- copy of email message series in sharepoint doc
- list of contacts

## To do

- Experience team develops series of 3 email messages
- Experience team determines frequency and specific send date
- Ops team develops list of contacts
- Operations team sends email messages

**Comment by HeatherRienks** [comment]
What content should be included? 
Cadence of sending?

**Comment by HeatherRienks** [comment]
@BerniXiongA6 - please refer to #5145

**Comment by HeatherRienks** [comment]
Target for initial comm to end users is week of 6/13/22. @HeatherRienks to confirm with SR team on 7/1/22 date (it's a holiday weekend!)

**Comment by BerniXiongA6** [comment]
Updated 5/25: Starting this ticket to have email series content ready for review before I leave for PTO.

**Comment by HeatherRienks** [comment]
Per SR team, new tentative dates for CSV uploader transition:
**Go live** on Simple Report on **Tuesday, 7/5/22**
**Sunset** on ReportStream-side on **Monday, 7/18/22.**

**Comment by BerniXiongA6** [comment]
Updates on 5/27/2022: The [SharePoint doc containing the email comms strategy and templates](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EdCfWvOO45dLkHiBwi6qoswBcFHxFnbzp48DyOANyzvSyQ?e=oHboBl) are Ready for Review/QA. I've also included the link in the SR/RS Transition Comms doc too (in case you all need to reference it in our next sync call with SR that I'll likely be absent for). There's a section in the DRAFT doc that needs SimpleReport content, I've tagged Laura Kerry of Skylight who has agreed to work on that piece. Thanks!

**Comment by BerniXiongA6** [comment]
Also, O&O should have the list of CSV upload contacts that we'll send the email comms to. We can ask them to handle the distribution of this email comms series once we finalize/approve the copy. Thanks! cc: @RakshindaAslam @HeatherRienks @drew-usds

**Comment by BerniXiongA6** [comment]
Updates on 6/6/2022: Accepted some suggested edits by Laura Kerry and @HeatherRienks - Awaiting next follow up conversation on these email comms with RS and SR. Thanks everyone! cc: @RakshindaAslam @drew-usds

**Comment by BerniXiongA6** [comment]
6/6/2022: Closing this because the content work is done from Exp. team's end - All that's left is for BX to follow up with NIH to discuss their edits/feedback regarding ReportStream's feature on their site. I think the best next step is to make sure we're clear about NIH/NIBIB goals for featuring their partners when I reach back out to Andrew Weitz. That will help us determine what kind of revisions we want to make to their RS content based on what we learn. [Here's the project folder](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Content%20design/3.%20Content%20Design%20Projects/ReportStream%20Web%20Copy%20on%20NIH%20Website?csf=1&web=1&e=p50zSp) I've created to document this progress (email comms, the original content we sent, etc.). cc: @RakshindaAslam @rachelhanster @kjt9cc

**Comment by BerniXiongA6** [comment]
6/7/2022: Met with @RakshindaAslam - email comms for the most part a good to go! Awaiting feedback from Zedd and Laura on the SR portion of the content but it's mostly done and ready to go by mid-June! [Refer to Email Comms Strategy for CSV transition](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EdCfWvOO45dLkHiBwi6qoswBcFHxFnbzp48DyOANyzvSyQ?e=oHboBl) for updated content!

**Comment by BerniXiongA6** [comment]
6/7/2022: Since O&O will likely be sending out the emails with Exp. team's help, I'll close this ticket since the email series and plan is mostly ready to go. BX will work with O&O to send the emails to uploader users per the [Email Strategy schedule outlined](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EdCfWvOO45dLkHiBwi6qoswBcFHxFnbzp48DyOANyzvSyQ?e=oHboBl).
