### ISSUE TITLE
Date picker allows for invalid date range to be selected

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5180]
**Describe the bug**
Date filters are labeled start and end, but this gets confusing when accounting for a sorting order as well. Currently the date pickers allow for an invalid range to be selected and no results will show.

**To Reproduce**
1. Go to submission history for an org that has a bunch of results (A1H CA for example)
2. Set filters to ascending dates that should return results.
3. No results returned

**Expected behavior**
Start was defined as the closest date to present day, and end, the furthest. The date range picker should allow the user to select two individual dates to create a range, and _not_ allow for the start date to be a more historic date than the end date. 

**Screenshots**
Pre-filtering:
![Screen Shot 2022-04-14 at 1.24.44 PM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/1a5a7eea-1596-42e5-95d1-ec367b5be2a0)

After filtering:
![Screen Shot 2022-04-14 at 1.24.52 PM.png](https://images.zenhubusercontent.com/5a6b4b784b5806bc2bc46da6/b2a7c3cc-9e9c-49f2-9ed2-3ae9b54614c2)

**Comment by kevinhaube** [comment]
Copied over from a discussion on #5127:

We originally intended to leave the ability for start and end range UI elements to be interchangeable for a user, as Brian is attempting to do here. That's fine if both dates are set every time, but the logic breaks down once you consider somebody who'll only set one date. There's no way for our software to tell what a user expects "end range" to mean if they don't provide the context of what they think start range means, as well. For this, we removed that interchangeability.

The true solution to that issue is a UI change. We should be using the [Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/) from USWDS, but the React component version cannot be used to mimic the current design because it's stacked instead of horizontal like ours. However, I think we can use the USWDS classes to make one and add our own classes atop that to reorient them horizontally. I'll copy this info to the other ticket, as well.

**Comment by kevinhaube** [comment]
Bonus: There's also a visual bug with our current filters that clearing them will not clear the visual value (i.e. what you see in the input), but does reset the programatic value (what the true value is). I think this bug can also be tackled with this change! I couldn't find a ticket for it, but I remember it being a point of feedback/known bug in a review with Dawn when filters first released.

**Comment by kevinhaube** [comment]
Updated content and title to match the root issue of this bug.

**Comment by kevinhaube** [comment]
Deployment delayed on 05/12/2020
