### ISSUE TITLE
CX survey: recruit research participants for f/u interviews 

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#5211]
## Problem statement
In order to hear from users directly and have them expand on their experience, we will be following up with organizational points of contact to understand their experience in more detail to inform the future of the product, address needs, and also for marketing material. 

## What you need to know
The survey is anonymous. we made decision not to do a drop down of organizations so hopefully people tell us who they are. 
In recruitment email note that we do not know if they completed the email. 
No more than 10 people.
Must consent to have them use quotes. Can share them with them before publishing. 

- add link to the protocol

- ...

## Acceptance criteria

- [ ] Promoters and detractors are emailed about participating in f/u interviews
- [ ] Meetings are scheduled with 5 promoters and 5 detractors (try for ~equal mix of senders/receivers for each)

## To do

**Schedule meetings (Berni)**

- [x] Draft email to send [examples from CSV upload pilot]
- [ ] Send out email to prospective participants
- [ ] Schedule meetings

**Comment by BerniXiongA6** [comment]
Today I'm starting to work on this ticket. Will prioritize sending out email comms before or by the end of this week to recruit research participants for follow up interviews to occur next week (May 9th through 12th).

**Comment by BerniXiongA6** [comment]
Promoters and detractors have been identified at the [CX Survey Data spreadsheet](https://cdc.sharepoint.com/:x:/t/USDSatCDC/EQf3-S3AXytLt7RR1cPR79MBM_KpCZfy2hNGdpSHuiHvDQ?e=y0gePm).

**Comment by Adrian-Brewster** [comment]
Responded to slack but I will add here as well:

@Berni Xiong Just want to make sure I am understanding.  Since I recall the the survey was anonymous, how do we know who responded and who didnt? It looks like we have a couple of detractors, so I am assuming these folks opted into identifying themselves?
I know @sarah and @Rakshinda Aslam were planning on doing some outreach to end users.  We may consider combining theses efforts a bit so we can "feed two birds with one scone." Who on the experience team will be conducting the interviews?

Adrian Brewster  3 minutes ago
Just my opinion, I am not overly concerned about over burdening users with requests for feedback.  I think most will see it as us really wanting to improve our offerings and be happy to participate.  Since these are all optional meetings, they can certainly opt out.
On the list you identified, we have a biweekly call with WA set up for every other Monday.  We can add this to the agenda for our next meeting so you dont have to set up a separate call. The others are pretty low touch and I imagine you wont have an issue getting 1-2 folks on a meeting to discuss.  I am happy to help set those calls up if you would like. @BerniXiongA6

**Comment by BerniXiongA6** [comment]
Updates on 5/6/2022: [Here's the email template](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EamHzWsiDmFNtP5vTGQ_dQYBz-onANNq5tainD2pVCE1xQ?e=jluehz) that has the communications we plan to send out on Monday 5/9 to promoters and detractors identified. In Review/QA with @Adrian-Brewster .

**Comment by BerniXiongA6** [comment]
Updates on 5/9/2022: I've revised the Email template with suggested edits by @Adrian-Brewster. This afternoon, @RakshindaAslam and I will finalize outreach plan before I send out email comms either later today or tomorrow.

**Comment by BerniXiongA6** [comment]
More updates 5/9/2022: I'll close this ticket out once all emails are sent (anticipated 5/10/2022). See shared doc with tracker (link coming today).

**Comment by BerniXiongA6** [comment]
Updates on 5/10/2022: [Here's the link to access the Experience Team Outreach Tracker in SharePoint](https://cdc.sharepoint.com/:x:/t/USDSatCDC/EdQTAaw3KlNDl6qGFrWtpU0BRbCrqUaXBobIOzDqMEJeEg?e=37gJhj). Closing this ticket now since managing and scheduling the tickets can be completed under [Issue # 3499](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3499).
