### ISSUE TITLE
Email message: Inform Uploader users of Submission page - Send email message to all Uploader users

### ISSUE THREAD

**Issue by victorialb-usds** [CDCgov/prime-reportstream#5218]
## Problem statement
As someone working at an organization reporting covid results, I need to be able view a list of csv files shared with ReportStream, so I can keep track of data submissions and so my organization has "written proof" should CLIA inspectors request proof.

As an organization, Reportstream wants to communicate to end users about new features. We need to communicate about submission history. 

## What you need to know
- Given a user is logged into reportstream as an Upload user
- User is directed by default to "Upload" page
- "Submissions" page is found next to "Upload" page

## Acceptance criteria

- Via email, all current Uploader users are informed of Submissions page availability
- Message has a mix of written and visual content

## To do
- [ ] Send email message to all Uploader users

**Comment by BerniXiongA6** [comment]
Updates on 5/2/2022: Content and instructional design deliverables are ready for review by @drew-usds @Adrian-Brewster ! Any questions, lmk.

[Here's the link to the Shared Folder](https://cdc.sharepoint.com/:f:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/Instructional%20Design/3.%20Instructional%20Design%20Projects/ReportStream%20Email%20Comms%20to%20Senders%20for%20Viewing%20Submission%20History?csf=1&web=1&e=zh0Pcx) to view: 1) Email copy template, and 2) Quick Guide to Submission History

**Comment by sarahnw** [comment]
@victorialb-usds is this something we need anymore? is this a dupe? I'm removing O&O's label.

**Comment by BerniXiongA6** [comment]
@victorialb-usds @drew-usds @sarahnw I remember this one -- when I was still on Exp. Team, I created the instructional guide on how to use the Submission History. I think the short term goal was to have Adrian email it to users. However, the ultimate goal was to have O&O review/approve the guide so that it could eventually become a resource (PDF or web copy) on the RS website. Let me bring this up to @RakshindaAslam -- see where she would like to go with it. In the meantime, I'm going to move it to O&O's internal review and will assign me to it.

**Comment by BerniXiongA6** [comment]
OK to close per @RakshindaAslam
