### ISSUE TITLE
ImageMover - Uptick in Timeouts

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5250]
**Describe the bug**
ImageMover had flagged an increase in timeouts between 4/16 to 4/19. @jimduff-usds @clediggins-usds @cwinters-usds  Any idea what could have caused this?

**Comment by cwinters-usds** [comment]
Yep, this was something Abbott had flagged as well. The current theory[1] is that one of our containers was accepting requests but not responding, so random requests would take a long time to return and not be processed. A resend would typically work.

Te deploy Tuesday AM cleared out the issue, and we've got monitoring on it (see the "Unusual HTTP status codes" graph on the shared "ReportStream Production Performance" dashboard) and are keeping an eye in case it happens again.

[1] "Theory" because we don't have a lot of insight into individual containers we're running, something we're looking to fix in the future.)

**Comment by cwinters-usds** [comment]
Closing because this was a known occurrence.
