### ISSUE TITLE
Web page design - "Built for you: new in Reportstream" 

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#5382]
## Problem statement

As a user, I want to be able to view newly built features and bug fixes in ReportStream in user-friendly format and language that is easy to understand.

## What you need to know
- [x] [Example 1](https://www.intercom.com/changes/en) and [Example 2](https://mailchimp.com/whats-new/)

## Acceptance criteria

- [x] Same style as the rest of the ReportStream site
- [x] Easy to navigate
- [x] Reviewed with the engineers

## To do

- [ ] ..

## Considerations
- [x] How will the page be updated?
- [x] Refer #5118

**Comment by BerniXiongA6** [comment]
@a-chappelear Regarding the Design portion of this ticket, please 1) visit the[ Release Notes 2.0 process proposal (slide 9)](https://cdc.sharepoint.com/:p:/t/USDSatCDC/EQQIHJZLN_lIjfBm0_zTziwBZNBq8wXAw0WZlQ962WdoKw?e=0wzUBi), 2) refer to the best practices we've already done research on in the second bullet point for "Best practices for formatting monthly release notes as copy on a website landing page," and 3) refer to 3rd bullet point that include examples provided that could we could model after (engineering all agreed that Asana's example was a good place to start). Let me know if you need to jump on a call to chat more. Otherwise, my plan was to bring this up in Design sync tomorrow. Happy to provide context regarding these initial ideas. cc: @RakshindaAslam

**Comment by a-chappelear** [comment]
Update via our design sync -

We looked at a couple of options for the "what's new" section of the public site. 

I started a small diagram to start mapping together how all the types of "new" content (website, release notes, email) might  flow together: https://app.mural.co/invitation/mural/primedatainput6410/1652912453295?sender=uc91f7c72c0f84196a8818813&key=24c24545-24bf-4570-a091-a7aa9c4c86fd

For the UI work, there are 2 options. We discussed that for now and based on the content length - "What's New" works best as a single page, showing all updates by month on the page. 

(Single page)
https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3107%3A21751

In the other option, it only works best if the content happened to be very long every month. But! there is a piece of it to consider even for the single page - long-term, it seems like this, and maybe even release notes may need some kind of archiving/blog-like ability. (In this case, the single page would then have a side nav sorted by year.)

Note the side nav in this version:
(https://www.figma.com/file/VrSkTA87t8PPeXPugQ0i8O/ReportStream?node-id=3106%3A21679)

I know our site is static, so a question for Eng ( @bgantick )knowing there is work being done to move pages to mark-down, does the new tooling also support something like that. If not, that is likely ok for now, just something to consider further out.

Otherwise, the single template uses essentially all the same formatting as other pages on the site (I annotated the comp names if needed.) Happy to discuss on Monday if needed!


@RakshindaAslam @BerniXiongA6 @HeatherRienks @bgantick

**Comment by BerniXiongA6** [comment]
Updated 5/23/2022: From a content standpoint, the considerations above have been answered in the Content Strategy & Email Marketing Plan that was completed today - [see file in SharePoint](https://cdc.sharepoint.com/:w:/t/USDSatCDC/EaL2QHqgxYJOpbaAeJ26plIBPTvps1XQAopiDSDco8yqtw?e=qbD3wp). Design and Content work for this ticket has been completed.

**Comment by kevinhaube** [comment]
Closing this out, development has begun! :) Thanks Andrea!
