### ISSUE TITLE
Existing API Re-queue Function Does Not Appear to Work

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5409]
Within the API, we have a requeue mechanism at `/api/requeue/send` that should send an existing file to a receiver. The invocation should look like this:

```
curl -X POST "http://localhost:7071/api/requeue/send?reportId=15a67edd-0913-4f1c-81ea-42cc34064826&receiver=de-dph.elr"  
```

Unfortunately this no longer appears to work, and it does not provide a response or an error message indicating why. We will fix it. It is possible that the error is related to issues with authentication when attempting to invoke. If this is the case, it would be better to return an error informing the invoker that they are not authorized to initiate this action instead of the current result which is it returns nothing.

### Acceptance Criteria
- The endpoint accepts either `POST` or `GET`. Currently it only accepts `POST` but with an empty body. Let's make it more flexible and accept either
- The endpoint should return a result in either an error or on success
- The endpoint should return `401` if the user is not authorized to conduct this action
- Verify with the pipeline team that the requeue actions are tracked in the submission history, and if they are not, coordinate the creation of a new ticket for them to do that. We should be logging these actions so we know when a file is resent. 

### Goals
- Once we have this working more clearly, the intent is to wire this into the web UI so we can invoke it for files that need to be resent. To that end, please coordinate your activities on this ticket with @TomNUSDS

**Comment by TomNUSDS** [comment]
Oh, I forgot to mention. I tested this using a POST API and it seemed to work?

The API returned:

```
Will resend all (30) items in d05d17f7-acaa-4f0e-bda1-135dbd81d477
d05d17f7-acaa-4f0e-bda1-135dbd81d477 has been queued to resend immediately to ignore.HL7_BATCH_OFFSET_TIME_UTC
```

I got the params from the `task` table and found a row that was marked `send_error` and used the `reportId` (`d05d17f7-acaa-4f0e-bda1-135dbd81d477`) and `receiver_name` (`ignore.HL7_BATCH_OFFSET_TIME_UTC`) columns.

We still need to sanity check that the resend is actually queuing correctly.

**Comment by jimduff-usds** [comment]
yeah, it works.    

Current syntax for calling it as of this writing is:
curl -X POST -H "content-length:0" -H "x-functions-key:<SECRET>" "https://prime.cdc.gov/api/requeue/send?reportId=861f31ec-276c-489c-a733-b55f701bcb4a&receiver=nm-doh.elr"

The secret is for the requeue azure function; NOT for any of the regular submission endpoints.

Because it operates within the existing code, any data re-sent gets correctly linked in the auditing tables.

Things to fix:
- move to using Okta auth
- get rid of the bizarre content-length header requirement.

Longer term:
- add a Resend button on the Receiver's Daily Data of Daily Data Details page.   Would need to hide this button for receivers that have no automated transport defined.
