### ISSUE TITLE
Look up patient state from patient zip code

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#5700]
**Is your feature request related to a problem? Please describe.**
The RADx spec allows senders to provide a patient zip code, but no state. Currently, we require patient state to be entered for proper message routing.

**Describe the solution you'd like**
We need to be able to populate patient state from patient zip code, in order to meet the RADx data spec.

- Change HL7 ingest schema to allow patient state to be populated from a look up of the patient zip code.
- Do not change if there is something present in the patient state.

**Additional context**
Some example messages are located in keybase: prime_dev_ops/sender_info/Intrivo

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5700?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by Adrian-Brewster** [comment]
Blocker for moving Intrivo forward. @MauriceReeves-usds to look into smarty streets

**Comment by Adrian-Brewster** [comment]
@MauriceReeves-usds looking into smartystreets this sprint.

**Comment by TomNUSDS** [comment]
If it's _JUST_ zip->state, that's a pretty small table since the zip 3-digit prefix determines the state.

See: https://en.wikipedia.org/wiki/List_of_ZIP_Code_prefixes

The layout is also in prefix _ranges_. E.g.  California is 900-961, so the table is likely ~60 rows (AP and discontinued are in there)

**Comment by sarahnw** [comment]
At this point in time we need to unblock API senders using RADX MARS so we're moving ahead without SmartyStreets. We will revisit a feature for SmartyStreets in the near future.

**Comment by brick-green** [comment]
Code completed. Need to write the PR next.

**Comment by brick-green** [comment]
of course things got tricky at the end. One of the smoke tests is failing but I can't quite figure out why. Gonna pair with some other engs tomorrow to get it sorted out.

**Comment by brick-green** [comment]
Lookup mapper was failing and has now been fixed. Based on our discussion in slack, I had to make patient state an optional field. Writing up PR now

**Comment by brick-green** [comment]
Merging to master. Here are the schemas that will be affected: 

- direct-careevolution-covid-19
- direct-hca-covid-19
- hl7-detect-covid-19
- hl7-hcintegrations-covid-19
- hl7-lifepoint-covid-19
- hl7-mns-covid-19
- hl7-prescryptive-covid-19
- hl7-primary-covid-19
- hl7-signetic-covid-19

The functionality is such that a state value will be filled in based on the zip code only if the state is sent in blank. @sarahnw @BerniXiongA6 Do we need to communicate with any senders on this?

**Comment by BerniXiongA6** [comment]
@brick-green This is awesome! I'll defer to @sarahnw on whether to communicate this to senders. Ideally, it's good practice to close the loop on requests or issues if they seem significant enough to share outside of release notes (otherwise, we're publishing monthly [release notes on the RS website](https://reportstream.cdc.gov/product/release-notes)).
