### ISSUE TITLE
CO - [CDPHE ELR Prod] Error: Cannot Write File to DB

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#5738]
Automatic Email from cdph_elr@state.co.us

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason: 
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-1eba8992-3eb4-4de0-bbbc-79fa70c39b20-20220601133010.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: **null**
Received by: CDPHE ELR Prod
Received on: 2022-06-01 13:30:07
File source: CDC PRIME
File name: covid-19-1eba8992-3eb4-4de0-bbbc-79fa70c39b20-20220601133010.hl7

Please review, correct, and resubmit the file.
Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by sliu1000** [comment]
6/9/2022 11:22 AM

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason: 
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-16e4abf0-5bda-41ea-97b8-558ae42c0ed9-20220526013056.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-26 00:00:00
File source: CDC PRIME
File name: covid-19-16e4abf0-5bda-41ea-97b8-558ae42c0ed9-20220526013056.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by sliu1000** [comment]
6/9/2022 11:22 AM

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason: 
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-5069a806-e737-410c-906d-bb378cc36e61-20220531193047.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-31 19:30:28
File source: CDC PRIME
File name: covid-19-5069a806-e737-410c-906d-bb378cc36e61-20220531193047.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by sliu1000** [comment]
6/9/2022 11:22 AM

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason: 
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-0a96f55d-3622-4588-a99f-29562b9910af-20220601013026.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-06-01 01:30:11
File source: CDC PRIME
File name: covid-19-0a96f55d-3622-4588-a99f-29562b9910af-20220601013026.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by sliu1000** [comment]
6/9/2022 11:22 AM

This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason: 
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-99f8fe6b-e555-4b50-b5c2-d8fe4356d544-20220530133020.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-30 13:30:19
File source: CDC PRIME
File name: covid-19-99f8fe6b-e555-4b50-b5c2-d8fe4356d544-20220530133020.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-1855d2cd-6b3e-4132-9a96-fa46b578c3f3-20220525073038.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-25 00:00:00
File source: CDC PRIME
File name: covid-19-1855d2cd-6b3e-4132-9a96-fa46b578c3f3-20220525073038.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-16e4abf0-5bda-41ea-97b8-558ae42c0ed9-20220526013056.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-26 00:00:00
File source: CDC PRIME
File name: covid-19-16e4abf0-5bda-41ea-97b8-558ae42c0ed9-20220526013056.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-24109188-efd6-404a-aed5-21c3e2a575ed-20220531073032.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-31 07:30:26
File source: CDC PRIME
File name: covid-19-24109188-efd6-404a-aed5-21c3e2a575ed-20220531073032.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-3c33563a-6a71-4a70-80d3-b8e1eb74f9cf-20220529133005.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-29 13:30:04
File source: CDC PRIME
File name: covid-19-3c33563a-6a71-4a70-80d3-b8e1eb74f9cf-20220529133005.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-5069a806-e737-410c-906d-bb378cc36e61-20220531193047.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-31 19:30:28
File source: CDC PRIME
File name: covid-19-5069a806-e737-410c-906d-bb378cc36e61-20220531193047.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-0aa2b54e-2ff7-49f7-8de2-898078878045-20220602073009.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-06-02 07:30:08
File source: CDC PRIME
File name: covid-19-0aa2b54e-2ff7-49f7-8de2-898078878045-20220602073009.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-055dd0ff-5652-4d5f-b7df-e6a1c0ab9066-20220526073036.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-26 00:00:00
File source: CDC PRIME
File name: covid-19-055dd0ff-5652-4d5f-b7df-e6a1c0ab9066-20220526073036.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-0fb47c25-d4aa-4dde-94e0-60354fd9059a-20220530013043.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-30 01:30:41
File source: CDC PRIME
File name: covid-19-0fb47c25-d4aa-4dde-94e0-60354fd9059a-20220530013043.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-626f1d44-8e17-4dfb-b70b-434aa5aae470-20220529193100.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-29 19:30:57
File source: CDC PRIME
File name: covid-19-626f1d44-8e17-4dfb-b70b-434aa5aae470-20220529193100.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-95c0ce4c-9331-449a-9bcb-fbc5da09e7d5-20220525013100.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-25 00:00:00
File source: CDC PRIME
File name: covid-19-95c0ce4c-9331-449a-9bcb-fbc5da09e7d5-20220525013100.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-99f8fe6b-e555-4b50-b5c2-d8fe4356d544-20220530133020.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-30 13:30:19
File source: CDC PRIME
File name: covid-19-99f8fe6b-e555-4b50-b5c2-d8fe4356d544-20220530133020.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-ae5fcea3-ea64-49e4-a3d6-44961c1345c3-20220529073012.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-29 07:30:12
File source: CDC PRIME
File name: covid-19-ae5fcea3-ea64-49e4-a3d6-44961c1345c3-20220529073012.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-c3a30eb3-f4e0-4299-8a7e-c98f6a1d4cf4-20220526193031.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-26 00:00:00
File source: CDC PRIME
File name: covid-19-c3a30eb3-f4e0-4299-8a7e-c98f6a1d4cf4-20220526193031.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-c3e40b1e-1026-444c-ae12-322c7de73a29-20220527193021.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-27 19:30:13
File source: CDC PRIME
File name: covid-19-c3e40b1e-1026-444c-ae12-322c7de73a29-20220527193021.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-a21cbc26-07cb-4cfb-aa56-13d87e651b8b-20220526013107.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-26 00:00:00
File source: CDC PRIME
File name: covid-19-a21cbc26-07cb-4cfb-aa56-13d87e651b8b-20220526013107.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-e46140f2-9381-4792-a5be-3eb5ebf13db7-20220525193019.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-25 00:00:00
File source: CDC PRIME
File name: covid-19-e46140f2-9381-4792-a5be-3eb5ebf13db7-20220525193019.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-cbd70401-46f5-4336-9f46-fdfa54f19a3f-20220531013020.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-31 01:30:11
File source: CDC PRIME
File name: covid-19-cbd70401-46f5-4336-9f46-fdfa54f19a3f-20220531013020.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-f3578a4d-0968-4ea0-b3ae-dde5880f5e8f-20220601193018.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-06-01 19:30:09
File source: CDC PRIME
File name: covid-19-f3578a4d-0968-4ea0-b3ae-dde5880f5e8f-20220601193018.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-ce8c7745-a255-49cc-9f66-40b8c9a19e50-20220525013111.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-25 00:00:00
File source: CDC PRIME
File name: covid-19-ce8c7745-a255-49cc-9f66-40b8c9a19e50-20220525013111.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-e58425f6-5f57-45df-86d1-77a53a16f767-20220531193040.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-05-31 19:30:26
File source: CDC PRIME
File name: covid-19-e58425f6-5f57-45df-86d1-77a53a16f767-20220531193040.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by shy2cdc** [comment]
This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.

Issue Report: Cannot insert the file into the database due to the following reason:
**************************************************
Violation of UNIQUE KEY constraint 'IX_ImportFile'. Cannot insert duplicate key in object 'dbo.ImportFile'. The duplicate key value is (CDC PRIME, covid-19-e1fcbcc9-5bf8-4f44-bb33-bdf90420d5db-20220602193034.hl7).

**************************************************
A common cause for the failure to write a file to the database is that the submitted file has the same name as a previously submitted file. Please note that each file submitted must have a unique name.

Message ID: null
Received by: CDPHE ELR Prod
Received on: 2022-06-02 19:30:22
File source: CDC PRIME
File name: covid-19-e1fcbcc9-5bf8-4f44-bb33-bdf90420d5db-20220602193034.hl7

Please review, correct, and resubmit the file.

Please contact cdphe_elr@state.co.us if you have any questions about this email.

**Comment by Adrian-Brewster** [comment]
These errors came from resubmissions.  Connection issue has been resolved and we sent resubmissions. Getting error messages regarding duplicates. Adrian to email CO.

**Comment by sliu1000** [comment]
@Adrian-Brewster  Hi Adrian, I think this is a duplicate ticket. Maurice created a ticket #5722.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5738?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by Adrian-Brewster** [comment]
@sliu1000 Please email Nancy Kecso with CODPH and let them know that these errors were because we resubmitted some test results to address and issue a couple of weeks ago and this flagged them as duplicates. Let me know if you have questions

**Comment by Adrian-Brewster** [comment]
@sliu1000 Please email Nancy Kecso with CODPH and let them know that these errors were because we resubmitted some test results to address and issue a couple of weeks ago and this flagged them as duplicates. Let me know if you have questions
