### ISSUE TITLE
Add Action Resolution Table

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#5772]
As part of the logic for allowing for better resends/resubmissions, we need a way to track that a `send_error` has not be resolved/resent. To address this, I'd like us to add an `action_resolution` table that will let us track when a resend/resubmission has been sent, or at the very least, that a send_failure has been ack'd.

Once this table is added, we can wire it and the data from #5771 into an API call that will let us show the last mile problems in the UI.

I'm opening this up for discussion, but at a bare minimum this table should track the `action_id` and `report_id` as well as a status flag and CRUD fields (last_updated_at, last_updated_by, etc). I think it would be good to also have a field to point to a GitHub issue number (or some kind of ticket tracker in the future) AND an optional comments field for more info.

I think it would also be good to allow for multiple records per `(action_id, report_id)` pair because something may need to be re-sent more than once.

**Comment by MauriceReeves-usds** [comment]
cc: @TomNUSDS @jimduff-usds

**Comment by jimduff-usds** [comment]
Let's use the existing tables to handle this.   The action of resolving a send_error is just that - an _action_ taking on an existing report..   And we already have an ACTION table - we can add new action_names to cover any sort of situation.

The ACTION table also has free text fields that can be used to to store inputs to the action (action_params) and what happened (action_response).  There's no reason why these can't contain human-generated notes.

Importantly, the ACTION table is already wired (that is, FK'ed) into the lineage table, so that if we also put entries there, we can create a rich history of what we did with any report in the system.

**Comment by jimduff-usds** [comment]
To make this work, we'll have to extend the concept of generating 'fake reports' that @whytheplatypus started.

Note that currently there is flaw that send_errors don't appear in the _lineage_.  Lineage in ReportStream is from parent to child reports, not parent to child actions.   So when a send_error occurs, there is no child report, so there is no lineage.

Just to have a concrete example, production action `15632787` resulted in a `send_error`, and the only way to find the report it was trying to send is to read the action_params (`report&SEND&2da7209f-d0a1-4006-80ae-6925a61964f1&false`) and extract the report_id. 

Gage's use case is if a report has all of its data qualityFiltered out, so that no data is going to that State, we create a fake entry in the report_file table, so that we can link action_log entries to it, and provide history back to the user.

We can do the same with send_errors and send_error_fixed (or whatever)

You can find example fake_error by looking for reports with item_count = 0 in metabase.
An example 'fake' report is 661beafa-d7b4-4ac1-a69d-b582caf02b92, in production.  note that it has item_count = 0;
The original received report was '8eec31f0-f984-44b4-88ae-438a53a8c3f4', and the 661beafa-d7b4-4ac1-a69d-b582caf02b92 child report was created in the lineage so that we'd have a place to attach the action_log info saying that everything was filtered.

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/5772?planning-poker) with ZenHub @brick-green @greene858 @jbiskie @jorg3lopez @MauriceReeves-usds @oslynn @TomNUSDS

**Comment by JGreenFearless** [comment]
@MauriceReeves-usds Is this something that requires work from the Pipeline Team?

**Comment by TomNUSDS** [comment]
Tracing through the code, it _seems_ like there's already some kind of tracking for this?

```kotlin
updateHeader(
    reportId,
    Event.EventAction.RESEND,
    nextEvent.eventAction,
    nextEvent.at,
    RetryToken(1, retryItems).toJSON(),
    txn
)
```

This modifieds the `Task` db, but looking at that table in metabase, it seems odd.

**Comment by brandonnava** [comment]
@brick-green @MauriceReeves-usds Is this still on our radar as something we want to do? And if so would this be for engagement to take on or the API team?

**Comment by brick-green** [comment]
@brandonnava this would be work for the platform team. I think they should gauge if this functionality is covered and if not then what the solution should be.
