### ISSUE TITLE
Two digit year causes failure for datetime

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#5849]
## Problem statement

When a datetime is received with a two digit year (1/5/22 13:00) an error is returned.

## What you need to know

`error: INDEX=1, Invalid date: '12/21/21 09:00' for element order_test_date (order_test_date)`

## Acceptance criteria

- [ ] Two digit years are interpreted the same as four digit years

**Comment by MauriceReeves-usds** [comment]
Part of the reason we did not implement this logic is because there was an implicit assumption that would only ever receive four-digit years. It looks now like we may need to process two-digit years. There is a problem with this using the built-in logic in Java: since Java 8, it assumes any two-digit year is >= 2000. While this simplifies the logic for Java, it complicates things for us.

Personally, I believe that we should only accept four-digit years. I think that that is the most logical and clear solution. However, if we do encounter a need to support two-digit years, we should figure out how we're going to do it.

Because ELR is a historical record of an event in the past, I think it would be a reasonably safe assumption to say that if a date is in the future AND the raw value has two digits in the year position, that we assume the century is 1900. If I have to add this feature, I would also like to put it behind a configuration setting, where we explicitly set a value on a sender that says "any two-digit year you send us will be treated as happening < 2000, so if you send us someone's birthday, and they were born in 2000, but you give us 00, we are going to age them at 1900". It's gross and and I hate it, but it's the kind of trade off we're going to have to make.

Thoughts, questions, concerns?

**Comment by brandonnava** [comment]
@brick-green Is this still an issue?

**Comment by brick-green** [comment]
I think we can close this. It was more relevant when the CSV uploader was still with RS.
