### ISSUE TITLE
SQL issue investigation

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-reportstream#5873]
Deep dive on

1. Why this query took so long
2. Figure out what we need to do to improve this query (add index, partition data etc)
3. Put some better visibility in to make it clearer when this occurs in the future, if possible add an alert for when we are running out of connections (Before they are all exausted) 

[See this Slack thread for more details](https://semanticbits.slack.com/archives/C01SFFVH31Q/p1655436702261979)

**Comment by jimduff-usds** [comment]
I like the idea of an alert _before_ we exhaust connections.  (Although if memory serves, the connection graph didn't show connections exhausted...)

I'm not sure I see an additional index helping - typically if a query is slow due to that sort of thing, its always slow.

It is possible that partitioning out "old" data will help with this, and a host of other problems too.
