### ISSUE TITLE
IN - Onboarding Failed Test Messages

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#5939]
**Describe the bug**
Accession numbers for the failed ones - `3558a700-e5a3-494b-b0b8-bf6ae1004166` `9ef9098e-c4b2-4916-b1c2-a5f53aa75851`

They are for VDF Unity facility with CLIA -  14D2212079.

Error description is - The code for Ordered Test name is missing. Blank identifiers in segments HL7LabReport.HL7PATIENT_RESULT.ORDER_OBSERVATION.ObservationRequest.UniversalServiceIdentifier

**Impact**
Preventing IN from moving to production. Must populate OBR-4 and resend

**Comment by oslynn** [comment]
SELECT r.report_id, split_part(body_url, '%2F', 3) as "file_name", body_url FROM report_file r WHERE r.report_id='3558a700-e5a3-494b-b0b8-bf6ae1004166'

**Comment by oslynn** [comment]
Downloaded file: ~/Downloads/in-pdh/pdi-covid-19-f160f2f4-eec3-4a1c-bc0a-e2d5ebe0059a-20220623201200.csv

**Comment by oslynn** [comment]
Downloaded the messages associated with message_ids (3558a700-e5a3-494b-b0b8-bf6ae1004166 9ef9098e-c4b2-4916-b1c2-a5f53aa75851).
The problem is in the ./metadata/table/LIVD-Supplemental.csv.  It overrides the database row that has colunm (Model) of "iHealth COVID-19 Antigen Rapid Test" with a new row.  However, the new row has "Test Ordered LOINC Code" of blank ("").  Therefore, during livd table lookup for the Device_Id/Model, it returns blank ("").  In turn, it returns null which mean there is no such device in the table.
To solve the issue, I have to remove the row of Model colunm "iHealth COVID-19 Antigen Rapid Test" from the ./metadata/table/LIVD-Supplemental.csv file.

**Comment by oslynn** [comment]
2022-07-3 10:01am CST Resent to host: gasecuremft.in.gov:/CDCRS/Test two files:
covid-19-f2864e4d-43d8-4134-8ebc-0d166cf58b3d-20220703093418.hl7
covid-19-2fd54452-3ba5-4c7e-8a6a-965b49ab5753-20220703093635.hl7

**Comment by oslynn** [comment]
Connected to PROD 2022-07-20.
