### ISSUE TITLE
NH DHHS - Report Stream - Incorrect Patient State Issue - NH

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#6132]
Hello,
We are receiving incorrect state ELR messages from SimpleReport (Same patient, different dates).

It looks like there is a typo for state. This ELR should have been sent to NJ.

MSH-10:

`4117d7b7-7e50-4167-b5dd-8d3d28b355ae`

`52b08e5a-f2f3-40da-a4b8-a5f6add7d8c8`

`dedce3b3-7b15-4de0-aafe-eaec79815c3d
`
Entered PID Address:  2621 Hwy 138^^Wall^NH^07719^USA

The zip code is for “Wall Township, New Jersey”.

Thanks,

Myron Miroslaw Lizak, MS, MB(ASCP)CM

ELR Coordinator

New Hampshire Department of Health and Human Services
Bureau of Public Health Statistics & Informatics

Myron.Lizak@dhhs.nh.gov | Ph: 603-271-4224

**Comment by Adrian-Brewster** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Onboarding--Operations-6166edbd409257001e09f1b2/issues/CDCgov/prime-reportstream/6132?planning-poker) with ZenHub @brick-green @greene858 @jorg3lopez @oslynn @sarahnw @TomNUSDS

**Comment by sliu1000** [comment]
Emailed NH State and advised them to have the facility correct the wrong state selection.

**Comment by sliu1000** [comment]
The State Department of New Hampshire is still receiving results from NJ Facilities. For more information please see below:

We continue to receive out of state ELR messages for Covid test results from SimpleReport (Same patient, different dates).

It looks like there is a typo for state. This ELR should have been sent to NJ.

 

Most recent message: 8/1/2022

 

MSH-10:

`1b18534c-2514-42d1-b3e2-bc5e7829a522`

 

Entered PID Address:  2621 Hwy 138^^Wall^NH^07719^USA

The zip code is for “Wall Township, New Jersey”.

 

Please let us know if this is something your team could help address.

Thanks,

 

Myron Miroslaw Lizak, MS, MB(ASCP)CM

ELR Coordinator

New Hampshire Department of Health and Human Services
Bureau of Public Health Statistics & Informatics

Myron.Lizak@dhhs.nh.gov | Ph: 603-271-4224

**Comment by sliu1000** [comment]
**Updated Communications:**
@White, Sarah (CDC/DDPHSS/OD/HITSSU)@Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) I may need some assistance here as we may need to remove the NJ results in NH reports and confirm with NJ that the test results are in fact NJ and not NH.

The ReportStream Support Team

From: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>
Sent: Wednesday, August 3, 2022 4:12 PM
Subject: RE: SimpleReport/Report Stream Issues
 
Yes, got it. In this case it sounds like the zip code and state don’t match up so it is reasonable to ask for a correction, and you can let them know the NH team alerted you to the issue. The engagement would need to be with the specific facilities that are submitting with this issue, not to NJ health department.

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Wednesday, August 3, 2022 4:10 PM
Subject: Re: SimpleReport/Report Stream Issues

Hi Megan,

Sure, no problem. I just wasn't sure if I/we had the authority to tell them to change something. @Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) would you like to reach out to NJ or shall I?

Best regards,

The ReportStream Support Team

From: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>
Sent: Wednesday, August 3, 2022 4:07 PM
Subject: RE: SimpleReport/Report Stream Issues
 
Absolutely this is something the facility needs to correct. But NH needs assistance getting in touch with the facilities to ask them to correct and re-send. It would be great if the ReportStream support team can handle this reach out because NH mentions they don’t have the capacity.


Thanks,

Megan

 

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Wednesday, August 3, 2022 4:06 PM
To: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Subject: Re: SimpleReport/Report Stream Issues

 

Hi Meghan,

 

I'm not certain whose responsibilities it would be to correct the state dropdown selection errors.  As it appears to be an manual entry issue by NJ.

 

@White, Sarah (CDC/DDPHSS/OD/HITSSU) any thoughts?

 

The ReportStream Support Team

Contact us at reportstream@cdc.gov

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

From: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>
Sent: Wednesday, August 3, 2022 4:01 PM
To: Report Stream (CDC) <reportstream@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Subject: RE: SimpleReport/Report Stream Issues

 

Thanks, but I am wondering if we are reaching out to the facility to correct for this? NH mentions they don’t have the capacity to follow up with the facility on this, and I thought it was part of the follow up/maintenance services we would help provide.

 

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Wednesday, August 3, 2022 3:55 PM
To: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Subject: Re: SimpleReport/Report Stream Issues

 

Hi Meghan,

 

NH State Department believes its something the NJ facility needs to correct.  As they are receiving test results with NJ zipcodes with NH listed as the State.

 

Best regards,

 

The ReportStream Support Team

Contact us at reportstream@cdc.gov

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

From: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>
Sent: Wednesday, August 3, 2022 3:53 PM
To: Report Stream (CDC) <reportstream@cdc.gov>; White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Subject: RE: SimpleReport/Report Stream Issues

 

Can you provide a summary of current status of that ticket? Is this something we are handling or expecting NH to handle?

 

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Wednesday, August 3, 2022 3:51 PM
To: White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Subject: Re: SimpleReport/Report Stream Issues

 

Hi Sarah,

 

Its actually 6132. Please disregard the previous ticket.

 

Best regards,

 

Sharon

 

The ReportStream Support Team

Contact us at reportstream@cdc.gov

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Wednesday, August 3, 2022 3:39 PM
To: White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Subject: Re: SimpleReport/Report Stream Issues

 

Hi Sarah,

 

Yes there its ticket #6051.

 

Thank you,

 

The ReportStream Support Team

Contact us at reportstream@cdc.gov

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

From: White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>
Sent: Wednesday, August 3, 2022 10:57 AM
To: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Cc: Report Stream (CDC) <reportstream@cdc.gov>
Subject: Re: SimpleReport/Report Stream Issues

 

I don't think they should take this on. @Sharon, is there a ticket for this? If not, can you make one.

 

Megan, please let Corrine know we'll take this back and I'm sorry for the confusion. 

 

Sarah White (Nava PBC)

Senior Product Manager

Pandemic-Ready Interoperability Modernization Effort (PRIME)

Centers for Disease Control and Prevention

From: Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>
Sent: Wednesday, August 3, 2022 9:54 AM
To: White, Sarah (CDC/DDPHSS/OD/HITSSU) <tlk9@cdc.gov>; Reeves, Maurice (CDC/OD/OCS) <qva8@cdc.gov>; Xiong, Bernadette (CDC/DDPHSS/OD/HITSSU) (CTR) <rwe7@cdc.gov>
Cc: Report Stream (CDC) <reportstream@cdc.gov>
Subject: FW: SimpleReport/Report Stream Issues

 

Hi all,

 

Forwarding Corrine’s (NH) email below. Do you know why she would have been told she needed to take this on? I thought we helped suppose these kind of support requests?

 

Thanks,

Megan

 

From: Davis, Corinne - DHHS Affiliate <Corinne.M.Davis@affiliate.dhhs.nh.gov>
Sent: Wednesday, August 3, 2022 10:42 AM
To: Brewster, Adrian (CDC/DDPHSS/OD/HITSSU) (CTR) <mpz9@cdc.gov>; Light, Megan (CDC/DDID/NCEZID/DPEI) <wpa8@cdc.gov>; Ligh, Ming (CDC/OD/OCS) <rtn9@cdc.gov>
Cc: Report Stream (CDC) <reportstream@cdc.gov>
Subject: SimpleReport/Report Stream Issues
Importance: High

 

Hi all,

 

We reported a few issues regarding receiving ELR from patients not in our jurisdiction. These ELR are being sent from facilities that we did not onboard, but we were told by the Report Stream team that it was our responsibility to contact the facility. I hope you understand how difficult it is for our team to take on the responsibility of contacting facilities we did not onboard and are not in our state. It has taken weeks to get in touch with one of the facilities (NJ). This is not something we can take on in the future. Can you put me in touch with someone that can help resolve this issue?

 

Please see message control IDs below. Appreciate your quick response to this matter.

 

MSH-10

Correct State

d52b4ee7-a53e-4f9f-b55f-a8f189fbcb60

NM

1b18534c-2514-42d1-b3e2-bc5e7829a522

NJ

4117d7b7-7e50-4167-b5dd-8d3d28b355ae

NJ

52b08e5a-f2f3-40da-a4b8-a5f6add7d8c8

NJ

dedce3b3-7b15-4de0-aafe-eaec79815c3d

NJ

 

Thanks,

 

Corinne Davis, MPH, MS

HL7 Implementation SME

New Hampshire Department of Health and Human Services
Bureau of Public Health Statistics & Informatics

corinne.m.davis@affiliate.dhhs.nh.gov | Ph: 603-271-6970

**Comment by BerniXiongA6** [comment]
Hey @sarahnw When a zip code and state are both entered, and one happens to be incorrect, which supersedes the other? I’m curious whether the senders are populating the states incorrectly or if RS is mapping zip codes incorrectly? cc: @sliu1000

**Comment by sarahnw** [comment]
@BerniXiongA6 the state supercedes right now.

**Comment by sarahnw** [comment]
we don't do any comparison on zip and state - it's something we could potentially do and fix when we can implement SmartyStreets

**Comment by sarahnw** [comment]
d52b4ee7-a53e-4f9f-b55f-a8f189fbcb60 == pmg
1b18534c-2514-42d1-b3e2-bc5e7829a522 == simplereport
4117d7b7-7e50-4167-b5dd-8d3d28b355ae == simplereport
52b08e5a-f2f3-40da-a4b8-a5f6add7d8c8 == simplereport
dedce3b3-7b15-4de0-aafe-eaec79815c3d == simplereport all CareOne @ Wall

**Comment by sarahnw** [comment]
I've replied to let NH know they can ignore. I'll follow up with the senders on Monday.

**Comment by BerniXiongA6** [comment]
@sarahnw will reach out to senders -- keep In Progress fo rnow

**Comment by sarahnw** [comment]
I've asked the senders to correct and resend. Moving to external/qa
