### ISSUE TITLE
[SPIKE] Determine best approach for standardizing fetching on the frontend

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6259]
We currently have multiple way in which we fetch data on the frontend. Lets standardize this and figure out a long-term, sustainable implementation to suit our needs.

## Requirements:
- minimize dependencies, while also considering maintainability
- supports everything we need to do (GET, POST, DELETE, PUT, PATCH, appropriate level of customization for headers, etc)

## Steps:
- inventory/document current methods
- determine how current methods could be improved
- research libraries to replace current methods

## Outcome:
- suggestion for implementation (building off what we already have or replacing current methods with a library)
- decision documentation (pros and cons of approaches, why things would/wouldn't work for us, etc)

## Previous work:
- https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5519
- https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5555
- https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/5893

## Bonus considerations:
- caching
- retries

**Comment by kevinhaube** [comment]
Here's a quick bullet list of things I've run into recently that we should be on the lookout for:
- Support for simultaneous fetching AND chained dependent fetches (like one fetch returning the data needed for the next)
- Header data and URL variables/queries needs to be able to be set from components so we can consume our `SessionContext` and pass through tokens, org names, etc. 
- Some way to assert types at compile time as a _bare minimum_, but I'd really reccommend our own runtime type check layer OR finding a library that does runtime type checking _without_ boxing us in the way `rest-hooks` did ( @TomNUSDS has a lot of experience with those limitations, worth asking him! )
- Seems simple enough, but to use an `ErrorBoundary` we need to `throw` on a failure. Do we _also_ want to throw when the response is something other than a 200-299? Some libraries do and some don't. Not a huge lift to make a `useStatusToThrow` and pipe in the `status` from a response.

And I'm detaching this from my list because it's a total preference, though I'd argue it's rooted in some solid logic:  something hook-based, please! Working tools like `axios` in is proving to make reactivity a chore to engineer for. We have to build hooks to create reactivity with it, but something hook-based is designed for that out of the box. It seems like a gold standard for higher-traffic apps has been `react-query`. Being so highly regarded, it's probably a hefty package so keep that in mind, but its feature set is inspiring.

**Comment by TomNUSDS** [comment]
Some nice-to-have off the top of my head.

- **Support for strong types in typescript for GET responses and PUTs/POSTs data**. 
    > Strong types means we can declare the structure and enumerated values the API uses and have it enforced by the typescript transpiler. 
    > Rest-Hooks does this well for GET responses, but for DELETE it expects the API to reply with the same data being deleted. While we have a work-around, it's still a WTF.

- **Error handling inside the component doing the request so it can fail gracefully**
    > We have pages that have tables and filters above the table. When data is being fetched, it's super annoying to have most of the page turn into a spinner instead of JUST THE TABLE. Ditto if something fails to load.
    > Rest-Hooks does not do this well. It has ErrorBoundries outside the component with the fetching hook.

- **Great support for mocking jest tests**. 
    > We don't have unit tests for a bunch of components because mocking is just so difficult.
    > Rest-Hooks does poorly here too. Maybe it's gotten better?
    
 - **Plenty of examples on the correct way to do things**. 
    > Rest-Hooks required some reverse engineering to figure out how to get DELETEs to work. Lack of examples, stack-overflow expertise has been an issue. But we mostly worked through those issues.

**Comment by doug-s-nava** [comment]
I think I've got everything that's been mentioned in the comments here covered, but not exactly clear on the bullet for type checking. @kevinhaube , can you elaborate on what you'd like to see done that goes beyond what the out of the box typescript compiler does? I'm not clear on how this affects our choice around data fetching implementation

**Comment by kevinhaube** [comment]
@doug-s-nava Yes, this kinda thing is beta paired with the thought that we're working on creating unified data types from our API YAML -- classes allow for data sideeffecr logic to be isolated, and easily tested as well, compared to the interface and utility functions model that we use now.

**Comment by doug-s-nava** [comment]
Ah! It looks like rest hooks may sort of do this? https://resthooks.io/docs/api/Entity#validate Are we looking to maintain that kind of type checking at run time? That seems like a cool idea. I am not seeing that behavior in any of the other libraries I've looked at, though. It may be something we'd tackle separately

**Comment by kevinhaube** [comment]
@doug-s-nava It's something _we_ might be able to build in somehow, so don't consider it integral as a built in aspect, but yes, the goal is to maintain that validation behavior from `rest-hooks` because it can be super useful!

**Comment by RakshindaAslam** [comment]
@doug-s-nava - are we able to create an implementation ticket as an outcome of this spike?

**Comment by doug-s-nava** [comment]
@RakshindaAslam , no we have a meeting scheduled tomorrow afternoon to go over the document and determine next steps
