### ISSUE TITLE
Move BZDlabs to production and validate with CA

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#6640]

**Comment by GilmoreA6** [comment]
BZD labs moved to production in testing mode and message sent to CA asking how they would like test messages delivered for evaluation

**Comment by shy2cdc** [comment]
Email from Ellaison:

Hi @GilmoreA6 ,

 

Yes, for the CSV messages, please do use CDPH00085 in place of the CLIA and send the prod messages for us to review to our test environment.  Since we are currently getting a fair amount of data in our test environment, it would be helpful to know when you send the messages and the accession numbers which will make it easy for us to locate and review them. 

 

I’ve added Teddy Fries on this email chain and she or one of her team members will be performing the review.  I’ve also cc’d Vanessa for awareness as she is familiar with ReportStream CSV uploads as well. 

 

Thanks,

Ellaison

**Comment by GilmoreA6** [comment]
Hi All,

We have successfully received the file in production and are working with the state of CA DPH to review and make sure it meets their criteria. This is the last step of onboarding. As soon as CA lets us know everything looks good, we can turn you on for full production.

Thank you and I will be in touch as soon as I have a confirmation from CA.

-James

**Comment by GilmoreA6** [comment]
email to CA-PDH:
Hi all,

Apologies for the long delay in this as it took us more time than expected to get the sender fully onboarded to our production environment. We now have a few production messages for the sender that are ready for review (these will contain actual PHI/PII). Given that we have now transitioned to our production feed pointing to SaPHIRE instead of CCRS should I send these to the SaPHIRE production feed or the CCRS test feed? (It looks like we do not yet have a SaPHIRE test feed set up).

Thanks,

James

**Comment by GilmoreA6** [comment]
CA respone:

Hi James,

 

Thanks for the update. 

 

We would like to review using our SaPHIRE test system.  Can you send the file(s) via secure email so we can play them into the correct test system?  Teddy or her team can provide comments after they review the messages. 

 

Kind regards,

Ellaison

**Comment by GilmoreA6** [comment]
Sent to test system for CA and awaiting review
