### ISSUE TITLE
Usability Test for ValueSet feature

### ISSUE THREAD

**Issue by RakshindaAslam** [CDCgov/prime-reportstream#6787]
## Problem statement

Perform usability test for the ValueSets MVP built for O&O admin team to identify:
- Satisfaction level with the MVP as delivered
- Issues/challenges with the UI/functionality of the feature
- Enhancement requests/if any

## Acceptance criteria

Performed usability test for the ValueSets MVP built for O&O admin team to identify:
- Satisfaction level with the MVP as delivered on a scale from 1-5 with both quantitative and qualitative feedback
- Issues/challenges with the UI/functionality of the feature, if any
- Enhancement requests/if any

## To do

- [ ] Walk-through and verify current feature on staging, prep questions based on the current state
- [ ] Share interview questions/plan with product & eng (and include additional input requested)
- [ ] Schedule time with at least 2 O&O users (separately, preferred) Ideally calls have 1 designer/researcher facilitating and 1 experience engineer

**Comment by RakshindaAslam** [comment]
@a-chappelear - new ticket for usability test for Valuesets - needs to be pre-refined

**Comment by a-chappelear** [comment]
Added a few to-do's!

**Comment by a-chappelear** [comment]
Ott scheduled for Wed (hoping to schedule with Jorge)
[Ott script/feedback](https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Team%20Documents/Experience%20Team/UX%20Research/3.%20UX%20Research%20Projects/Value%20sets/Value%20Sets%20-%20Ott.docx?d=wa1e619a814bc4c73a61da8f1284c4fe6&csf=1&web=1&e=EBBZsH)

**Comment by a-chappelear** [comment]
@RakshindaAslam @doug-s-nava 

Take-aways and next steps from O&O:

1) Many were not aware the feature was available to use. Was behind a feature flag as well. O&O will continue to review the feature as is and provide more feedback.

However, based on the demo I showed today - some valid points were raised

2) Value sets as it is now, only let you edit core values. I remember it being discussed that that was the first step/scope of an "mvp" - but there was also discussion on potentially adding the option to "add new" values later. (ie. the add new button is there, but not a thing yet!)

Core values do not change that often, but the need to add or create ones do and for this to be useful, that should be considered as a next step.

3) It is not clear in the UI or as documentation - what happens if a user edits a value, while at the same time someone could also edit the same value in code and NOT in the UI. Does one overwrite the other and vice versa? 

4) We do have an "updated by" line in the UI, but it's not clear what was updated (which code/field) Or really, the ability in the UI to surface the "history" of a change

5) There is a concern it is too easy to edit a field, make a mistake, and potentially cause a breaking change. We should explore the ability to add a type of "warning" or other confirmation of the change.

**Comment by doug-s-nava** [comment]
- The add new button should work to add new values to existing data sets. Did you see otherwise in the testing?
- value sets are based on the lookup table system, which means that each change to any value in a value set creates an entirely new version of the table. The implications for overwriting data there is that each change creates a new version, and so previous versions are retrievable (though that would be a more involved process). I know there are some processes here driven by CSV files, though, is that what the `change in code` scenario is speaking to? I think that a change to a csv would overwrite changes made in the UI.
- a history could happen by displaying different versions of the value set. since the entire value set is recreated on each update, there's no simple way to speak to what was updated without looking at a diff from the previous version
- agree on the idea of a warning. I think I brought this up during initial development and it was shelved as a later improvement. But it's later now, so let's do it

**Comment by a-chappelear** [comment]
I created a ticket for adding the warning or type of confirmation. I did not see the new added at the bottom of the table - am wondering if that "new" row could be added to the top? Will wait to see if O&O continues to use the feature as is and has any further feedback.
