### ISSUE TITLE
COVID Check Today - sender setup

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/prime-reportstream#6806]

**Comment by jbiskie** [comment]
Sender is configured in staging and production. Waiting for sender to supply their keybase.io username.

**Comment by sliu1000** [comment]
Update from User sent on 9/29/2022

Hi Joel,

Thank you so much for reaching out. I apologize for the delayed response. I have been a bit out of the office last week, this week and next week on paternity leave. I'm working a little bit here and there, and will try and get the task work caught up on this project as soon as possible. It will most likely be mid to end of next week. Thank you for your patience in working with me on all of this.

Ryan

**Comment by BerniXiongA6** [comment]
Ryan / sender is on paternity leave -- will re-assign to engr when Ryan returns cc: @BerniXiongA6

**Comment by jbiskie** [comment]
Staging and prod keys are in Azure.

**Comment by sliu1000** [comment]
We have not reached out to them since October after Joel left. I'll send a follow-up email.

**Comment by sliu1000** [comment]
Reached out to Sender on next steps:

Report Stream (CDC)
Ryan Nelson <ryan@covidchecktoday.com>
brandoncanniff@navapbc.com;Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR);lafredahoward@navapbc.com
Hi Ryan,

I'm just following up on next steps.  Please let us know if you are no longer interested and we can close out this request.

Best regards,

Sharon
The ReportStream Support Team

Contact us at reportstream@cdc.gov

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Friday, February 10, 2023 11:00 AM
To: Ryan Nelson <ryan@covidchecktoday.com>
Cc: brandoncanniff@navapbc.com <brandoncanniff@navapbc.com>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>; lafredahoward@navapbc.com <lafredahoward@navapbc.com>
Subject: Re: Report Stream Patient Data Format and API Question
 
Happy Friday Ryan,

I hope you are adjusting well to from Paternity Leave - return.  As we discussed a few weeks ago please provide availability to discuss next steps with the sender onboarding process.

Best regards,

Sharon
The ReportStream Support Team

Contact us at reportstream@cdc.gov

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

From: Report Stream (CDC) <reportstream@cdc.gov>
Sent: Thursday, January 26, 2023 12:18 PM
To: Ryan Nelson <ryan@covidchecktoday.com>
Cc: brandoncanniff@navapbc.com <brandoncanniff@navapbc.com>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>
Subject: Re: Report Stream Patient Data Format and API Question
 
Hi Ryan,

Great to hear from you! I'll reach out again during the week you return.

Best regards,

Sharon
The ReportStream Support Team

Contact us at reportstream@cdc.gov

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

From: Ryan Nelson <ryan@covidchecktoday.com>
Sent: Thursday, January 26, 2023 11:17 AM
To: Report Stream (CDC) <reportstream@cdc.gov>
Cc: brandoncanniff@navapbc.com <brandoncanniff@navapbc.com>; Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR) <rut5@cdc.gov>
Subject: Re: Report Stream Patient Data Format and API Question
 
Hi Sharon,

Thank you for reaching out. I will be out of the office until 02/02/23. I would very much like to connect with you and your team to move forward with the onboarding once I am back in the office.


Ryan
Sent from my iPhone

On Jan 24, 2023, at 5:42 PM, Report Stream (CDC) <reportstream@cdc.gov> wrote:

﻿
Hi Ryan,

It's been a while since we've last reached out.  Can you please advise if you'd like to move forward with ReportStream onboarding or close-out the request?

Best regards,

Sharon Liu
The ReportStream Support Team
Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by GilmoreA6** [comment]
Message sent to sender

"Hi Ryan,

Just wanted to check in. Were you able to create a Keybase account, or would you like me to send via encrypted email?

Thanks,

James"

**Comment by GilmoreA6** [comment]
Hi Ryan,

I have sent you a keybase message with the x-functions-keys that you will use to send to our staging and production systems

Please find the example curl commands below. The "x-functions-key" values should be replaced with the secrets in the keybase message. You can find information on sending to us in the ReportStream Programmer's guide (https://reportstream.cdc.gov/assets/pdf/ReportStream-Programmers-Guide-v3.0.pdf). Please ensure to never send PII/PHI to our staging environment. Only mock data should be sent to this environment. 

Your organization name is "covidchecktoday" 

Example curl command staging:

curl -X POST -H “client:covidchecktoday” -H “content-type:text/csv” –data-binary “@./covidchecktoday-nonPII-data.csv” -H “x-functions-key:<staging-secret-goes-here>” https://staging.prime.cdc.gov/api/waters

Example curl command production:

curl -X POST -H “client:covidchecktoday” -H “content-type:text/csv” –data-binary “@./covidchecktoday-prod-data.csv” -H “x-functions-key:<prod-secret-goes-here>” https://prime.cdc.gov/api/waters


Thanks,

James
