### ISSUE TITLE
MO - MO DHSS COVID-19 Result Reporting - CDC PRIME - Production Validation Errors

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6890]
Email from Jake:

Good morning!

We received a message over the weekend missing some data.  Would you mind investigating and re-submitting the file(s)?

Filename:  covid-19-0bad5f28-4d82-475d-86cf-33196314ef0d-20220930192053

MSH-10:  `beb6add4-9b77-43e0-94e6-1dd032f388bc`

MSH-10:  `41e5b0cd-d06d-424e-a746-b5aa343a8a83`

MSH-10:  `21628282-174b-4072-9a45-48f257305832`

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerOrderNumber.EntityIdentifier Description=Required field missing

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.PlacerOrderNumber.EntityIdentifier Description="Required field missing

Please let us know if you require any additional information.  Thanks.

Jake

**Comment by oslynn** [comment]
2022-10-03: Requested Intrivo to resubmit those messages with those missing fields.

Good After Noon, Karim,

The following messages were missing ORC-2.1, ORC-2.1, ORC-2.2, ORC-2.3, ORC-2.4 and OBR-2.1, OBR-2.1, OBR-2.2, OBR-2.3, OBR-2.4.

MSH-10:  beb6add4-9b77-43e0-94e6-1dd032f388bc
MSH-10:  41e5b0cd-d06d-424e-a746-b5aa343a8a83
MSH-10:  21628282-174b-4072-9a45-48f257305832

Would you please resubmit them to ReportStream with those fields.

Very respectfully,
-Ott Sathngam
CDC SWE.

**Comment by oslynn** [comment]
2022-10-03: During the investigation of those missing fields.  I found 748 messages from Intrivo are missing ORC-2.1, ORC-2.1, ORC-2.2, ORC-2.3, ORC-2.4 and OBR-2.1, OBR-2.1, OBR-2.2, OBR-2.3, OBR-2.4.  This need to be discussed in 16 mins standup.

**Comment by jbiskie** [comment]
Couple notes on this: Intrivo is a RADx MARS sender (OTC). ORC/OBR-2 are not required according to the spec.

**Comment by BerniXiongA6** [comment]
@oslynn need to verify if it's been resent

**Comment by sliu1000** [comment]
Hi @oslynn - 10/21/2022

Jake from Missouri sent an email requesting the investigate and re-submit the below file due to missing data. It looks like the sender is Intrivo and fields that are missing fields may be optional (please see Joel's note above).

Good morning!

We received a message early this morning missing some data.  Would you mind investigating and re-submitting the file(s)?

Filename:  covid-19-c9b3cefe-3507-4a64-b637-bacaf672b0bb-20221021092001

MSH-10: 859f0201-965e-41da-9ae9-386407bb4dd4

PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerOrderNumber.EntityIdentifier Description=Required field missing

PATIENT_RESULT[0].ORDER_OBSERVATION[0].OBR.PlacerOrderNumber.EntityIdentifier Description="Required field missing 

Please let us know if you require any additional information.  Thanks.

Jake
