### ISSUE TITLE
Aspira Health Onboarding – Go Live Coordination

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6899]
### Acceptance Criteria 
- [ ] Contacted sender to confirm when they want to start sending  
- [ ] Introduced sender to the Customer Support form and CC: the Ops team (at least Sharon Liu and Berni Xiong)  
- [ ] Adjusted final settings:  
     - [ ] Modified organization.yml and created yamlitos  
          - [ ] Customer status = active  
          - [ ] For HL7 senders, schemaName: hl7/hl7-ingest-covid-19-prod 
     - [ ] Modified prod settings table  
     - [ ] Modified staging settings table 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender and ops team 
- [ ] RS team member who originates this ticket: add dependencies:  
     - [ ] Aspira Health Onboarding – Create Org and Sender Settings 
     - [ ] Aspira Health Onboarding - Validate Test Files 
     - [ ] Aspira Health Onboarding – Testing in Staging and Prod 
     - [ ] Aspira Health Onboarding – Validate Receiver 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Sender" 
     - [ ] Epics: #6972

**Comment by rnz6** [comment]
Update on 1/4/23 as of 12:55pm: Followed up with William Albanese if still interested, sign TOS and send test file to validate.... awaiting response.
 
Email from Christopher Decker on 1/4/23 and 9:43am

Good Afternoon,

We have a lab, Atracare, who has reached out to us about reporting labs via HL7 messaging. We directed them to Prime. We have been in contact with their representative, William Albanese; however, we wanted to reach out to Prime/reportstream to see where they may be in the onboarding process. Because they perform a substantial amount of Covid testing, we would like to get this facility onboarded as soon as possible.

Mr. Albanese did mention that Prime gave them  syntax to plug into Athena (their EMR system), but have not received any other updates.

Please let me know if there is anything I can do to help assist this process so Atracare can begin reporting via HL7 as soon as possible .
 
Thank you so much and have a great day!
 
Christopher Decker
Management Analyst III
Delaware Department of Health and Social Services
Division of Public Health
Jesse S. Cooper Building
417 Federal Street, Dover, DE 19901
Phone: (302) 744-4949
Christopher.decker@delaware.gov
