### ISSUE TITLE
Vault Onboarding – Testing in Staging and Prod

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#6956]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [ ] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add dependencies:  
     - [ ] [name of company] Onboarding – Create Org and Sender Settings
     - [ ] [name of company] Onboarding - Validate Test Files 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops," "Sender"
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
email to Vault and redox (integration service) 

"Hi All,

Wanted to check in and see there any questions regarding the LIVD values and also see if there was a decision on token based authentication vs. shared-secret. I am happy to set up a meeting if there are any questions that you feel would be more easily addressed in real-time communication. 

Thanks and happy weekend!

-James"

**Comment by shy2cdc** [comment]
Email from Tara:

Hi James,

I sent your response back to my developer and he responded with:

 

Based on the programmer’s guide, it looks like we would want to follow the steps on pages 9-11 and submit a public key to reportStream to enable use to use a generated JWT. We have an auth strategy called SMARTBackend that will probably allow us to do what they’re asking.

According to the guide they should have supplied us with a client ID: (Page 9)

As part of the onboarding process, the ReportStream team will pre-configure ReportStream with your client information and give you a unique client-id.

 

 

-- 

Tara Brocke

**Comment by shy2cdc** [comment]
Email from Tara:

Hi James,

Outlook wouldn’t let me attach the public keys, so I’ve put them in this secure link:  https://redoxengine.sendsafely.com/receive/?thread=XP8F-DDFA&packageCode=lDUz0iCYMlSUIEsZs702lOgpUVVFntkqq0gj21i6tZ0#keyCode=DAbX0fC0to9kvxCAci6hdKZRE0YkLf0oO6LX-ChgwwI

 

Vaultppublickey509.pem is prod

Vaultspublickey509.pem is stage

(notice the difference after vault – p or s – it was a terrible naming convention – sorry!)

**Comment by shy2cdc** [comment]
Email from Tara:

Hi James,

It looks like we may need some help.  Are you seeing any messages hit your endpoint? 

 

We are trying to query a token request, our paramaters are:

 

grant_type=client_credentials&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjU5MTY1YTRlLTcwMDctNDY3Yy04YzgwLTk0NjJmNDI4NzFmMyJ9.eyJpYXQiOjE2NjYzNjM1MzIsImV4cCI6MTY2NjM2MzUzNywiYXVkIjoiaHR0cHM6Ly9zdGFnaW5nLnByaW1lLmNkYy5nb3YvYXBpL3Rva2VuIiwiaXNzIjoidmF1bHRoZWFsdGgiLCJzdWIiOiJ2YXVsdGhlYWx0aCIsImp0aSI6ImE3YjFjYWY5LWQwMzUtNGEwYy04MzVlLTViMDViNDFmMzI1OCJ9.Cp0ZzxpP6g1BOkmOF_QfAXOax5kQQqavKsqvbVD1Wnf132d7jI2v0Ko3aYjeadjynSoQU6NAnOqGGJSvgh44xEjV-SGhxBroLjHjrfXIw6rjGtnIjWRlu0vSooGICaSYRd1MD50nBw2EbP65A2jSsSfsFTtLSCdhges0NNRfYeyw8Mg67aAJdDbE-U1RMFxLcmj7Nd9WcXAqI0GNSO6quDFuXig640CpNC_PJxiYusShMKV4hiOA1Tr3bwK4JejjaOOaGT8OIx0mi8irLtICDZMwYTRQnVNp5_yRm_lGXdRXd5fX5U6MHOzAFy8LZPKhS6zjgU0dniCTXV0qESK2cQ&scope=vaulthealth.default.report

 

content-type is application/x-www-form-urlencoded

 

We are receiving a 401 error response.

-- 

Tara Brocke

**Comment by GilmoreA6** [comment]
10/21 - working through issues with OAuth

"Hi Tara,

just to clarify, you are getting a 401 when attempting to get a bearer token? Since it's a 401  (unauthorized) and not a 400 (error) there are a couple of likely candidates.


1.) Try using a scope of "vaulthealth.*.report"

If that scope doesn't work....

2.) You are attempting to POST to the staging environment and not the production environment correct?

example:

curl -X POST -H "content-length:0" "https://staging.prime.cdc.gov/api/token?scope=vaulthealth.default.report&grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:cl ient-assertion-type:jwt-bearer&client_assertion=<token-signing-secret>

3.) Are you using the private key pair for staging and not prod to generate the signed JWT? 

(also possible that I mixed up the public keys when loading to our environment which I will check)

4.) In the header and payload for the JWT can you make sure that the "kid", "iss"  and "sub" are "vaulthealth.default" and the "aud" is "staging.prime.cdc.gov"?

Example:

{ "header": 
      { "kid": "vaulthealth.default", 
       "typ": "JWT", 
       "alg": "RS256" 
       }, 
      payload": { 
       "iss": "vaulthealth.default", 
       "sub": "vaulthealth.default", 
       "aud": "staging.prime.cdc.gov", 
       "exp": 1666418613, 
       "jti": "4b713fcd-2514-4207-b310-620b95b749c5" } }"

**Comment by sliu1000** [comment]
Update from Sender:

Hi James! 

Looping in the Vault Engineering team here for support. The team has looked into the LIVD value change and found that since PRL's test does not have an EUA, it's not in the list provided for mapping. We're wondering if there is another value we can place in OBR-4 if there is no EUA and there is no testkit Name ID in the mapping list?

Thanks! 
Julia

**Comment by sliu1000** [comment]
Update from Sender on 10/26/2022 at 6:54 PM:

Hi, 

The LOINC Result Code for this test is 95425-5 and the LOINC Order code is 95826-4 (SARS-CoV-2 (COVID-19) N gene [Presence] in Saliva (oral fluid) by NAA with probe detection). I misread the previous question as the collection device instead of test device — my apologies. We've been asked to send the corresponding Testkit Name ID for this test, which we can't find in the LIVD mapping file. 

Thank you!
Lindsey Snyder

10/26/2022 - 3:26 PM
The test device is the Spectrum saliva tube (SDNA-1000 Saliva Collection Device), which is FDA approved and used for a number of tests. This particular RT-PCR test is run by ReOpen Diagnostics LLC d.b.a Pandemic Response Lab. The EUA application is still pending for this test. 

I'm working with our engineering team on this update to support state reporting pipelines, and just need to know what to report for OBR-4 in the event that there is no EUA. 

Thanks so much,
Lindsey

**Comment by sliu1000** [comment]
Update from Sender: 10/28/2022

Hi James,

Thank you for the detailed response! Regarding the EUA for PRL's test, they have applied for one, but the regulatory window was closed before they were approved. PRL submitted for EUA on September 9, 2020 and the FDA announced they would stop reviewing LDT EUAs on October 9, 2020. For other states we have automated, as long as an EUA was applied for and is being sought out, we have been able to use ‘LDT’ (Lab Developed Test) in the EUA-related field (OBX-4) as long as it is structured properly. Let me know if there is a solution there since we want to be able to automate this reporting process if possible!

Thanks,
Lindsey

**Comment by GilmoreA6** [comment]
Waiting for Response from CDC about how to handle non LIVD table tests

**Comment by GilmoreA6** [comment]
Email sent to Megan regarding LDTs 11/17/2022:

Hi Megan,

I appreciate you running this by whomever can help us out. In the past our response to senders has been that we will only accept data for COVID-19 tests that have an EUA or other FDA authorization and have an entry in the LIVD SARS-CoV-2 LIVD table. This initially worked really well as all tests had to get EUAs at the beginning of the pandemic and there was an umbrella EUA in effect for LDTs developed by labs certified to perform CLIA high complexity tests.

More recently, that requirement was lifted for LDTs as the FDA has made changes to how they are handling new covid-19 tests. Many of these laboratories have submitted their tests for an EUA but do not have a timeline from the FDA on when (or if) that EUA will be approved. In the meantime they are needing to report these results to STLTs and currently we do not allow them to do that through ReportStream. 

Our ask is to find out if there should be an exception made for LDTs or if we should continue with our current policy of only accepting tests on the LIVD table. If the latter, is there some official language that we can include in our response to these senders?

Thank you,

James

**Comment by LaFreda1** [comment]
@GilmoreA6 What are the next steps for this ticket?

**Comment by LaFreda1** [comment]
Closing this ticket due to the timeframe We will reopen if needed.
