### ISSUE TITLE
Create document of PHD contacts

### ISSUE THREAD

**Issue by fmccaf1** [CDCgov/prime-reportstream#6975]
## Problem statement

Let's start building up a resource with contacts we can connect with for ongoing research.

## What you need to know

Rakshinda's work in August kicked us off with this work:

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/3298164b-3a5f-4186-abf2-fef9cf85d59b)

## Acceptance criteria
 
- [ ] Create living document in Sharepoint

**Comment by victorialb-usds** [comment]
Here is a list of who got the CX survey - https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/Shared%20Documents/PRIME%20ReportStream/Design%20and%20Research/Florida/RS%20CX%20Survey_Likelihood%20to%20Refer%20Research%20January%202022/Tracking%20Survey%20Distribution/Copy%20of%20ReportStream%20Directory%20-%20For%20CX%20Survey%20as%20of%20April%2014%202022_for%20Tracking.xlsx?d=wad10f4176f104bfeb5696c938588bdb7&csf=1&web=1&e=PTGKMj 

Might be a good input. Then the research done with PHDs this summer CA
https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B9AA07812-682B-42B6-A908-B38059A1C3C3%7D&file=STLT%20Facing%20Feature%20Research%20-%20IL%20-%202022.08.17.docx&action=default&mobileredirect=true

https://cdc.sharepoint.com/:w:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B8E61B085-925B-43EB-A4F3-56AE5D26FAFA%7D&file=STLT%20Facing%20Feature%20Research%20-%20CA.docx&action=default&mobileredirect=true

There was one more.

**Comment by victorialb-usds** [comment]
Here is the research contact tracker --need to add that after any research interaction people log it in here. https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B532DCD82-BFD1-4AB7-82A2-83EF8C8F788A%7D&file=Research%20Tracker%20(updated%2020221013).xlsx&action=default&mobileredirect=true&cid=b086d346-0557-4f92-830f-59b6dc1ecbc4

**Comment by victorialb-usds** [comment]
Victoria is working with PHDI to learn about the panel they are creating and how we can have a PRIME wide panel so that we easily pull up and segment and reach out to users for ongoing research. Question? Do we want to be tracking out internal users too to know who we talk to about what - for sustainability and capacity building at CDC?

**Comment by victorialb-usds** [comment]
@fmccaf1 we are talking this week. I would like to ask if you think we need to be tracking internal users.

**Comment by victorialb-usds** [comment]
noting that in the doc shared by Rakshinda there was a suggestion of doing on ongoing focus group @HeatherRienks can we talk about this at the next sync with o and o if this is a good idea - what purpose it serves - I dont want to leave the folks talked to this summer hanging. with some new researchers coming on we might want to have capacity but there could be research ops around this so that we have a way of setting the agenda for each convening/focus group. CC: @fmccaf1 @drew-usds
