### ISSUE TITLE
Change error code "Mo intervention required" to more appropriate verbiage

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#6989]
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To Do
- Let's refine this ticket before bringing it into the sprint -- AC and other info need to be fleshed out further. Thx, BX
## To do

- [ ] ...

**Comment by brandonnava** [comment]
@chris-kuryak @arnejduranovic I think one of your two teams was improving error codes. Did we ever get "Mo intervention required" removed from the error messaging? I wanna say yes but double checking.

**Comment by arnejduranovic** [comment]
@brandonnava I don't remember dealing with such messaging and, from a quick search, it still appears to be in the code.

**Comment by chris-kuryak** [comment]
@brandonnava @arnejduranovic I believe there are two steps of API Errors Communication: 
- the codes (already completed by Arnej)
- the messages displayed when a code is received (responsibility of Experience team)

I believe this is an error message issue.
#7944 is our open issue to update the Error Messages from the new API Error Codes, and then #7945 is to implement those changes.

@stephenkao Can you confirm which code/error this "Mo intervention required" is being reported on? And then add an AC in #7945 to ensure it is changed/removed in our upcoming update?

**Comment by brandonnava** [comment]
Thanks for the clarity @chris-kuryak 

Once you and @stephenkao get the Mo error spec'd on your ticket let me know and I'll close out this one

**Comment by stephenkao** [comment]
@chris-kuryak Like Arnej said it still exists in the code [here](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/SendFunction.kt#L106) and [here](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/src/main/kotlin/azure/WorkflowEngine.kt#L529), but it looks like the error is only recorded in the `action.action_result` column for internal purposes.  From the looks of it, this can happen if there's a critical error in the Send step or there have been 5+ errors in the Process...though I don't think we're surfacing this to anyone other than admins on the Last Mile Failures page:

<img width="1272" alt="Screenshot 2023-01-25 at 20 14 19" src="https://user-images.githubusercontent.com/2421042/214733246-014e69fe-4e9e-477b-b9e2-f615a0851597.png">

(This is just from my manually triggering an error during the Send step locally, not on a live environment!)

I might be missing something, but I don't think this is an "error code" situation since it doesn't feel like we'd want to surface this error to external users.  Like I said above, it feels more like an internal error message that we'd want manual intervention to resolve 🤔 We can definitely take out the "Mo intervention needed" part if needed, though -- that'd be really simple!

@jimduff-usds @arnejduranovic Does this sound right or am I incredibly incorrect?

**Comment by chris-kuryak** [comment]
@brandonnava See Stephen's response above. Looks like this isn't an error code shown to external users, but rather an internal error code where manual intervention is required. 
Is there different verbiage you'd like it to show?

**Comment by chris-kuryak** [comment]
@brick-green @GilmoreA6 @oslynn @LaFreda1  @adegolier 
Please develop new verbiage on what you'd like to see on these two errors.

**Comment by LaFreda1** [comment]
@chris-kuryak the team and I discussed this ticket yesterday during sprint planning. The appropriate verbiage should be: "Manual Intervention Required."

**Comment by brick-green** [comment]
We're gonna take this so we can remove the experience label if it shouldn't be on the WebX board?

**Comment by LaFreda1** [comment]
Thanks @brick-green

**Comment by stephenkao** [comment]
Thanks, Brick!  Feel free to move/update however you'd like if you're taking it :)

**Comment by chris-kuryak** [comment]
Thanks @LaFreda1

**Comment by LaFreda1** [comment]
@GilmoreA6 what do we need to close this ticket?

**Comment by GilmoreA6** [comment]
@LaFreda1 I 've made the change to the error message and am working on how to write a test for this since it looks like a unit test for this function was never written.

**Comment by LaFreda1** [comment]
@kant777 please see James if you have any questions
