### ISSUE TITLE
Osang LLC / Stone Labs Onboarding – Create Org and Sender Settings  

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7091]
### Acceptance Criteria 
- [x] Added to organization.yml and create yamlitos  
    - [x] Customer status = testing  
    - [x] For CSV OTC senders, schemaName: csv-otc-covid-19

- [ ] Added to prod settings table  
- [ ] Added to staging settings table  
- [ ] Key exchange  
    - [ ] 1. Shared secret  
         - [ ] Created API keys in Azure staging   
         - [ ] Created API keys in Azure prod  
         - [ ]  Sent API keys to Sender via Keybase  

FYI: this ticket can be completely concurrently with “Validate Test Files” ticket for this API sender 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Sender" 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by BerniXiongA6** [comment]
Hi @jbiskie I don't know if this step was completed yet because there wasn't an individual ticket until now. If this step has been completed, please feel free to comment and close it. Thanks! cc: @MauriceReeves-usds

**Comment by jbiskie** [comment]
Sender settings are ready and pushed to a branch, onboarding-ops/7091/osang-onboarding. Just need to create the PR.

Requested keybase username from Osang.

**Comment by sliu1000** [comment]
Updated Communication:

Dear Joel,

We appreciate your detailed feedback for the sample file and corrections.

Concerning each item, I'd like to add some firsthand comments or inquiries.
(Please refer to text in blue)

Please use comma delimiters between fields. The sample you sent is tab delimited
            -  We will correct this
The date fields are in scientific notation, so they've lost some precision. Please ensure you're sending the full date/time string.
            -  We will correct this
One field was missing, testing_lab_specimen_received_date. This is in the spec between specimen_collection_date and test_result_date
            -  We will correct this
date_result_release is missing the last letter, it should be date_result_released
            -  We will correct this
The field testing_lab_clia should be either 00Z0000014 for OTC, 00Z0000015 for prescription
            -  Considering the proper code again, 00Z0000015 should be the one for non-lab reporting use. 
I noticed some ordering provider fields were filled in. If this was intended as a prescription, please also send the provider's NPI in ordering_provider_id. If this is OTC, leave all of the ordering provider fields blank.
            - We will be working on this one.
patient_id: Our spec shows that this is optional, but as I was testing your file, I see that when it's omitted, it presents a problem for us with OTC. Can you provide a value here? If you don't have a true patient identifier, the same value that you're sending in the accession_number would work great.
            - We will fill in a value in the field.     
patient_first_name and patient_last_name: I know you're omitting PHI for the sample, which is fine. Just a heads-up, you'll need to include a value when you actually test with the endpoint.
            - We will fill in values in the fields. 
               However,  one question is whether this is in accordance with "COVID-19 Pandemic Response, Laboratory Data Reporting: CARES Act Section 18115" ( https://www.cdc.gov/coronavirus/2019-ncov/downloads/lab/HHS-Laboratory-Reporting-Guidance-508.pdf)
               On Page 6 of the document, there is a citation about de-identification and I wonder this doesn't have to be applied here.
There are a number of extra fields in your file that are not necessary for OTC. Please omit the following fields:
           - We will remove all those fields. 


On the app, we'll shortly work on correcting all these at once on the mobile app and keep you apprised.

Thank you very much and have a nice weekend!


Best regards,
Eric

----------------------------------------------
 
Eric (Mingoo) Song  
 
CEO / 대표이사
StoneLab Inc.
 
(e) president@stonelab.kr
(t) +82-70-8778-7450 
(m) +82-10-3925-5340


AI Research Center
306, Maeheon-ro 8-gil 47, Seocho-gu, Seoul

HQ Office
303, Daehak-ro 179, Yuseong-gu, Daejeon  



----------------------------------------------

The content of this email is confidential and intended for the recipient(s) specified in the message only.
It is strictly forbidden to use, acknowledge, redistribute, or share any part of this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and follow with its permanent deletion, so that we can ensure such a mistake does not occur in the future.






---- On Sat, 22 Oct 2022 07:16:33 +0900 Biskie, Joel (CDC/DDPHSS/OD/HITSSU) (CTR) <rtz3@cdc.gov> wrote ---

Hello again Philip and team,

I'm following up on the sample file. Here are the modifications I found that need to be made:
Please use comma delimiters between fields. The sample you sent is tab delimited
The date fields are in scientific notation, so they've lost some precision. Please ensure you're sending the full date/time string.
One field was missing, testing_lab_specimen_received_date. This is in the spec between specimen_collection_date and test_result_date
date_result_release is missing the last letter, it should be date_result_released
The field testing_lab_clia should be either 00Z0000014 for OTC, 00Z0000015 for prescription
I noticed some ordering provider fields were filled in. If this was intended as a prescription, please also send the provider's NPI in ordering_provider_id. If this is OTC, leave all of the ordering provider fields blank.
patient_id: Our spec shows that this is optional, but as I was testing your file, I see that when it's omitted, it presents a problem for us with OTC. Can you provide a value here? If you don't have a true patient identifier, the same value that you're sending in the accession_number would work great.
patient_first_name and patient_last_name: I know you're omitting PHI for the sample, which is fine. Just a heads-up, you'll need to include a value when you actually test with the endpoint.
There are a number of extra fields in your file that are not necessary for OTC. Please omit the following fields:
patient_preferred_language
N/A
comment
test_result_status
testing_lab_name
testing_lab_street
testing_lab_street2
testing_lab_city
testing_lab_state
testing_lab_zip_code
testing_lab_phone_number
pregrant
employed_in_healthcare
resident_congregate_setting
residentce_type
hospitalized
icu
reporting_facility_name
reporting_facility_clia
ordering_facility_name
ordering_facility_street
ordering_facility_street2
ordering_facility_city
ordering_facility_state
ordering_facility_zip_code
ordering_facility_phone_number


I've attached a copy of the test file after I made these edits and sent it through my local development environment, in the event it's useful for you to see an example. Please let me know if you have any questions. Once we get your keybase.io username that I mentioned in my other email, we can send you the API keys so you can start testing against our endpoints right away.

Have a great weekend,

Joel Biskie (Flexion, Inc.)
Integration Engineer
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by sliu1000** [comment]
Update from Sender:

Dear Joel,

Thanks for the clarification.

We've restructured the transmitting data protocol matching your guidance while considering the identification part.

Best regards,
Eric (Mingoo) Song

**Comment by sliu1000** [comment]
Update from Sender:

Dear Berni,

Thank you for the clarification of the below two issues.

1) We just noticed Joel that our mobile app's reporting data protocol has been reconstructed to meet the criteria.
2) The following is the keybase.io username:  https://keybase.io/osangllc
osangllc (Osang LLC) | Keybase
osangllc (Osang LLC) is now on Keybase, an open source app for encryption and cryptography.
keybase.io

Thank you again for your prompt cooperation.

Best regards,
Eric
