### ISSUE TITLE
WA - Wrong Jurisdiction For Result

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#7097]
User is Caroline Thomas.

The issue is as follows:

"WA DOH received a result from QUICKMED DIAGNOSTIC INC that we believe belongs to another health jurisdiction.
In this result, the patient address is in Tianjin and the ordering facility and ordering provider both have CA addresses.

If this result is indeed for WA, please let us know."

ReportID:  `00bdca40-e78b-437d-842f-2e52e6a46325` date 10/19/2022

**Comment by sliu1000** [comment]
Receiver from WA State is alerting us on another issue with Quickmed Diagnostic Inc sending data not belonging to WA State:

Report ID:
0b782214-b202-404f-81fe-a81cf35017d8

Original Communications:

We received a handful of messages originating from Quickmed Diagnostic Inc that have patient addresses in DC, but the state is listed as WA. We believe these results should be sent to DC rather than WA. Please confirm if these messages are intended for WA or not. If not, please let Quickmed Diagnostic to correct the states and send the results to the appropriate jurisdiction.

Thank you!

Message ID:

FTPCF2+833+20221102, P6BYNF+836+20221102, 93H5AP+837+20221102, V4VLYC+832+20221102, KKZ86T+839+20221102, GDQW63+838+20221102, 2WBG2P+834+20221102, CLJ2N8+835+20221102

Action:  Please confirm that these messages should be routed to DC instead of WA.

**Comment by sliu1000** [comment]
Hello,

The Sender was SimpleReport. I was able to figure this one out. I have requested SR to resubmit.

![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/74d149e4-93e5-42ab-b6f7-baff526af9d9)

**Comment by BerniXiongA6** [comment]
HI @sliu1000 we just got off our sync with WA Dept of Health today. They were wondering who would be resubmitting the messages? Laura King/SR was on the call and said that SR couldn't resubmit because these were CSV files, which they don't keep. Could you provide any updates you have on this ticket? Thanks so much!

**Comment by sliu1000** [comment]
@BerniXiongA6 

I've been requesting Quickmed to resubmit:

<img width="559" alt="WA-quickmed" src="https://user-images.githubusercontent.com/102377655/200403071-624fe5fb-ea85-424d-a1da-018d932e59e5.PNG">

![image](https://user-images.githubusercontent.com/102377655/200403226-7e49eb1c-2e92-4597-8016-305887771f8f.png)
