### ISSUE TITLE
Turn on duplicate detection for all senders

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#7150]
## Problem statement

Reportstream has an option to detect and ignore duplicate submissions. Turning this option on for senders will save processing time and resources in report stream in the event that errors occur in a sender system.

## What you need to know

Option in sender settings:

This is the default: `allowDuplicates: true`

All should be changed to `allowDuplicates: false`

## Acceptance criteria

- [ ] All senders have `allowDuplicates: false`

**Comment by TomNUSDS** [comment]
_**Verify behavior of `allowDuplicates: false`**_: Does it strip out duplicate tests from within bulk submissions or does it reject the whole submission?

Be prepared for extra work if the whole submission is rejected.

**Comment by GilmoreA6** [comment]
allowDuplicates: false does not strip out duplicate tests from within bulk submissions. The entire CSV file or HL7 batch message will fail if there is a single detected duplicate row. 

Interestingly, it also does not detect duplicates within a csv file or HL7 batch message in an inbound message, if those messages or rows have not already been submitted. This is because the way that duplicate checking is working is done by comparing the values in item_hash column on the item_lineage table in the database (fun: isDuplicateItem in DatabaseAccess.kt)

**Comment by GilmoreA6** [comment]
Decision was made to only turn on duplicate detection for senders who are sending a single message per file.
