### ISSUE TITLE
Color Onboarding – Testing in Staging and Prod

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#7630]
### Acceptance Criteria 
- [x] Sender has tested in staging and production 
- [x] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [x] RS engineer: update this ticket with comments with every interaction with sender 
- [x] RS team member who originates this ticket: add dependencies:  
     - [x] [name of company] Onboarding – Create Org and Sender Settings
     - [x] [name of company] Onboarding - Validate Test Files 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops," "Sender"
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
Update from Sender:

Hi James, 

Could you please check the 3 most recent messages I've submitted and confirm whether I've made the correct changes mentioned above? IDs for the messages are "`c222b1fe-8e37-46d1-926e-ef2c293bb26c`", "`0954f533-f519-4c70-bec5-3be08ef5a16d`", and "`67137bfb-d822-4e81-bf1b-3644ae4b85d3`". 

Please let me know if you need any additional information. 

Best, 

Nick

**Comment by GilmoreA6** [comment]
Review files from sender and graduated to production

**Comment by sliu1000** [comment]
Update from Sender:

Hi James, 

We turned on our message sending last night. So far, on our end, every request seems to have failed with a Read Timeout. I realized our timeout is set low (5 seconds) and plan to increase it, but are you seeing these requests on your end? 

I think at minimum we've successfully sent token requests and have received responses back from that endpoint, but not from the /waters endpoint. Are these APIs generally slower than 5 seconds? 

Also, we were wondering if when you send these records on to NY, you're designating them as test messages or whether they'll be treated as real records. 

Please let me know if you need any additional details from us. 

Best, 

Nick

**Comment by sliu1000** [comment]
Update from Sender on 12/23 @ 1:39 PM:

Hi James, 

Thanks so much for the info on timeouts. I'll adjust it to 30 seconds. Is the waters endpoint the preferred one since it's newer? 

Does this mean those 13 records were successfully processed? Are we good to start reporting to NY through ReportStream? Please let me know if we need to do any other testing or verification. 

I'll let NY know that we probably sent duplicate records, but is there any way for you to give me some additional identifying information about the 13 files you've got saved on your end? Perhaps the sample identifiers in SPM|1|D-XXXXXXXX 
This way I can make sure we know exactly what records we might've both manually reported and also reported through RS. 

All in all, this seems like great progress. Thanks for your continued support in getting us onboarded!

Best, 

Nick

**Comment by GilmoreA6** [comment]
Hi Nick,

I have asked NY what they require for us to move to production and will let you know as soon as I hear back. The 13 records were successfully processed in ReportStream, they were not yet sent to NY. If NY asks us to forward them for validation I will let you know which identifiers are sent.

The Waters endpoint is the preferred endpoint at this time.

Thanks,

James

**Comment by sliu1000** [comment]
Update from Sender:

Hi James, 

Happy New Year! Just wanted to check with you on the NY records status. We actually had alerted them a few weeks ago that they may be seeing a few test records come across from us.

Please let us know if you need any additional info from us or need us to send new messages or anything like that. 

Best, 

Nick

**Comment by shy2cdc** [comment]
Update from Sender:

James, 

You should've received a record at 3:11 PM PT. Let me know if this one message is sufficient, otherwise I'll have to send more on Monday. We've had low volume for NY and we had to be mindful about making changes headed into the weekend. 

On my end, I saw a successful response from the Waters endpoint for the first time. Increasing that timeout seems to have done the trick. 

Let me know what you need from me, and I'll make it happen first thing Monday so that we can hopefully move past the testing phase and start reporting for NY ASAP. We've got lots of other jurisdictions we'd love to start sending for as well once we know we're good to go. 

Best, 

Nick

**Comment by GilmoreA6** [comment]
Thanks Nicholas,

NY has confirmed your messages and we are good to move to full production. For other jurisdictions, we do not require you to go through the full process to validate with other STLTs before sending them to us, however there are a few jurisdictions that do ask for us to send them test messages before sending to their production system. They are NJ, WA and CA.

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi All, 

Answers below in red:

1. When we submitted the messages in question, ReportStream returned a 201 status to us with an errorCount of 0. I see warnings, but why is the record not rejected outright if there's a fatal issue with these LIVD values that have to match perfectly? Good question. I may need to bring this back to my group for some history because it does for CSV but not HL7. I will bring this up tomorrow morning with my larger group.

2. Could you describe where the failure actually happened? Did ReportStream attempt to send the record to NY and NY rejected it, or did ReportStream not attempt the send because of the issues with these values? This is the exact message we would have sent manually to NY that they would have accepted, so that's why I'm curious about where the failure is happening. Technically speaking it didn't which is why I didn't notice it at first until doing a deep dive into the production messages. As noted above it produced a warning and not an error, so it went through the system and onto NY. This is where the LIVD table requirement gets weird because according to NY there is nothing wrong with the messages. The LIVD table is a CDC requirement not one imposed on us by the other public health jurisdictions. We have noticed issues with this requirement and ReportStream is actively seeking guidance from our CDC stakeholders on whether this requirement is truly still needed at this stage of the pandemic.

3. Do you have to update our configuration to allow for individual rows/values in the LIVD table in our submissions? Or are we good to go as long as we're providing valid table values, even if they're for another lab, like the Broad. The only requirement is that the values have to match across a row in the table. There is no logic correlating sender to LIVD table row, as a lab/hospital system could use multiple different tests from different manufacturers. All 1000+ rows are considered valid for every sender.

4. Could you remind me again which of the values must match the LIVD table for submissions to be accepted? You called out the OBX-17 and OBX-18 values, but if there are other fields of particular importance, please let me know and I'll check on those as well. The relevant values are OBX-17-1, OBX-17-2 and OBX-18-1. In the LIVD table OBX-17-1 should match column M "Testkit Name ID", OBX-17-2 should match Column B "Model" and OBX-18-1 should match column O "Equipment UID"

Thanks,

James

**Comment by GilmoreA6** [comment]
This is a good example of where the LIVD table requirement is causing a headache as we have a sender who sent us production example of a message that in real life was accepted by a STLT (in this case NY) but because the test is not on the LIVD table we are saying it is not valid.

**Comment by sliu1000** [comment]
Update from Sender:

Hi James, 

That's great news! Happy to hear it. Thank you for the update. 

Just a couple questions for you now that we're good to go: 
1. When will we be in full production mode? Is it just a switch you all can flip at any time? 
2. Do you have any recommendations for us for the first week or so that we're reporting real results in prod? 
3. Will you be monitoring in the initial days after we go live and let us know if you see issues on your end? 

Great to know we don't have to coordinate for every state. We'll try to give you a heads up though if we're cutting over high volume states, even if they're not the ones you listed. 

Best, 

Nick
