### ISSUE TITLE
TX - Lab Errors missing LOINC CD in OBR-4 and OBX[1]-3 segments

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#7691]
## Problem statement
User states:

Hi,

Some ELRs from are erroring out due to missing LOINC CD in OBR-4 and OBX[1]-3 segments.

Accession nos.

PBHQRS5KG

PBT9WQW77

PB23Q3KS4

Please review the accession nos. above and make corrections to ELRs moving forward.

Thanks,

Asenath Onderi

Health Informatics Specialist IV

Public Health Informatics and data exchange group|LIDS

Texas Dept. of State Health Services

Asenath.Onderi@dshs.texas.gov

[Write a short description of what you want to achieve with this task]

For the errors to be fixed 

## What you need to know

The HL7 file name is CDCPRIME_11D2030855_20221214023527

and i can confirm OBR-4 and OBX 1-3 segments are missing

The lab is called QC labs, location Corpus Cristi TX.  

Submission date is 12/13/22 at 9:35:23 pm

## To do

Fix errors and resubmit data

**Comment by brick-green** [comment]
This issue was caused by a failure by the sender. So we will need to request that they fix the problem going forward then resend after it has been fixed to assure all messages are sent correctly. Here is a table to assist with clarifying the issue:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>


</head>

<body link="#0563C1" vlink="#954F72">



LIVD Column | LIVD Column Name | HL7 Field | Value Received from QC labs
-- | -- | -- | --
F | Test Performed Code | OBX-3.1 | 95209-3
M | Test   Kit Name ID | OBX-17.1 | Sofia 2 Flu + SARS Antigen FIA_Quidel Corporation
B | Model | OBX-17.2 | Sofia 2 Flu + SARS Antigen FIA_Quidel Corporation
O | Equipment UID | OBX-18.1 |  



</body>

</html>

The values sent in these four fields(OBX-3.1, OBX-17.1, OBX-17.2, OBX-18.1) need to align with exactly with values in the LIVD table. Those LIVD table columns are identified by the first two columns in the above table. The final column shows the values that we received from QC Labs. There is no record in the LIVD table that matches those values exactly.

**Comment by brick-green** [comment]
@Jcavallo7 These results were originated by QC Labs but reported to us through a vendor - Primary Health. Can you make the request to Primary Health to have this resolved based on the information in my last comment? Do you think my description was clear enough?

**Comment by Jcavallo7** [comment]
@brick-green Yeah it seems very clear to me, I'll send this right away.

**Comment by Jcavallo7** [comment]
Hello,

Texas DOH stated on 1/10/23:

"Thank you for the update! The ELRs continue failing due to the issues outlined below.

 

Thanks,"

**Comment by brandonnava** [comment]
@Jcavallo7 Any update here?

**Comment by Jcavallo7** [comment]
No updates from Andrew or their team on it. No information on the ticket they created either, nor were the details shared with us. Should I follow up?

**Comment by brick-green** [comment]
@Jcavallo7 Yeah I think a followup with Primary Health would be the next step. Looks like it's been about 2 weeks since the initial comm

**Comment by LaFreda1** [comment]
@Jcavallo7 Did we follow-up with Primary health?

**Comment by Jcavallo7** [comment]
Followed up with Primary Health, waiting for response.

**Comment by LaFreda1** [comment]
@Jcavallo7 can we follow up with Primary Health again? Thanks!

**Comment by Jcavallo7** [comment]
@LaFreda1 apologies, primary health gave an update 2/9/23:
*Hi Reportstream, 

My apologies for the delayed response. 

Our team corrected the record to show 'Sofia 2 Instrument_Quidel' in the equipment UID portion moving forward. We are basing this info on row 830 of the LIVD SATS COV2 2023-1-11 excel file. 

Hope this will resolve it. 

Thanks, 
Andrew*
