### ISSUE TITLE
Staging Error - HTTP 400 (Occurring every night for the last two weeks)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7731]
## Problem statement

Can someone help determine if there is a ticket for this/create one if there is not? This is generating an HTTP 400

## What you need to know

{"HttpMethod":"POST","TriggerReason":"This function was programmatically called via the host APIs.","Category":"Host.Results","FunctionExecutionTimeMs":"90.388","InvocationId":"b87ecfec-3004-41b2-ad16-f18c39675f3a","LogLevel":"Information","HostInstanceId":"1c698458-f0fb-49ff-b293-653618eec1c2","ProcessId":"24","FullName":"Functions.reports","HttpPath":"/api/reports"}

This is important to track down why because we are being alerted every night. If this should not be something Devops needs to know about it, please let us know and we’ll remove the alert. This is the definition:
| where toint(resultCode) >= 400
    and toint(resultCode) < 500
    and toint(resultCode) != 401

Feedback from Arnej:
I'm not sure how we would figure out who is making this request? HTTP 400 indicates a client error of some sort (malformed request syntax, etc.) so it seems like someone is sending bad requests? I can bring this up with 
@Jim Duff
 at standup today but it doesn't seem critical to me at this point

## Acceptance criteria

- Why is this occurring?
- How do we correct this?

## To do

- Assign to Engineer to investigate further.

**Comment by BerniXiongA6** [comment]
Hey @brandonnava let's bring this into stand-up so we can get more info in order to triage

**Comment by BerniXiongA6** [comment]
Per @GilmoreA6 -- there's a slack thread in DevOps channel -- this is caused by SafeHealth. James emailed SafeHealth to inform them to stop. cc: @brandonnava

**Comment by GilmoreA6** [comment]
Good Afternoon Santosh,

I am reaching out because it looks like over the last few weeks there may be an automated process on your side that is trying to POST to our staging environment and failing. We are seeing a large number of 400 errors occurring every night from Safehealth to our Staging environment. Is there a reason you are needing to send to our staging environment at this time and if so, could we help you troubleshoot the issue as it is causing alerts on our side due to the high number of failures.

Thanks,

James

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort ([PRIME](https://www.cdc.gov/surveillance/projects/pandemic-ready-it-systems.html))
