### ISSUE TITLE
WA - Incorrect Jurisdiction for tests

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7745]
## Problem statement

Caroline Thomas (caroline.thomas@doh.wa.gov) Washington State Department of Health	

User states:

WA DOH received a result that is most likely for another jurisdiction.

Issue: patient address in DC, state = WA, ordering facility and provider in CA
Message Date/Time: 12/20/2022 12:45:29 PM
Message Control ID: 1.67138E+15+213+20221220

MSH ID (For WA Records): 400019353

Please notify submitter that this result should be corrected and sent to appropriate jurisdiction.

## What you need to know

Results are from a different jurisdiction

## To do

Notify submitter that this result should be corrected and sent to appropriate jurisdiction.

SimpleReport Submitter Name: Action Urgent Care Inc. CLIA is 05D2078131

**Comment by shy2cdc** [comment]
Ticket from Caroline:

WA received a result most likely meant for another state.

Issue: patient address in CO, but state = WA; ordering facility and provider in CO
Message date/time: 12/20/2022 6:35:15 PM
Message control ID: `00032-22-352-0120+274+20221221`

Please review result with submitter, correct the address, and send to appropriate jurisdiction.

**Comment by BerniXiongA6** [comment]
Let's bring into a backlog refinement next week, what do you think @brandonnava ?

**Comment by brick-green** [comment]
Need to identify the sender then ask them to resend with correct address information.

**Comment by brandonnava** [comment]
@sliu1000 Is this something you can take on? Identifying the sender and asking for a resend? If you need an eng to find the sender lmk!

**Comment by sliu1000** [comment]
@brandonnava  - yes, will take a look at it now.

**Comment by sliu1000** [comment]
@Jcavallo7 Can you please do me a favor and reach out to two separate facilities that use SimpleReport to resubmit some data that may have been sent to WA accidently.  Please see below for more details:

(1) Please email the admin from Action Urgent Care regarding a test result submitted to WA with a DC patient address. Please ask them to make sure to submit the data to the correct state.

SimpleReport User/Sender: Action Urgent Care Inc. CLIA is 05D2078131
Advise the Admin to please make sure that the test result submitted by them on: 12/20/2022 12:45:29 PM for one of their results should have been sent to District of Columbia instead of WA State.  The patient resides in DC not WA.
-Message Control ID: 1.67138E+15+213+20221220

(2) Please email the admin from Southern Colorado Clinic (Another SimpleReport Reporter).

Advise the Admin to please make sure that the test result submitted by them on: 12/20/2022 6:35:15 PM for one of their results should have been sent to Colorado instead of WA State.  The patient resides in CO not WA.

Issue: patient address in CO, but state = WA; ordering facility and provider in CO
Message date/time: 12/20/2022 6:35:15 PM
Message control ID: 00032-22-352-0120+274+20221221

**Comment by Jcavallo7** [comment]
both were emailed with instructions for resubmission

**Comment by brandonnava** [comment]
Will close after sender confirms the resend and we can double check it went through @sliu1000 @Jcavallo7

**Comment by brandonnava** [comment]
@Jcavallo7 Do you know if resubmission was successful?

**Comment by Jcavallo7** [comment]
No record of successful verification, user was contacted, however is out of office.

**Comment by LaFreda1** [comment]
@Jcavallo7 Have we heard anything from the user? Thanks!

**Comment by Jcavallo7** [comment]
Will email user again to confirm verification, and hopefully I can update this ticket a bit faster.
