### ISSUE TITLE
Create Terraform Script to deploy existing Analytics queries/dashboard charts to production

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-reportstream#7869]
## Problem statement

We need to create a Terraform script to deploy our current Azure Analytics queries and dashboard charts to production.

## Background Info
- DevOps will create the Terraform

## Acceptance criteria

- [x] Dashboard in production has charts from #7625, #7626, #7629
- [x] Document the process of updating the Terraform configuration and share with Engineering

## To do

- [x] Work with devops to run script on staging and production

**Comment by kevinhaube** [comment]
@chris-kuryak Can we group in #7627 with this as well? That way Etan's ticket can just handle the React implementation and defining the query. cc: @etanb

**Comment by etanb** [comment]
+1 to that idea! Happy to work together to bring those analytics to life.

**Comment by chris-kuryak** [comment]
I think @penny-lischer is going to be performing the work on this issue as she refines this issue and add to it as she collaborates with the DevOps team (Jeremy Page).

So would it be better to just keep them as separate tickets but @penny-lischer and @etanb work alongside eachother as they do them?
Or @penny-lischer do you think it would be easier to just combine the tickets and y'all can work together on one ticker?

(I don't know enough about the work on these two, so I am going to leave it up to @penny-lischer and @stephenkao to provide feedback.)

**Comment by stephenkao** [comment]
I thiiiiink DevOps won't be able to provide support for a bit since they're working on a more pressing database change so if the query #7627 will be ready to go before then, my feeling is that it could be included in this first wave of Terraform updates.  @penny-lischer does that sound good to you?

Also, after we know how to make these Terraform changes, we won't need to separate the AI dashboard query work from the Terraform work in the future; both can just be grouped together in one ticket.

**Comment by penny-lischer** [comment]
Yes, sounds good to me.

**Comment by penny-lischer** [comment]
O&O ticket - https://github.com/CDCgov/prime-reportstream/issues/7871

**Comment by penny-lischer** [comment]
Documentation found here - prime-reportstream/templates/azdashboard_readme.md
