### ISSUE TITLE
Base10 Onboarding – 2. Testing in Staging and Prod

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#8720]
### Acceptance Criteria 
- [ ] Sender has tested in staging and production 
- [ ] RS engineer has determined the data is good enough and graduates Sender to send Prod data to receiver  

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add dependencies:  
     - [ ] [name of company] Onboarding – Create Org and Sender Settings
     - [ ] [name of company] Onboarding - Validate Test Files 
- [ ] RS team member who originates this ticket: make sure the following are included when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops," "Sender"
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
Update from Sender:

Hi Ott,

I was able to resolve some of the issues. I'm still encountering the following quality filtering messages below, but the "overallStatus" already says "Waiting to Deliver". Let me know if these issues DO indicate an unsuccessful submission.
"For il-phd.elr-antigen, filter doesNotMatch[processing_mode_code, T, D] filtered out item 1585",
I resolved this by making MSH-11 blank
"For il-phd.elr-molecular, filter matches[test_type, Mol, Breath] filtered out item 1585",
not sure if this needs resolving since "overallStatus" is already "Waiting to Deliver"
"For il-phd.elr, filter allowNone[] filtered out item 1585",
not sure if this needs resolving since "overallStatus" is already "Waiting to Deliver"
I attached the HL7 file I sent and the response I got from ReportStream for reference.

Let me know what you think.
 
Regards,
Nicole

**Comment by Jcavallo7** [comment]
*update from user*

Hi Ott,

Re-sending this email so that everyone is cc'ed.

Thanks for the help. I was to resolve all errors for now. Let us know how we can move forward.

Regards,
Nicole

**Comment by Jcavallo7** [comment]
*update from user*

Hi Ott,

Attached is the WA message I sent to staging. I got the following response from staging ReportStream API:

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/e71ec224-07ce-4383-9611-8fae971257c1)

Regards,
Nicole

**Comment by oslynn** [comment]
email from WA response to validation;

Thank you Ott,

I have reviewed the message and structurally it is acceptable.  I have a few clarifying questions before onboarding this facility.

 

You state the testing facility is Base10 Genetics, however, I do not see that facility name in the report.  Instead, I see Cascade Park listed as ordering facility and performing org.  Is this expected?
Race and ethnicity are both listed as unknown and language is missing entirely.  Are you able to acquire this important demographic data?
Earlier in the email chain we agreed that unproctored/self-administered tests should not be sent to WA.  Are these unproctored or self-administered tests?
 

Sincerely,

Jenni

**Comment by oslynn** [comment]
Done

**Comment by Jcavallo7** [comment]
*update from user*
![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/13729964-192e-49c1-8e97-9339fa4fb170)

Hi Ott,

I tried sending an actual message to the ReportStream production endpoint and I'm getting this error from the response payload. Attached is the hl7 file I sent.

**Comment by oslynn** [comment]
@Jcavallo7 took care of this issue.
