### ISSUE TITLE
UT - Not Receiving Production Data

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#8827]
## **Problem Statement**
We received an email via the ReportStream box asking for us to send them production data for Utah.

## **What you need to know**
The State was onboarded around January 2023.  They said they have not received more data since the first file that was sent over.

## **Acceptance Criteria**

User would like us to send them production like messages for review.

## **To Do**
NA

## **Additional Comments**
NA

**Comment by oslynn** [comment]
Notified UT:
Good after noon, Rocio
I checked the ReportStream transport to see the latest message sent to UT-PHS.ELR.
It uploaded information as bellow:
  Filename:                 covid-19-3651335e-32ec-4c93-a720-fb2bfcd68587-20230322170925.hl7 
  uploaded to host:   transfer.health.utah.gov
  Destination:              /in

Are those information above correct?  If so, please check the /in directory.

Very respectfully,
-Ott Sathngam
CDC ReportStream Eng.

**Comment by oslynn** [comment]
Email from UT:
Hello,

I have been reviewing your test messages for CDC ReportStream and have noticed a few things that we're missing for Utah's Communicable Disease code. Here is a list of what we've noticed thus far.

1. Patient address identifier. This element can be optional as long as the identifier (i.e. Apt. 3) is present in the patient address field. PID.11.2
2. Patient Email is a required reportable element for the state of Utah, if known.  We know that not everyone collects it but if you do we request that it be included in PID.13.4.
3. Ordering Facility Address ID is an optional element which should be used to identify a suite number (i.e. Suite 202). ORC.22.2
4. Result Units. This element is only required for numerical results. No units should be present for string text, snomed, or internal codes. OBX.6.1
5. Reference range. This element is particularly important for susceptibility or numerical results.  If this test message does not include numerical results ensure a future test message includes a lab test with numerical results to ensure the element is included and correct. OBX.7.1
6. Collection Date and Lab Test Date are being sent to us however, we are missing a time zone offset. This is important for our system to properly translate the time stamps for date validations. For example, a formatted date/time field of 202201011200-0700 would be used to report from MST.


Can you please look over these and let me know if you have any questions. Once you are ready to send us new messages including these elements please let me know so that I can look over them again and provide further feedback if necessary. 

Thank you,

**Comment by sliu1000** [comment]
Rocio Ramos (DHHS) <rramos@utah.gov>
Utah DCP Informatics Program <edx@utah.gov>
Sathngam, Ott (CDC/DDPHSS/OD/HITSSU) (CTR);Report Stream (CDC);Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR);james.gilmore@agile6.com;brandoncanniff@navapbc.com;lafredahoward@navapbc.com
Hi everyone,

Great news, the feed is now in production. We will still need to go through a validation process but we are currently working on a few things before we can get started. We will reach out as soon as we have everything in place to start the validation process with your feed.

Thank you,

Rocio
On Wed, Apr 5, 2023 at 3:19 PM Utah DCP Informatics Program <[edx@utah.gov](mailto:edx@utah.gov)> wrote:
Great. I have looked over the messages and we should be ready to move into production soon. Teri will need to review the feed and give authorization for the feed to be moved into production. She is out this week, hopefully she can review in the next couple of weeks. I will keep in touch and let you all know once she has had time to review. 

Thank you,

Rocio

**Comment by oslynn** [comment]
Somehow, UT is sending this email to us by mistake.  Closing this ticket.
