### ISSUE TITLE
Cleanup TrustedIntermediaryLabOrder.yml

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8841]
### User Story:
As the ETOR sender, my translations should be of the appropriate kind (sender vs receiver) and live in the appropriate folder.

### Description/Use Case
Presently, the HL7v2 receiver transforms live in `TrustedIntermediaryLabOrder.yml` under the STLT/CA folder, which is incorrect. Furthermore, this file seems to actually have transforms that should be moved to a sender transform configuration since they are not receiver specific.

### Acceptance Criteria

- [ ]  `TrustedIntermediaryLabOrder.yml` moved to STLT/Flexion folder.
- [ ] Contents of `TrustedIntermediaryLabOrder.yml` migrated to a sender transform config if appropriate. If no contents are migrated, then an empty sender transform config is created as a placeholder for future additions.
- [ ] Flexion org settings updated to point to correct transforms.
- [ ] Manually tested to see if a FHIR message sent by flexion sender makes it to simulated public health lab, also under the flexion org.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8841?planning-poker) with Zenhub @arnejduranovic @carlosfelix2 @JessicaWNava @jimmyfagan @mkalish @PatriciaPerozoUSDS @thetaurean @victor-chaparro

**Comment by bishoyayoub** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/8841?planning-poker) with Zenhub @jack-h-wang

**Comment by jimmyfagan** [comment]
The current contents of the receiver transform involve setting OBR-11 to "P", to reflect the [Specimen Action Code](https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0065) for `Pending specimen; Order sent prior to delivery`. The published mapping for OBR-11 to FHIR only reflects conversions for "A", "G", and then loops in everything else in the same one. So when we do a conversion back to OBR-11, there isn't a standard way of doing so for values other than "A" and "G". I tried to make some custom string for our own usage like "Pending specimen", however that then failed the FHIR validation because "Pending specimen" is not in the enum [ServiceRequest.ServiceRequestIntent](https://hapifhir.io/hapi-fhir/apidocs/hapi-fhir-structures-r4/org/hl7/fhir/r4/model/ServiceRequest.ServiceRequestIntent.html) that the property uses. It'd be nice to talk through it to make sure we're on the same page, but I think the current layout is therefore appropriate. Will still use this ticket to update the layout of the transforms and make sure the org is pointing to the right ones.
