### ISSUE TITLE
Refine design process map 

### ISSUE THREAD

**Issue by lizzieamanning** [CDCgov/prime-reportstream#8843]
## User story

As a ReportStream team member, I need to understand our design process, so that I know what steps are involved, and who is responsible for driving each step. 

## Background & context

After reflecting on how our process worked for the first few features we worked on as a team, we have ideas about how to improve our process so our collaboration starts earlier, is more efficient, and is documented. 

## Open questions
-   What's the best format to document this process so others can reference it?
-   How can we indicate required vs optional steps depending on the feature or piece of work? Keeping in mind that this should work for our service design teams' work as well
- What is the best way to gather feedback from others? (Knowing all discipline leads from Webex have already been consulted) i.e., should we share in the all team sync on Wed?

## Working links

[Mural](https://app.mural.co/t/nava4113/m/nava4113/1673916436749/fa6b9fa1649bfcc743f872ac3691460172a7141e?sender=u791b7d4d34761ac59b672214)

## Acceptance criteria

- [x] Take an initial pass at refining the existing process (See mural above)
- [x] Document open questions 
- [x] Review with design team
- [x] Create a plan for sharing with the wider team

**Comment by jillian-hammer** [comment]
I made a few minor revisions based on feedback from the design team at crit.

The design team would like to add additional detail to the "Design" process section, and split out the "Implementation" section to be inclusive of non-technical/feature work. This will happen at a future design sync.

**Next steps:** Share with PMs early next week, and again at All Teams Sync on 4/5.

Going to close since ACs are completed, and happily pass the baton to the design team to complete while I'm OOO.

cc @lizzieamanning
