### ISSUE TITLE
CA Flu Pilot: Create SR Sender Transform

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#8861]
### User Story:
As ReportStream, I want to achieve an appropriate level of separation of concerns in our transforms by making sure sender-specific transforms, in this case Simple Report, are not stored with receiver transforms, in this case CA.

### Description/Use Case
When getting SimpleReport FHIR FLU data sent to California, sender transforms did not exist and so all our transforms happened in the California receiver FHIR -> HL7 transforms under `prime-router/metadata/hl7_mapping/STLTs/CA`. Now that Sender transforms are implemented (FHIR -> FHIR) we need to comb through all the mappings in the CA folder and determine which ones are specific to SimpleReport and not CA and then move them to a SR sender transform.

### Dev Notes:
- Receiver transforms are FHIR -> HL7 transforms that occur to accommodate special requirements of the receiver (California)
- Sender transforms are FHIR -> FHIR transforms that occur to accommodate special requirements or missing data of the sender (SimpleReport)
- There are currently no Sender transforms in the repo. I suggest seeing if `prime-router/metadata/fhir_mapping/fhir` would be a good place to store them?  We could make a folder here for each sender, like SimpleReport?
- Victor added comments in the CA mappings files for what should be moved over to SimpleReport Sender transform

### Acceptance Criteria
- [ ] Created a sender transform for SimpleReport and stored it in the appropriate location in repo
- [ ] Moved non-CA specific receiver mappings from CA folder to SimpleReport sender (FHIR) transform
- [ ] Validated CA output HL7 is the same before and after changes to the mappings

**Comment by JessicaWNava** [comment]
After talking with Patricia and Victor, there is not anything to move over to simple report. However, there is going to be a ticket coming out of this to figure out how to handle the cliaForSender setting since this is in a bit of a middle no man's land between sender and receiver and may require a custom fhir function or some other very specific work around. We also determined that the sending-facility_namespace-id did not actually need to be set since it was not being set in the COVID pipeline, so next test @victor-chaparro is going to remove it to test to make sure there aren't any issues without it.
