### ISSUE TITLE
Puerto Rico Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#9156]
### Acceptance Criteria 
- [x] Created and sent data using fake data generator 
- [x] Created and sent data using synthesized data generator 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed

**Comment by cloudmagic80** [comment]
From the meeting with Puerto Rico team, they had questions on the validator header, specifically the FHS and BHS segment. If it was failing, we recommended they remove those, which PR did.
We don't need to send a test message with those segments removed since PR removed it.
If PR is having more issues, they will send a message to Tier 1 support.

We are waiting to hear from them next week , wee of June 5th. We should have data structure figured out by then.

**Comment by brick-green** [comment]
Sent another test message to PR. I _think_ it should be the last test messaged needed prior to going to prod
