### ISSUE TITLE
ReportStream Staging - 17 Dependency Notifications on Latency Degradation

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#9192]
## **Problem Statement**
Received a PagerDuty notification on 4/17 at 5:47 PM for ReportStream Staging - Dependency Latency Degradation notifies you of an unusual increase in response by a dependency your app is calling (e.g. REST API or Database).

## **What you need to know**
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/c169273c-c2c5-4213-ae33-059621e6ec95)

## **Acceptance Criteria**
Please investigate and see if any further action is needed.

## **To Do**
Assign to an Engineer to Investigate.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by sliu1000** [comment]
![image](https://user-images.githubusercontent.com/102377655/232647059-a8013c13-db44-4e96-bfbb-3714d7c12794.png)

**Comment by LaFreda1** [comment]
Please see @oslynn for any questions

**Comment by oslynn** [comment]
Looking into this issue.  I know what it is.  Our ReportStream Staging were trying to access database and at point staging database responded slower than normal.  Therefore, the ALTER was trigger.  There is no harm since is happen sometime in our staging environment.  I will comment and close the ticket.
