### ISSUE TITLE
Create a user flow diagram mapping out Okta login

### ISSUE THREAD

**Issue by yudonoodles** [CDCgov/prime-reportstream#9253]
## User story

As a Webex team member, I want to understand the steps involved in logging in using Okta so that we can visually see that mapping. 

## Background & context

This is part of the conversation and work happening around [Okta research](https://docs.google.com/document/d/1lPCVpzU9tqdESWxOyU9KqxOr-Tlax0SVe7u79bTYz2g/edit#heading=h.5d3xmmoa5n8j).  

## Open questions

_A bullet list format of any unresolved questions that will need answers in order to complete this
task_

-   ...
-   ...

## Working links

_Links to any Figma, gDoc, or other working document_

-   [Okta login set up and user login flow ](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=u79b7ab9bcb294882c12b1916)

## Acceptance criteria
-   [x] Create a mural flow of the current login flow
-   [X] Update the [questions pool](https://docs.google.com/spreadsheets/d/1THH9Ekj5renvIwSpl-6SzzyUJ5tuNcH76l4GTiboQXE/edit#gid=0) with any questions that came up

**Comment by yudonoodles** [comment]
Review: 

- @jillian-hammer and @lizzieamanning have reviewed it. 
- @chris-kuryak you were interested to take a look at it. Updated the ticket with mural link. 

- To do:
Review with Eng from Engagement regarding meta data set up and where they add those details.

**Comment by yudonoodles** [comment]
Done: 
- Engagement engineer Brick Green reviewed it and left comments async on mural board. 
- Added new process box and incorporated feedback from Brick Green.

Review before closing:
@chris-kuryak and @jillian-hammer take a look at the final form of the diagram and then this should be good to close out.

**Comment by jillian-hammer** [comment]
looks great to me! thanks @yudonoodles

**Comment by chris-kuryak** [comment]
@yudonoodles 
Nice work! Love the screenshots for clarity. Some questions I have, but happy to review sync if it's easier:

1. This flow appears include _adding a sender_ as well as _setting up the Okta account_. And since the Okta account setup is NOT a required step currently (though it will be), should we change the title and description of the document to include adding a new sender?  
2. There is an arrow linkage between **Create new Organization** and **Eng needs Okta acc**, which makes it seem as though after setting up the sender on the backend you need to log in to ReportStream and also set up the sender in the GUI. But I don't think that's true right? Shouldn't it just be a red line that connects from **Create new Organization** to **Do you need an Okta Acc**? Or am I missing something here?
3. I would consider changing **Eng needs Okta acc** to **Eng needs Admin access to Okta** to be more explicit (since we have multiple tiers of Okta access). Or potentially removing **Eng needs Okta acc* altogether and go straight to Logging into Okta Admin Settings.
4. What does **Authenticate User** mean in this case? Is it referring to the Sender? And does that just mean entering the public key, or is it something different?
5. Consider changing **Do you need Okta acc** to **Does Sender need Okta account**
6. On the decision point **Format Works**, I believe that is referring to Pass/Fail Validation, right? I would consider changing to **Pass Validation?**. And it is missing a **Yes** after that step leading to setting up the Sender Settings.
7. I think it may be useful to add a link to the [Kickoff SOP](https://docs.google.com/document/d/10HjEtXyRSyl2dkx_1hXFqkaxq5xMxKpNwI8ePV2rems/edit#) near the **Kickoff Call** block
8. Are we building a mural that connects all these pieces of the onboarding process? If so, this would be great to link to/from that larger mural for more detail on just this part of the process.

**Comment by yudonoodles** [comment]
@chris-kuryak Thank you for the feedback! 

1. DONE - Changed board title to "How to add a new sender and set up their okta account? And renamed the sender set up board to "1. How a RS engineer onboards a new sender?" and "2. How a RS engineer sets up sender on Okta" to be clearer
2. DONE - Added path from "Create new org" to "Authenticate user via public key" which then leads to "Does sender need Okta acc?"
3. DONE - Removed "Eng needs Okta acc" step altogether
4. DONE - Changed to "Authenticate Sender via public key" to be more explicit 
5. DONE - Changed to "Does sender need Okta acc?" Added "optional" on the arrow that takes it to that step
6. DONE - Changed to "Pass validation?" 
7. Added link to Kickoff SOP doc. ***Change needs to be accepted by admin, currently my link is a suggestion to the doc***
8. Yes, will move this task to [#9238](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9238)

Let me know if there's any additional changes, will close once you review the updates. Needs to approve change to SOP doc (see bullet 7).

**Comment by chris-kuryak** [comment]
@yudonoodles Looks awesome! Thanks for integrating my feedback.
Just some small stuff below that I went ahead and changed. I think you can consider this done if you agree:

1. I also updated the Purpose statement to include "set up a new sender" along with creating an Okta account. Let me know if that doesn't seem appropriate.
5. I don't think you need the "Optional" tag here, since asking the question "Does Sender need Okta acc?" is NOT an optional step. I believe they are asking that every time. The optionality of the Okta account seems to be encompassed by the Yes/No to that answer. So I removed the word "Optional". But let me know if you think it should be added back in.

**Comment by lizzieamanning** [comment]
Also looks good from my end

**Comment by chris-kuryak** [comment]
@yudonoodles I could only add the link to the Mural (which I did).
But I don't seem to have the ability to "approve" changes to the SOP document. So I tagged @lizzieamanning in the document to see if she can.
