### ISSUE TITLE
Saving actions during batch step fails if item lineages are populated

### ISSUE THREAD

**Issue by TurkeyFried** [CDCgov/prime-reportstream#9266]
## Describe the bug
When Item Lineage is loaded during the Batch step, saving action history fails with the following error:
`parent reports from items [X]) != from reports [X]`, with `[X]` standing for lists of ids.

## Impact on ReportStream
To work around this, functionality that uses Item Lineage needs to be loaded outside of the Batch step, leading to odd code placement and additional database fetches.

## Steps to reproduce
1. Go to `BatchFunction.kt`
2. Inside the setting of `inReports`, add the following code: `report.itemLineages = workflowEngine.fetchItemLineagesForReport(report)`
3. Submit a COVID Pipeline report and await the batch step.
4. The ReportStream console will display the error message.

## Expected behavior
ItemLineage is a core part of the Report structure, and its existence should not hinder other aspects of the system. Simply loading ItemLineage on any Report should have no effect on Action saving.

**Comment by bishoyayoub** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/9266?planning-poker) with Zenhub @arnejduranovic @jack-h-wang @mkalish @thetaurean @victor-chaparro

**Comment by JessicaWNava** [comment]
8985 needs to be reworked into a bunch of smaller tickets and a more planned out rework of the api, so we are going to close this ticket since 9266 only needs to be done if the "origin id" method for fixing the api call speed is done. But there's a chance that as part of the rework we may go with a different solution rendering this ticket moot. (mostly quoted from Luis). Closing.
