### ISSUE TITLE
MPox Data in RS going to DCipher - Confirmation of Definitions

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#9267]
## **Problem Statement**
Received an email inquiry from Jasmine Chaitram (CDC) about getting Duplicate Data from "Mpox data from commercial labs coming to CDC via ReportStream and going to Dcipher"

## **What you need to know**
Sahil from DCipher Team provided the following information: The duplicates here stemmed from the resending of data due to updates coming from Mayo Clinic. We were able to resolve the duplications by modifying our criteria to identify duplicates, but it is probably **worth aligning on what constitutes a unique lab test** coming from ReportStream.

Based off conversations from last year, the columns that constituted a **duplicate** were the following: testing_facility_oid, testing_facility_name, sample_additional_identifier, message_id; however, from some analysis it looks like **“message_id”** changes when the same lab test is sent again (i.e., if a field is modified). Could you confirm if that my interpretation of message_id is correct? If so, it would also be helpful to confirm a unique identifier for a lab test.

## **Acceptance Criteria**
- Please confirm what constitutes a "duplicate".
- Please confirm if Sahil's understanding of what a message ID is correct. If correct, please confirm a unique identifier for a lab test.

## **To Do**

- Assign to Engineer
- Engineer to Investigate
- Provide to Helpdesk and they can provide to the original user with the response.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by Jcavallo7** [comment]
*Update from JIm Duff*

Sharon,

This email chain is information related to Ticket https://github.com/CDCgov/prime-reportstream/issues/9267

Basically, Mayo resent the data to fix issues with age data, which was missing.

Jim

**Comment by sliu1000** [comment]
FWD Email from Jim Below:

**Comment by sliu1000** [comment]
Update from Dcipher:

Chaitram, Jasmine (CDC/DDPHSS/CSELS/DLS)
Gilmore, James (CDC/DDPHSS/OD/HITSSU) (CTR);Report Stream (CDC);Arora, Sahil (CDC/DDID/NCEZID/OD) (CTR)
Reeves, Maurice (CDC/DDPHSS/OD);Duff, Jim (CDC/DDPHSS/OD);Soroka, Stephen (CDC/DDID/NCEZID/OD);lafredahoward@navapbc.com
Hi James - Thanks for the explaining source of potential duplicate info.
 

Sahil – Any suggestions at this point? Can some examples be provided?

Jasmine

**Comment by GilmoreA6** [comment]
email sent to decipher team:


Hi Sahil and Jasmine,

 

In regards to the message_id field. For HL7 senders (which all current ReportStream MPOX senders are) this is taken from the MSH-10 (Message Control ID) field of the inbound message from the sender. 

 

Per HL7 spec this should be a unique identifier for that specific message (per application) and should not be repeated unless it is the exact same message. This value can and does pop up again from a different application/source (i.e. application/sender one sends message id "123" and then later application/sender two sends message id "123"). This is why the columns of testing_facility_oid and testing_facility_name are necessary to identify a duplicate.

 

sample_additional_identifier we pull from the SPM-2 (Sample ID) field. The sample id is a unique identifier assigned by the sending application for the specific sample (i.e. tube of blood drawn from patient) so this combined with the other columns should allow you to identify most duplicates.

 

The caveat here are the concepts of either sequential final results or corrected results, which may be what we are dealing with here. When a mistake is identified in the initial results sent most laboratories will issue a corrected result which amends the previous result with corrected information. This would have a new message_id because according to the sending application it is a new message (i.e. not an exact duplicate as it has new information). If this is the case we should be able to identify it from test_result_status (looks like we aren't passing this along to you in your current schema but we could if this identifier is present).

 

If you have identified some duplicates could you provide the message id's of some identified duplicates and I can investigate those specific messages to see what they looked like inbound? This will help me see might be the best course of action.

 

Thanks,

 

James

**Comment by GilmoreA6** [comment]
Response from Decipher team:

Hi James - Thanks for the explaining source of potential duplicate info.

 

Sahil – Any suggestions at this point? Can some examples be provided?

 

Jasmine

**Comment by GilmoreA6** [comment]
Closing issue as DCipher has not provided any examples for review or asked for additional assistance beyond the provided explanation
