### ISSUE TITLE
Sender "Color" wants to receive failure notifications.

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#9391]
## **Problem Statement**
We received an email from Nick from the sender "Color" through the ReportStream inbox stating Color started submitting COVID results for Vermont 05/03/2023, the message shows as delivered, yet Vermont states the message was rejected. However, this message was successfully submitted and then delivered properly without being filtered. But our concern is that we (Color) did not receive any notification that it failed. Is there any way for us to get failed notifications? 

## **What you need to know**
Hello, 

Color started submitting COVID results for Vermont through ReportStream yesterday, May 3. We are on the synchronous processing setting, so the message we sent should have been validated at the time of submission. The message shows as delivered when querying the history API, yet Vermont reports their system actually rejected the message. I've forwarded the email from Vermont below which has message details and the error messages they're reporting. Given this message showed it was successfully submitted and then delivered properly without being filtered, on our end we'd have no way to know that it failed. 

Please let us know how we should proceed in this situation and do let us know if you need any additional information. 

Best, 

Nick Wheeler

## **Acceptance Criteria**
Investigate if it's possible for Color to receive failure notifications.
Let help desk know so we can relay the message to Color and if there is any alternative.

## **To Do**
Assign to an engineer.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by wcollin89** [comment]
@GilmoreA6 

Hi James, Nick reached out for an update on this in the RS Inbox:

> I was wondering if we could get an update on these support tickets. We understand there may be some investigation to do and that these take time, but we want to make sure we can inform these states about our plan going forward.
> 
> For Vermont, we've now had the second failed submission (mentioned in previous reply).

Thank you!

**Comment by GilmoreA6** [comment]
Hi Nick,

Apologies for the delay. Here are the updates.

VT:
I've deployed a hotfix that should resolve the issues. The issue was on our side and related to how we were handling some of the subfields in the provider fields (ORC-12-9 and OBR-16-9), also added some logic around ORC-4 due to that error. I've re-ran the messages through the new code and re-submitted to VT. I'll follow up with our contact at VT-DOH on Monday to make sure they processed correctly.

OH:
I've changed some settings around how the filters are working so that instead of not getting any response you should receive indication from the submission history api that those messages were filtered out because they did not contain an abnormal flag in OBX-8 (this is not retroactive and querying anything submitted to this point will still return no errors or destinations). I have an email out to Ohio asking if they would like us to change their settings as they are currently blocking results they (theoretically) should want according to their current guidance.  I will let you know when I hear from them.

Thanks,

James

**Comment by GilmoreA6** [comment]
Hi James,

 

Thanks for following up! Unfortunately, neither of the messages below made it through successfully. I’ve pasted the NAKs for each below which will hopefully help you investigate further:

 

Vermont Department of Health - HL7 2.5.1 ELR Message Validation Error Report

Filename: covid-19-b711c577-a329-4cb5-a7f8-43812e5c9b34-20230516231527.txt

Received: Tue May 16 2023 19:16:49 GMT-0400 (EDT)

 


 

Message failed to process due to the following HL7 validation error(s):

      <error Path="PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerGroupNumber.EntityIdentifier" Description="Required field missing"/>

      <error Path="PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerGroupNumber.UniversalID" Description="Required field missing"/>

      <error Path="PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerGroupNumber.UniversalIDType" Description="Required field missing"/>

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Vermont Department of Health - HL7 2.5.1 ELR Message Validation Error Report

Filename: covid-19-2af526a5-af4f-4066-8e08-aa2048e67252-20230517163621.txt

Received: Wed May 17 2023 11:38:19 GMT-0400 (EDT)

 



 

Message failed to process due to the following HL7 validation error(s):

      <error Path="PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerGroupNumber.EntityIdentifier" Description="Required field missing"/>

      <error Path="PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerGroupNumber.UniversalID" Description="Required field missing"/>

      <error Path="PATIENT_RESULT[0].ORDER_OBSERVATION[0].ORC.PlacerGroupNumber.UniversalIDType" Description="Required field missing"/>

 

Let me know if there is anything else I can do to help. Again, I appreciate your attention to this!

 

Andrew Gross, MPH | Health Data Administrator

Division of Health Statistics & Informatics

Vermont Department of Health

108 Cherry St, Burlington, VT 05402

**Comment by GilmoreA6** [comment]
Hi Andrew,

Re-Transmitted the two failed messages. It looks like when I updated the configuration the first time I missed updating logic around ORC-4-2. This has been corrected and both messages should have processed appropriately and moving forward for Color. Let me know if there are other issues.

Thanks,

James

**Comment by OHoward2023** [comment]
Hi James, 

I've seen your updates regarding Vermont and it seems like we're in a good place there. Our most recent message on May 16 was received successfully and not filtered. Thanks for working through that.
