### ISSUE TITLE
Sender "Color" wants to know why their submission is not being delivered.

### ISSUE THREAD

**Issue by OHoward2023** [CDCgov/prime-reportstream#9394]
## **Problem Statement**
We received an email from Nick from the sender "Color" through the ReportStream inbox stating Color started submitting COVID results for Ohio 05/03/2023, the specific submission, "5899e299-2a60-42f9-bf80-e05a141ab87d", did not receive any errors, only warnings, but was not delivered to any destination. The history API has this record marked only as "received" even though it was sent yesterday.

## **What you need to know**
Hello, 

Thank you for looking into this. We also migrated our Ohio reporting to ReportStream and encountered an issue there we would appreciate if you could look into. Submission "5899e299-2a60-42f9-bf80-e05a141ab87d" has no errors, only warnings, but was not delivered to any destinations. It was bound for "oh-doh.elr" and the message is exactly the same as the message we would have sent them if not reporting through ReportStream. The history API has this record marked only as "received" even though it was sent yesterday. 

Best, 

Nick

## **Acceptance Criteria**
Investigate why the submission is not receiving errors, only warnings, and why it was not delivered to any destination.
Let help desk know so we can relay the message to Color and if there is any alternative.

## **To Do**
Assign to an engineer.

## **Additional Comments**
If applicable, add screenshots, links, etc. to further explain the ticket

**Comment by wcollin89** [comment]
@GilmoreA6 

Hi Jmes,

Nick reached out to the RS Support team for an update on this, and mentioned another occurrence:

> For Ohio, we had another submission on May 10 (`a60181a7-5899-47ed-b755-5be033c06a6a`) which shows no errors, but also no destinations. The record still shows as "received" 2 days later now. 

Thank you!

**Comment by sliu1000** [comment]
Update from sender:

For Ohio, we had another submission on May 10 (a60181a7-5899-47ed-b755-5be033c06a6a) which shows no errors, but also no destinations. The record still shows as "received" 2 days later now. 


Commnication from James on 5/4/2023:

Looking into these two tickets for you and here is what I have so far.

1.) Ohio  (#9394) - Ohio has a filter to only pass positive results. I can reach out to them to check and make sure this is what they still want from us but we would have set the filter this way at their direction. It looks like you didn't get a response that this was filtered out though. I believe this is a bug because the filter is set on the org and you are using the routeTo functionaility which bypasses some of the routing process. I can start a ticket for this and have it investigated.

**Comment by GilmoreA6** [comment]
Hi Nick,

Apologies for the delay. Here are the updates.

VT:
I've deployed a hotfix that should resolve the issues. The issue was on our side and related to how we were handling some of the subfields in the provider fields (ORC-12-9 and OBR-16-9), also added some logic around ORC-4 due to that error. I've re-ran the messages through the new code and re-submitted to VT. I'll follow up with our contact at VT-DOH on Monday to make sure they processed correctly.

OH:
I've changed some settings around how the filters are working so that instead of not getting any response you should receive indication from the submission history api that those messages were filtered out because they did not contain an abnormal flag in OBX-8 (this is not retroactive and querying anything submitted to this point will still return no errors or destinations). I have an email out to Ohio asking if they would like us to change their settings as they are currently blocking results they (theoretically) should want according to their current guidance.  I will let you know when I hear from them.

Thanks,

James

**Comment by OHoward2023** [comment]
Hi James,

Just following up about Ohio. We had submissions May 17-20 that seem to still be filtered with the `abnormal_flag`. Have you heard back from them? And when you do, will it be possible for you to resend these messages? 

Please let me know if I can assist in any way. 

Best, 

Nick

**Comment by OHoward2023** [comment]
Hi Nick,

I have not yet heard from Ohio. I will try to ping them again. I can resend anything that is still in our blob storage (60 days). Ohio did update it's guidance after the end of the PHE to align with other Class B reporting for Ohio, so I think there is a strong possibility they will elect to continue only receiving positive results.

Thanks,

James

**Comment by OHoward2023** [comment]
Update from sender 5/23/23:

James, 

Sorry, I misunderstood the issue here initially. I just looked and we did have a successful result go through to Ohio when there was a positive test result. That submission was May 12.

Everything looks good then. We're able to submit to them when there's a positive test, and then they're correctly (from their perspective) filtering negative results. 

Apologies for the confusion. Thanks for looking into this and for the explanation.
