### ISSUE TITLE
Identify opportunities for Self-Service features in the Sender Onboarding Process

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#9442]
## Problem statement
Research exists for the Intake/Interest and Kickoff processes on the Sender Onboarding lifecycle. We would like to identify areas of those processes that can be "self-served" to eliminate the need for hands-on interaction with ReportStream engineers and support staff.

## What you need to know
Background Materials
- [Kickoff SOP](https://docs.google.com/document/d/10HjEtXyRSyl2dkx_1hXFqkaxq5xMxKpNwI8ePV2rems/edit#heading=h.d07on35uxhvq)
- [Original Service Blueprint](https://app.mural.co/invitation/mural/nava4113/1672148125717?sender=u0c3cdba5126734aceb613229&key=64533fb0-db5e-4171-a9a0-7db126e7b740)
- [WIP New Service Blueprint](https://app.mural.co/t/nava4113/m/nava4113/1681488534126/acccd696c031a19d3335e62204ece296ef483b9e?special=mandrillfacilitator&sender=u791b7d4d34761ac59b672214)
- [Existing Sender Settings and Okta Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=u788ba8e0ebf56a2ad7d18905)

Working Link
- [Interest & intake phase self-service opportunities Mural](https://app.mural.co/invitation/mural/primedatainput6410/1684158407022?sender=u0c3cdba5126734aceb613229&key=eb9cebd4-44a1-4f4a-a444-186187042ec9)

## Acceptance criteria

- [x] Opportunities for self-service on the Interest/Intake and Kickoff phases are clearly identified and ready for discussion
- [x] Review with Jillian and Chris

## To do

- [x] Desk research: review all of the existing documents
- [x] Set up a scratchpad Mural to copy paste the existing flows
- [x] Annotate opportunities as stickies on top of the flow

**Comment by yudonoodles** [comment]
On 05/11 met with @jillian-hammer to discuss the ticket and get some context about the work. @chris-kuryak and Jillian helped define the scope for this ticket prior. The work as defined is using existing research to define areas of opportunity. During our meeting, we aligned on: 
- Start reviewing existing documents 
- Jillian will start a mural board for us 

**Note**: There is interest to collaborate on identifying opportunities from the Engagement designers despite this ticket being scoped as only reviewing existing research/documents. See thread [here](https://focusconsultinggroup.slack.com/archives/C025JHV38BY/p1683735991520989) on that discussion that @audreykwr helped start. During the existing weekly design sync on 05/15 (held twice weekly Mon & Thurs), there will be a discussion with the design team on identifying some of these opportunities.

**Comment by jillian-hammer** [comment]
hi, two updates for you @yudonoodles: 
- I set up the [Mural workspace](https://app.mural.co/invitation/mural/primedatainput6410/1684158407022?sender=u0c3cdba5126734aceb613229&key=eb9cebd4-44a1-4f4a-a444-186187042ec9). I will continue to refine it this afternoon, but feel free to pop in if you make a note of anything as you review the SOP 
- I gave this ticket 3pts, but let me know if that feels inaccurate and we can adjust!

**Comment by yudonoodles** [comment]
Thanks @jillian-hammer for setting up the mural board. 3 pts sounds good to me. 

**Note:** During the usual design crit on Thursday, engagement designers will present some research that they have done on summarizing pain points or potential opportunities.

**Comment by yudonoodles** [comment]
@jillian-hammer & Tshering met with @chris-kuryak on 05/19, presented flow diagram based on kickoff SOP doc and tiered (low, mid, high) measure of opportunities. Based on feedback from Chris, I updated the following on the mural board:
    * Clearly segmented sticky notes to specific legends
    * Added swim lanes and content for: 1. Specific artifacts and 2. Who's responsible for those artifacts
    * Included images and links where applicable
    * Followed up on “Informational meeting” step in onboarding with Dylan and Jessica: That step seems STLT facing and isn’t a standard step in onboarding a sender, removing the step from mural as a result. 
    * Organized and cleaned up mural board

**Comment by yudonoodles** [comment]
Ticket is closed, but want to log follow-up meetings:

05/23 Meeting with Chris, Jillian, Tshering and Lizzie on 05/23 discuss next steps and alignment: 
- Discussion surrounding opportunity to improve sender intake form, if by improving that small piece, there could be an opportunity to help senders onboard without help from RS team. 
- During that discussion, I brought up an addition to the mural where I laid out three tiers of matching that might be happening: light, medium and heavy and at each of these checkpoints, we are checking if the sender and RS is the right fit, that way there is a robust system that doesn't move forward unless it passes the matching at those points, and critically making sure the early light matching is being considered and thinking about how to improve that so that down the line, the senders who we don't match with does not go through to the next step, and instead there is an opportunity to redirect them to other resources. Potentially this could be a future line of discovery. 

05/24 Meeting with Chris, Tshering and Sharon, Customer Service Lead to discuss Smartsheet Service Request Forms and an opportunity to update them. 
- Meeting [notes](https://docs.google.com/document/d/1wW-CeQkjOQGajDcNfIbMIuuR45l5xnQK6_xjdNGUs7c/edit#heading=h.bk4vjnwx9b4r) and some takeaways were already captured here. In general, found it super helpful to understand challenges in getting senders to fill out the form, how data from those forms are managed and also got some validation on issues surrounding matching with senders and moving them forward to a kickoff call despite not meeting the requirements in order to connect with RS. 

Want to note two big takeaways from this research for future exploration/possible tickets:

1. Sender specific approach: An opportunity to create a step by step process for users to move forward during onboarding prior to meeting with the RS team where they can clearly move forward on their own via the ui/site. A medium tier lift opportunity could be to experiment with connecting existing disparate pages, such as file validator or public key tool and api programmer's guide, into a streamlined and linear manner and adding clarity on what's needed to be done at each stage before they move to the next. The first stage of this work could cover the ground of supporting the customer service team with creating a better way to match a sender to RS. 

2. Internal team approach: On the internal side of onboarding, this research also noted the need to centralize data/information internally, and a future line of work could be to streamline artifacts in a manner where they feed a centralized "source of truth" tracker automatically without the need for manual updates. 

In both cases, further discovery is needed, however we could explore the first opportunity since some of those pages that senders are being asked to use already exists, and we could explore how to connect or centralized them in a given location without needing to be directed by a person. Goal would be to make it intuitive and user-friendly. 

cc: @lizzieamanning @chris-kuryak
