### ISSUE TITLE
Design: Investigate USWDS & Trussworks implementations on ReportStream

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9615]
## User story

As a designer on ReportStream, I need to understand the USWDS standards and the Trussworks implementation on ReportStream, so that I can design the RS website/features within the standards.

## Background & context

Because ReportStream uses USWDS, WebX designers must develop a working knowledge of the set of standards, components, and technical specs outlined by the USWDS. Additionally, deepening our understanding of how Trusswork’s React library is used by our engineers (and the pain points) is a crucial part of ongoing eng <> design collaboration.

## Open questions

_A bullet list format of any unresolved questions that will need answers in order to complete this
task_

-   ...
-   ...

## Working links

- [ReportStream Figma](https://www.figma.com/files/project/18835566/ReportStream?fuid=1181666893792877605)
- [USWDS website](https://designsystem.digital.gov/)
- [Trussworks Figma component library](https://figma.com/community/file/836611771720754351)
- [Trussworks React library on Storybook](https://trussworks.github.io/react-uswds/)
- [Resource: Nava's Getting started with the U.S. Web Design System
](https://docs.google.com/presentation/d/1ufAej88fZP_Or57cBrEFmFDaT-3pgeNtwVmiHZoHa2M/edit?usp=sharing)
## Acceptance criteria

-   [x] Resources in working links section are reviewed
- [x]  Designer sets up a playground/working space to play around with the USWDS to deepen understanding of how it works as well as its limitations

**Comment by yudonoodles** [comment]
In progress, reviewing the links provided.

**Comment by yudonoodles** [comment]
Reviewing USWDS's design system (prepared by Truss.works), and learned that they have since made a few updates, currently we are on version 3.0 and this new version is v3.4.1. I added the [updated figma file ](https://www.figma.com/file/kkFICIYSxiEkijmiusDHeD/U.S.-Web-Design-System-(USWDS)-v3.4.1?type=design&t=VLRAkaSmoihAKZUB-6) to our Figma project: CDC>ReportStream.

Some notable updates by comparing the 2 versions are:
- New color wheels under the section system palette
- Font update from Public Sans to Source Sans Pro
- Button update - showing focus state and removing the success state
- Four additional icons added to icon list: LinkedIn, construction, outline checkbox, and fax icons.
- In-page navigation component aka side nav
- Language selector component

A minor update that's nice to have is: Adding placeholder image to certain components like cards.

cc: @jillian-hammer

**Comment by jillian-hammer** [comment]
thank you for pulling out these 3.4.1 updates @yudonoodles! 

how did this exercise go? were you able to play around with using it at all?
