### ISSUE TITLE
NH Onboarding Operations

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#964]
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [ ] Added to organization.yml
* [ ] Added to organizations-local.yml
* [ ] Added to staging settings table
* [ ] Added to prod settings table
* [ ] Added at least one receiver
* [ ] Added OKTA group to download site
* [ ] Added customers to OKTA group for download site
* [ ] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [ ]  Got credentials?
* [ ] Tested ELR connection locally?
* [ ] Tested ELR connection from Azure?
* [ ] Has the receiver accessed the download site?
* [ ] Has the receiver been sent at least one test file?
* [ ] Has the receiver signed off on file formatting?
* [ ] Are there labs sending data?
* [ ] Has the receiver confirmed receipt of the data?
* [ ] Have the files processed successfully?
* [ ] Are we in production?

**Comment by anshulkumar-usds** [comment]
| Task | Description | Completed (Y/N) |
| --- | --- | --- |

**Comment by MauriceReeves-usds** [comment]
Adding NH's ELR implementation guide.

[https://app.zenhub.com/files/304423150/a1bec11b-fbe1-4fb4-a002-df569a7318f7/download](https://app.zenhub.com/files/304423150/a1bec11b-fbe1-4fb4-a002-df569a7318f7/download)

**Comment by anshulkumar-usds** [comment]
4/30: Requested NH to provide SFTP creds

**Comment by MauriceReeves-usds** [comment]
Currently blocked because we are reviewing the documentation they have sent us

**Comment by MauriceReeves-usds** [comment]
Now that the credentials for New Hampshire have been persisted we can start sending test files to NH.

This is an iterative process where we post files to ReportStream, and they are routed to the server set up for NH. There is, however, a challenge in the short-term in how we can handle this. Until your CDC credentials are created, I can't share any PHI/PII with you, and I also can't share the credentials for NH with you yet. But there is a workaround.

I will provide you with a CSV file in the SimpleReport format that has already been synthesized and had it's PII/PHI stripped out. You will generate a file via your local Docker container that matches the NH spec, and then share that file with me, and I will send it to them for review.  I'll have you copied on all communications, so as we receive feedback you'll be able to respond and make adjustments. There is always the potential that you will need to make code changes in order to match NH's specification, so you will need to work in a branch.

Steps:
1. Switch to master and update it: `git checkout master && git fetch --all && git pull --rebase`
2. Create a new branch based on master: `git checkout -b <BRANCH NAME>`
3. Push the new branch upstream: `git push -u origin <BRANCH NAME>`
4. Update the `organizations-local.yml` file to fill in the information based on the AK spec. You will see that in the organizations file, there is a section for translation. There are three types of translation: Custom, CSV, and HL7. HL7 has the most configuration options, and makes it so you don't need to create a distinct schema for a state, which is something I should have communicated to you sooner, so I apologize for that. As an example, MSH.5.1 comes from the `receivingFacilityName` field, MSH.5.2 comes from the `receivingFacilityOID` field and so on. You can review other examples in the file to see how they're used, and look at the code in the HL7Serializer if you have questions. Once your organizations file matches the configuration for AK, you can start generating files.
5.  Prep your Docker container: `gradle clean package` and then `docker-compose build` and then `docker-compose up`
6. Make sure you have credentials saved for NH: `export $(cat ./.vault/env/.env.local | xargs) ./prime create-credentials --type UserPass --user foo --pass pass --persist NH-DPHS--ELR`
7. Once your Docker container is running, you submit the synthesized file I gave you like this: `curl -X POST -H 'client: simple_report' -H 'Content-Type: text/csv' --data-binary '@<PATH TO CSV FILE>' 'http://localhost:7071/api/reports'` The file will then run in your Docker container and be converted into HL7 and then uploaded into the SFTP server locally
8. Log in to your local SFTP server: `sftp -oPort=2222 foo@localhost` and `cd` into the `uploads` folder. You should see the New Hampshire file there. `get` the file locally and review the contents of the file against the HL7 spec from NH.

If you are satisfied with way the file looks, and it matches the spec, you can let me know and send me the file, and I will upload it to NH for you. Make sure to also pay special attention to things like field length limits, encoding of fields like race, ethnicity, etc and also the file name. If they have a specific file name format that they want, you may also need to define a custom `nameFormat` for them. Name formats are defined in `metadata/file_name_templates/file-name-templates.yml`, and there is a `nameFormat` property in the organizations file for each receiver.

You may need do this step several times as NH provides feedback on the file.

Each time you send me a file, you should commit your code in your branch and push it to origin so we have a copy in origin of the work you're doing. You are free to make a draft PR while you work.

On final commit, when this is ready to be merged in and we have sign off from the state, you will need to add a settings update into the `settings/production` folder that contains the correct translation configuration settings for the state.

fysa: @jlusds

**Comment by jlusds** [comment]
Regarding data schema, Inductive said it'd be the same for other Inductive STLTs

**Comment by jlusds** [comment]
e.g Guam

**Comment by MauriceReeves-usds** [comment]
Blocked by an issue saving credentials due to bug in Microsoft's Azure credentials library: https://github.com/Azure/azure-sdk-for-java/issues/22429
