### ISSUE TITLE
Ellume data issues

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#9694]
## Problem statement

Andrew from NIH reached out to inform us on some data issues regarding Ellume. 
I am pasting the email below.

## What you need to know
Hi ReportStream team,

 

Sorry for the mass email, but I wasn’t sure who to ask…

 

Charlee and I were looking over the OTC data and noticed a couple issues with the Ellume results:

Of the ~2M results received from Ellume, there are about 800,000 that have a null test result.
On Dec 4, 2022, there was a huge spike in Ellume test results.  About 58,000 were received, which all specify Dec 4th as the testing date.
 

See screenshots below.

![image002.png](https://images.zenhubusercontent.com/63d01230d5fb0224c259f9a7/e4a3db6b-c99b-4109-9802-60289c60a605)
![image001.png](https://images.zenhubusercontent.com/63d01230d5fb0224c259f9a7/0ff8f7da-b11d-41a6-ad3d-d7f24aa16aea)## Acceptance criteria

## To do

- [ ] Investigate the following questions/concerns: Of the ~2M results received from Ellume, there are about 800,000 that have a null test result.
On Dec 4, 2022, there was a huge spike in Ellume test results.  About 58,000 were received, which all specify Dec 4th as the testing date.

**Comment by GilmoreA6** [comment]
The blank result values appear to be a consequence of ELLUME providing the value "Presumptive Negative Test for SARS-CoV-2 (no antigen detected)" for LOINC 94558-4 when the expected value is "260415000^Not Detected^SCT". It also appears that they are using the incorrect LOINC code according to the LIVD table.

**Comment by GilmoreA6** [comment]
email sent to tim.kelly@ellume.com

"Good Afternoon Tim,

I am hoping you can help me reach the right person at Ellume to help with a data quality issue we are seeing with OTC negative results coming from Ellume into ReportStream. 

We are receiving HL7 message from Ellume through Lifepoint and for all of the positive and indeterminate results we are receiving the expected result codes in the OBX-5 field ("260373001^Detected^SCT" or "455371000124106^Invalid Result^SCT") but for the negative result values we are receiving the value "Presumptive Negative Test for SARS-CoV-2 (no antigen detected" instead of the expected "260415000^Not Detected^SCT".

In addition, in the OBR-4 and OBX-3 fields we are receiving the LOINC code 94558-4 when according to the LIVD table (https://www.cdc.gov/csels/dls/livd-codes.html) the correct value for Ellume COVID-19 Home Tests is 95209-3.  

Lastly, on Dec 4th 2022 it looks like there was a huge spike in reported results. Do you happen to know of a reason for that spike (results reported late, large event etc.)

I appreciate any help or direction you can give me to get this to the right person on your side. Please let me know if you have any questions.

Thanks,

James"

**Comment by GilmoreA6** [comment]
Response from Andrew NIH:

"Hi James,

 

Thank you so much for doing such great detective work!

 

Given that Ellume/Lifepoint was sending "Presumptive Negative Test for SARS-CoV-2 (no antigen detected)", I agree we can assume that all the null values represent negative results.  Do we have any reason to be unsure of this?  If not, I suggest that the HHS Protect team updates the Ellume data to replace the nulls with negatives.

 

Looking forward to hearing what you learn about the spike in reporting volume on 12/04/22.

 

Regarding the concept of a quality filter, we’re currently putting the finishing touches on a validator tool for MARS test results.  We had previously discussed having ReportStream implement this validator inline.  It wouldn’t work for the Ellume data, which is not MARS-compliant, but my understanding is that ReportStream is working on the ability to convert incoming OTC messages to MARS format – so the validator could be run after that conversion.

 

Best,

Andrew"

**Comment by GilmoreA6** [comment]
Hi James,

I've asked my lead developer Yuri Piano to look into this and will get back to you shortly.

Thanks,
Tim

Tim Kelly​
Head of Information Systems

**Comment by GilmoreA6** [comment]
closing as we have had no response
