### ISSUE TITLE
TN Onboarding Operations

### ISSUE THREAD

**Issue by anshulkumar-usds** [CDCgov/prime-reportstream#970]
The following items, generally in order, must be completed to successfully onboard a receiver to ReportStream:

* [x] Added to organization.yml
* ~~[ ] Added to organizations-local.yml~~ --no longer exists
* [x] Added to staging settings table
* [x] Added to prod settings table
* [x] Added at least one receiver
* [x] Added OKTA group to download site
* [x] Added customers to OKTA group for download site
* [X] Is customer contact made?
* What doc format are we supporting for the receiver (HLV, CSV, other)? **(Add comment below)**
* What transport(s) are we supporting for the receiver (SFTP, other)? **(Add comment below)**
* [X]  Got credentials?
* [x] Tested ELR connection locally?
* [x] Tested ELR connection from Azure?
* [x] Has the receiver accessed the download site?
* [X] Has the receiver been sent at least one test file?
* [x] Has the receiver signed off on file formatting?
* [x] Are there labs sending data?
* [x] Has the receiver confirmed receipt of the data?
* [x] Have the files processed successfully?
* [x] Are we in production?

**Comment by MauriceReeves-usds** [comment]
Now that the credentials for Tennessee have been persisted we can start sending test files to Tennessee.

This is an iterative process where we post files to ReportStream, and they are routed to the server set up for Tennessee. There is, however, a challenge in the short-term in how we can handle this. Until your CDC credentials are created, I can't share any PHI/PII with you, and I also can't share the credentials for TN with you yet. But there is a workaround.

I will provide you with a CSV file in the SimpleReport format that has already been synthesized and had it's PII/PHI stripped out. You will generate a file via your local Docker container that matches the TN spec, and then share that file with me, and I will send it to them for review.  I'll have you copied on all communications, so as we receive feedback you'll be able to respond and make adjustments. There is always the potential that you will need to make code changes in order to match TN specification, so you will need to work in a branch.

Steps:
1. Switch to master and update it: `git checkout master && git fetch --all && git pull --rebase`
2. Create a new branch based on master: `git checkout -b <BRANCH NAME>`
3. Push the new branch upstream: `git push -u origin <BRANCH NAME>`
4. Update the `organizations-local.yml` file to fill in the information based on the TN spec. You will see that in the organizations file, there is a section for translation. There are three types of translation: Custom, CSV, and HL7. HL7 has the most configuration options, and makes it so you don't need to create a distinct schema for a state, which is something I should have communicated to you sooner, so I apologize for that. As an example, MSH.5.1 comes from the `receivingFacilityName` field, MSH.5.2 comes from the `receivingFacilityOID` field and so on. You can review other examples in the file to see how they're used, and look at the code in the HL7Serializer if you have questions. Once your organizations file matches the configuration for TN, you can start generating files.
5.  Prep your Docker container: `gradle clean package` and then `docker-compose build` and then `docker-compose up`
6. Make sure you have credentials saved for TN: `export $(cat ./.vault/env/.env.local | xargs) ./prime create-credentials --type UserPass --user foo --pass pass --persist TN-DOH--ELR`
7. Once your Docker container is running, you submit the synthesized file I gave you like this: `curl -X POST -H 'client: simple_report' -H 'Content-Type: text/csv' --data-binary '@<PATH TO CSV FILE>' 'http://localhost:7071/api/reports'` The file will then run in your Docker container and be converted into HL7 and then uploaded into the SFTP server locally
8. Log in to your local SFTP server: `sftp -oPort=2222 foo@localhost` and `cd` into the `uploads` folder. You should see the Tennessee file there. `get` the file locally and review the contents of the file against the HL7 spec from TN.

If you are satisfied with way the file looks, and it matches the spec, you can let me know and send me the file, and I will upload it to TN for you. Make sure to also pay special attention to things like field length limits, encoding of fields like race, ethnicity, etc and also the file name. If they have a specific file name format that they want, you may also need to define a custom `nameFormat` for them. Name formats are defined in `metadata/file_name_templates/file-name-templates.yml`, and there is a `nameFormat` property in the organizations file for each receiver.

You may need do this step several times as TN provides feedback on the file.

fysa: @jlusds

**Comment by jlusds** [comment]
See attached for the implementation guide
[ELR_ONBOARDING_2019_FINAL.pdf](https://github.com/CDCgov/prime-reportstream/files/6749957/ELR_ONBOARDING_2019_FINAL.pdf)

**Comment by jlusds** [comment]
@MauriceReeves-usds Sent data today

**Comment by brick-green-agile6** [comment]
TN provided feedback: [https://app.zenhub.com/files/304423150/10d7bf9c-956f-47c0-8bff-e10e81a29f8b/download](https://app.zenhub.com/files/304423150/10d7bf9c-956f-47c0-8bff-e10e81a29f8b/download)

Overview:
- Data missing in non-required fields x% of the time. Since this is fake data these are not a priority to fix.
- OBR-25 result status is invalid
- Coded result is invalid in ~5% of results
- OBX-11 results status is invalid in ~10% of results

**Comment by brick-green-agile6** [comment]
Feedback to TN:

- SCT is a valid coding system according to table HL70396 (https://phinvads.cdc.gov/vads/ViewValueSetConcept.action?id=FF1E4EB5-F86F-11E1-BCF5-0050568E3338)
- Result Status is pulled from table HL70123 according to the HL7 v2.5.1 spec. Can TN not accept all the values in OBR-25 and OBX-11? (https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.815)

The remaining issues seem to concern missing data. I think we should wait till we can turn on a live feed to re-evaluate.

**Comment by brick-green-agile6** [comment]
password expired. TN asked to move to a public key auth. So I will create the key pair and send the public key to TN.

**Comment by anshulkumar-usds** [comment]
TN confirmed everything looks good on their end, no issues surfaced to RS on 11/23. Closing the onboarding workstream. Future issues will be added to support queue. fyi @brick-green-agile6
