### ISSUE TITLE
Page outlines from core model (2 of 3)

### ISSUE THREAD

**Issue by jillian-hammer** [CDCgov/prime-reportstream#9729]
## User story

As a user, I want to find what I need quickly and understand it easily so I can do my job.

## Background & context

The core model provides a way to anchor content plans around our goals, user needs, and the user journey, creating guidance for consolidating redundant content and IA development. Once the workshop has been completed, the info needs to be gathered from that work into specific plans to implement by developing more specific page outlines/flows for the main content categories.

## Open questions

- How many pages each section might require

## Working links

[Onboarding: Sender core pages](https://docs.google.com/document/d/1Mbp_AGcp9FgS0B8HV01n0KcpGNIef61FjkRHZKl0-3Q/edit)

## References

- [Core Model Mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1683161148287/76e2f6363470d7ad11e9a5db23cfc29606f42621?sender=uc55a7af3b66977fba12f5528)
- [Core Model Planning doc](https://docs.google.com/document/d/1WwM8aiyqzx-ocGeUAA07A5dpl6wTRIvOy8ya5ANRsws/edit)

## Acceptance criteria

- [x] Create Outline for Onboarding Senders (1 or several pages)
- [x] Create navigation structure for how sender pages will be connected
- [x] Meet on 06/15 with WebEx Designers to review said outline(s)

**Comment by yudonoodles** [comment]
Met with Audrey and Jillian on 06/08 to look over [Core Model Synthesis Plan](https://docs.google.com/document/d/1iEQJtMlpR-smxUqZt8BD1KpobJDfrzV92sdjds2ZYT8/edit), which was created to help orient on how and what to synthesize. We will meet again to review our syntheses on 06/15. 

**What we aligned on is as it relates to the ticket assigned to me:**
- I will take on Onboarding sender section of the [core-model workshop](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1683161148287/76e2f6363470d7ad11e9a5db23cfc29606f42621?sender=u79b7ab9bcb294882c12b1916)

**Summary of what I'll do:** 
- Create user flows for sender onboarding section
- Create an outline of the main page and different chunks within it (main deliverable)
- If clarification is needed, reach out to SME to get more details as needed. 

**Tool**: Can I use mural since it involves creating some user flows as well as an outline of the main/core page (as per the doc. linked above and section within it named Core model synthesis plan >**Core model outline Process**?

@audreykwr Please take a look at the summary of what I'll do and let me know if there's anything missing. As well as the tool I am thinking of using, mural, for this part.

**Comment by yudonoodles** [comment]
Reviewed Outline with WebX design team (Jillian and Audrey) yesterday 06/15 to review all page outlines.

Working link: [Onboarding sender Outline pages](https://docs.google.com/document/d/1Mbp_AGcp9FgS0B8HV01n0KcpGNIef61FjkRHZKl0-3Q/edit)

Jillian and my portion of this work is complete. @audreykwr will bring together the work we produced and provide final deliverables that include:
- Combine the outlines; create parity between them and their respective structures
- Produce a list of pages to block-frame for the next sprint
