### ISSUE TITLE
South Carolina Onboarding - Validate Test Data

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#9763]
### Acceptance Criteria 
- [ ] Created and sent data using fake data generator 
- [ ] Created and sent data using synthesized data generator 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [ ] Pipelines: Onboarding & Operations (New) 
     - [ ] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [ ] Epics: [select the epic for this API onboarding sender]

**Comment by sliu1000** [comment]
Notes from the last meeting on 9/28/2023

@LaFreda1 did we decide who will replace Don on this?

**Comment by LaFreda1** [comment]
@sliu1000 no, as I mentioned at sprint planning I am waiting for CDC to let us know about SC. We will leave them in the backlog until we can get a response.

**Comment by GlennRGrieves** [comment]
Update and Context to this ticket: South Carolina reached back out (Greg Fowler, an analyst programmer). Max and Glenn met with him on 9/28/23. The conversation was generally focused around RS, asking questions about future states and potential pilot ideas. However, Greg is not a decision maker and it felt more like a general inquiry rather than a STLT read to take an active step. Glenn is going to set up a conversation in the future to continue the dialogue, but I do not anticipate this STLT will be onboarding any time soon.
