### ISSUE TITLE
Arkansas Onboarding - Validate Prod Data

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#9766]
### Acceptance Criteria 
- [x] Sent production data 
- [ ] Confirmed with STLT that data passes validation 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with receiver 
- [x] RS team member who originates this ticket: add any dependencies, as needed 
- [x] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Receiver" and state label 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by GilmoreA6** [comment]
Hi James.

 

I have reviewed the messages sent since last week and there are some errors:

 

Patient Race (PID-10) value of ASKU^Asked, but unknown^NULLFL^^^^2.5.1 failing. Can you block this value from being sent?
There are a number of duplicate messages.  Can you up your ack timeout to 5 minutes?  That usually resolves this issue.
 

Regards,

Eddie

**Comment by GilmoreA6** [comment]
Hi Eddie,

I don't think we need the call today. For the PID-10 value for unknown, what is the correct value that should be applied?

Thanks,

James

**Comment by GilmoreA6** [comment]
Response from Eddie Butler (AR-DOH):

"For unknowns, can you leave the field blank?"

**Comment by GilmoreA6** [comment]
Arkansas says only errors are a few duplicates. Likely due to manual sending of backlog. Will review wil AR at 11/9/23 meeting.
