### ISSUE TITLE
Grant CDC ELIMS team access to STAGING environment

### ISSUE THREAD

**Issue by arnejduranovic** [CDCgov/prime-reportstream#9913]
### User Story

As ReportStream, I need to onboard CDC ELIMS support staff to Okta **STAGING** so they can log in and access the "CDC-ELIMS-HL7" organization

### Description/Use Case

The CDC ELIMS team will need to have OKTA credentials created for the staging environment so they can view their submissions data. 

- Please contact Arnej for list of emails to add to Okta group associated with the `CDC-ELIMS-HL7` organization

### Acceptance Criteria

- [ ] The CDC emails provided by Arnej can access the "CDC-ELIMS-HL7" organization in the RS staging environment

**Comment by bishoyayoub** [comment]
Julie Crowder from ELIMS CDC needs to provide feedback on the above risk.

**Comment by bishoyayoub** [comment]
@arnejduranovic Should I follow up with Julie on this?

**Comment by arnejduranovic** [comment]
@bishoyayoub  Not yet, we are still working with her on requirements and scoping.Ignore all stories in this epic for now. Feel free to add the draft tag to them if it helps!

**Comment by LaFreda1** [comment]
Hey @GilmoreA6, Just got an email from ELIMs on needing access to the staging environment. I am marking this as a high priority since there's platform work that's dependent on this. Let me now if you have any questions.

**Comment by GilmoreA6** [comment]
@arnejduranovic Looks like ELIMS gave us a public key in an email. I can add that to their sender if platform is ready. Also if there's a list of emails that I need to give staging okta accounts I can do that.

**Comment by bishoyayoub** [comment]
@LaFreda1 We need to confirm access for the following three Chris Anderson - [nxq0@cdc.gov](mailto:nxq0@cdc.gov)
Gelu Comanescu -  [xho8@cdc.gov](mailto:xho8@cdc.gov)
Crowder, Julie [quu9@cdc.gov](mailto:quu9@cdc.gov). If the accounts are created and they can confirm that they can login, this ticket should be good to go from Engagement's end.

**Comment by LaFreda1** [comment]
@bishoyayoub Please see James email to the ELIMs team. 

_Hi All,

The public key has been associated to the CDC-ELIMS-HL7 org in staging and activation emails were sent to Christopher Anderson, Gelu Comanescu and Julie Crowder. These emails will have SimpleReport branding on them because of how the Okta instance is configured but they only have access to ReportStream staging. I don't know if there will be anything for them to see with the logins yet as the senders/receivers haven't been created yet.

Thanks,

James

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)_

Platform should be unblocked to complete #10199

**Comment by bishoyayoub** [comment]
@arnejduranovic Do you know what next steps are here based on James' email?

**Comment by arnejduranovic** [comment]
@bishoyayoub yes, but the team still cannot access their accounts (they see the 4XX error that experience team is looking into)
